$name = InputBox("Name", "Please enter your name below.")
$pass = InputBox("Password", "Please enter your password below.")
Run("C:\Program Files\Warcraft III\Frozen Throne.exe")
WinWaitActive("Warcraft III")
Sleep(4000)
Send("B")
Sleep(6000)
MouseClick("left", 177, 128, 1, 0)
Send ("{BS 15}")
Send ($name&"{TAB}"&$pass&"{ENTER}")
Sleep(5000)
Send("C")
