Run("video-editor")
WinWaitActive("Installer Language")
Send("enter")
WinWaitActive("ImTOO Video Editor 1.0.34.1012 Setup","License Agreement")
Send("!a")
WinWaitActive("ImTOO Video Editor 1.0.34.1012 Setup","Choose Install Location")
Send("!n")
WinWaitActive("ImTOO Video Editor 1.0.34.1012 Setup","Choose Start Menu Folder")
Send("!n",)
WinWaitActive("ImTOO Video Editor 1.0.34.1012 Setup","Create shortcut")
Send("!i")
WinWaitActive("Setup - Framing Studio", "Completing the ImTOO Video Editor 1.0.34.1012 setup wizard")
Send("enter")
WinActivate("ImTOO Video Editor (Unregistered)")
WinClose("ImTOO Video Editor (Unregistered)")
