;THE FOLLOWING IS AN EXAMPLE ON HOW TO USE THE CONSTANTS...
;PIECE - 12 VARIATIONS (K.265,Ah! vous dirai-je maman) THEME
;Composer : Wolfgang Amadeus Mozart
;Resequenced by Eynstyne

#include <midiudf.au3>

$open = _midiOutOpen ()

For $i = 27 To 87
   _MidiOutShortMsg ($open, 0x99 + ($i * 256) + (127 * 0x10000)) ; Drums!
   Sleep(200)
Next
For $i = 1 To 2
   _MidiOutShortMsg ($open, 256 * 16 + 192) ;Select Patch 16 Drawbar Organ
   $msg = _midioutshortmsg ($open, $C5_NOTEON)
   $msg = _midioutshortmsg ($open, $C3_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $C5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $C3_NOTEOFF)
   $msg = _midioutshortmsg ($open, $C5_NOTEON)
   $msg = _midioutshortmsg ($open, $C4_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $C5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $C4_NOTEOFF)
   $msg = _midioutshortmsg ($open, $G5_NOTEON)
   $msg = _midioutshortmsg ($open, $E4_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $E4_NOTEOFF)
   $msg = _midioutshortmsg ($open, $G5_NOTEON)
   $msg = _midioutshortmsg ($open, $C4_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $C4_NOTEOFF)
   $msg = _midioutshortmsg ($open, $A5_NOTEON)
   $msg = _midioutshortmsg ($open, $F4_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $A5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $F4_NOTEOFF)
   $msg = _midioutshortmsg ($open, $A5_NOTEON)
   $msg = _midioutshortmsg ($open, $C4_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $A5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $C4_NOTEOFF)
   $msg = _midioutshortmsg ($open, $G5_NOTEON)
   $msg = _midioutshortmsg ($open, $E4_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $E4_NOTEOFF)
   $msg = _midioutshortmsg ($open, $G5_NOTEON)
   $msg = _midioutshortmsg ($open, $C4_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $C4_NOTEOFF)
   $msg = _midioutshortmsg ($open, $F5_NOTEON)
   $msg = _midioutshortmsg ($open, $D4_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $F5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $D4_NOTEOFF)
   $msg = _midioutshortmsg ($open, $F5_NOTEON)
   $msg = _midioutshortmsg ($open, $B3_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $F5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $B3_NOTEOFF)
   $msg = _midioutshortmsg ($open, $E5_NOTEON)
   $msg = _midioutshortmsg ($open, $C4_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $C4_NOTEOFF)
   $msg = _midioutshortmsg ($open, $E5_NOTEON)
   $msg = _midioutshortmsg ($open, $A4_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $A4_NOTEOFF)
   $msg = _midioutshortmsg ($open, $D5_NOTEON)
   $msg = _midioutshortmsg ($open, $F3_NOTEON)
   Sleep(500)
	$msg = _midioutshortmsg ($open, $D5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $F3_NOTEOFF)
   $msg = _midioutshortmsg ($open, $D5_NOTEON)
   $msg = _midioutshortmsg ($open, $G3_NOTEON)
   Sleep(300)
	$msg = _midioutshortmsg ($open, $D5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $G3_NOTEOFF)
   $msg = _midioutshortmsg ($open, $E5_NOTEON)
   Sleep(175)
	$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $C5_NOTEON)
   $msg = _midioutshortmsg ($open, $C3_NOTEON)
   Sleep(1000)
	$msg = _midioutshortmsg ($open, $C5_NOTEOFF)
   $msg = _midioutshortmsg ($open, $C3_NOTEOFF)
Next
$msg = _midioutshortmsg ($open, $G5_NOTEON)
$msg = _midioutshortmsg ($open, $E4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
$msg = _midioutshortmsg ($open, $E4_NOTEOFF)
$msg = _midioutshortmsg ($open, $G5_NOTEON)
$msg = _midioutshortmsg ($open, $G3_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
$msg = _midioutshortmsg ($open, $G3_NOTEOFF)
$msg = _midioutshortmsg ($open, $F5_NOTEON)
$msg = _midioutshortmsg ($open, $D4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $F5_NOTEOFF)
$msg = _midioutshortmsg ($open, $D4_NOTEOFF)
$msg = _midioutshortmsg ($open, $F5_NOTEON)
$msg = _midioutshortmsg ($open, $G3_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $F5_NOTEOFF)
$msg = _midioutshortmsg ($open, $G3_NOTEOFF)
$msg = _midioutshortmsg ($open, $E5_NOTEON)
$msg = _midioutshortmsg ($open, $C4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
$msg = _midioutshortmsg ($open, $C4_NOTEOFF)
$msg = _midioutshortmsg ($open, $E5_NOTEON)
$msg = _midioutshortmsg ($open, $G3_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
$msg = _midioutshortmsg ($open, $G3_NOTEOFF)
$msg = _midioutshortmsg ($open, $D5_NOTEON)
$msg = _midioutshortmsg ($open, $B3_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $D5_NOTEOFF)
$msg = _midioutshortmsg ($open, $B3_NOTEOFF)
$msg = _midioutshortmsg ($open, $D5_NOTEON)
$msg = _midioutshortmsg ($open, $G4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $D5_NOTEOFF)
$msg = _midioutshortmsg ($open, $G4_NOTEOFF)
$msg = _midioutshortmsg ($open, $G5_NOTEON)
$msg = _midioutshortmsg ($open, $E4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
$msg = _midioutshortmsg ($open, $E4_NOTEOFF)
$msg = _midioutshortmsg ($open, $G5_NOTEON)
$msg = _midioutshortmsg ($open, $G4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
$msg = _midioutshortmsg ($open, $G4_NOTEOFF)
$msg = _midioutshortmsg ($open, $F5_NOTEON)
$msg = _midioutshortmsg ($open, $D4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $F5_NOTEOFF)
$msg = _midioutshortmsg ($open, $D4_NOTEOFF)
$msg = _midioutshortmsg ($open, $F5_NOTEON)
$msg = _midioutshortmsg ($open, $G4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $F5_NOTEOFF)
$msg = _midioutshortmsg ($open, $G4_NOTEOFF)
$msg = _midioutshortmsg ($open, $E5_NOTEON)
$msg = _midioutshortmsg ($open, $C4_NOTEON)
Sleep(400)
$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
$msg = _midioutshortmsg ($open, $C4_NOTEOFF)
$msg = _midioutshortmsg ($open, $F5_NOTEON)
Sleep(50)
$msg = _midioutshortmsg ($open, $F5_NOTEOFF)
$msg = _midioutshortmsg ($open, $E5_NOTEON)
Sleep(50)
$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
$msg = _midioutshortmsg ($open, $D5_NOTEON)
Sleep(50)
$msg = _midioutshortmsg ($open, $D5_NOTEOFF)
$msg = _midioutshortmsg ($open, $E5_NOTEON)
Sleep(250)
$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
$msg = _midioutshortmsg ($open, $F5_NOTEON)
$msg = _midioutshortmsg ($open, $D4_NOTEON)
Sleep(150)
$msg = _midioutshortmsg ($open, $F5_NOTEOFF)
$msg = _midioutshortmsg ($open, $D4_NOTEOFF)
$msg = _midioutshortmsg ($open, $E5_NOTEON)
$msg = _midioutshortmsg ($open, $C4_NOTEON)
$msg = _midioutshortmsg ($open, $G3_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
$msg = _midioutshortmsg ($open, $C4_NOTEOFF)
$msg = _midioutshortmsg ($open, $G3_NOTEOFF)
$msg = _midioutshortmsg ($open, $D5_NOTEON)
$msg = _midioutshortmsg ($open, $B3_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $D5_NOTEOFF)
$msg = _midioutshortmsg ($open, $B3_NOTEOFF)
$msg = _midioutshortmsg ($open, $C5_NOTEON)
$msg = _midioutshortmsg ($open, $C3_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $C5_NOTEOFF)
$msg = _midioutshortmsg ($open, $C3_NOTEOFF)
$msg = _midioutshortmsg ($open, $C5_NOTEON)
$msg = _midioutshortmsg ($open, $C4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $C5_NOTEOFF)
$msg = _midioutshortmsg ($open, $C4_NOTEOFF)
$msg = _midioutshortmsg ($open, $G5_NOTEON)
$msg = _midioutshortmsg ($open, $E4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
$msg = _midioutshortmsg ($open, $E4_NOTEOFF)
$msg = _midioutshortmsg ($open, $G5_NOTEON)
$msg = _midioutshortmsg ($open, $C4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
$msg = _midioutshortmsg ($open, $C4_NOTEOFF)
$msg = _midioutshortmsg ($open, $A5_NOTEON)
$msg = _midioutshortmsg ($open, $F4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $A5_NOTEOFF)
$msg = _midioutshortmsg ($open, $F4_NOTEOFF)
$msg = _midioutshortmsg ($open, $A5_NOTEON)
$msg = _midioutshortmsg ($open, $C4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $A5_NOTEOFF)
$msg = _midioutshortmsg ($open, $C4_NOTEOFF)
$msg = _midioutshortmsg ($open, $G5_NOTEON)
$msg = _midioutshortmsg ($open, $E4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
$msg = _midioutshortmsg ($open, $E4_NOTEOFF)
$msg = _midioutshortmsg ($open, $G5_NOTEON)
$msg = _midioutshortmsg ($open, $C4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $G5_NOTEOFF)
$msg = _midioutshortmsg ($open, $C4_NOTEOFF)
$msg = _midioutshortmsg ($open, $F5_NOTEON)
$msg = _midioutshortmsg ($open, $D4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $F5_NOTEOFF)
$msg = _midioutshortmsg ($open, $D4_NOTEOFF)
$msg = _midioutshortmsg ($open, $F5_NOTEON)
$msg = _midioutshortmsg ($open, $B3_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $F5_NOTEOFF)
$msg = _midioutshortmsg ($open, $B3_NOTEOFF)
$msg = _midioutshortmsg ($open, $E5_NOTEON)
$msg = _midioutshortmsg ($open, $C4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
$msg = _midioutshortmsg ($open, $C4_NOTEOFF)
$msg = _midioutshortmsg ($open, $E5_NOTEON)
$msg = _midioutshortmsg ($open, $A4_NOTEON)
Sleep(500)
$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
$msg = _midioutshortmsg ($open, $A4_NOTEOFF)
$msg = _midioutshortmsg ($open, $D5_NOTEON)
$msg = _midioutshortmsg ($open, $F3_NOTEON)
Sleep(400)
$msg = _midioutshortmsg ($open, $D5_NOTEOFF)
$msg = _midioutshortmsg ($open, $F3_NOTEOFF)
$msg = _midioutshortmsg ($open, $E5_NOTEON)
Sleep(50)
$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
$msg = _midioutshortmsg ($open, $D5_NOTEON)
Sleep(50)
$msg = _midioutshortmsg ($open, $D5_NOTEOFF)
$msg = _midioutshortmsg ($open, $C5_NOTEON)
Sleep(50)
$msg = _midioutshortmsg ($open, $C5_NOTEOFF)
$msg = _midioutshortmsg ($open, $D5_NOTEON)
Sleep(250)
$msg = _midioutshortmsg ($open, $D5_NOTEOFF)
$msg = _midioutshortmsg ($open, $E5_NOTEON)
$msg = _midioutshortmsg ($open, $G3_NOTEON)
Sleep(150)
$msg = _midioutshortmsg ($open, $E5_NOTEOFF)
$msg = _midioutshortmsg ($open, $G3_NOTEOFF)
$msg = _midioutshortmsg ($open, $C5_NOTEON)
$msg = _midioutshortmsg ($open, $C3_NOTEON)
Sleep(1000)
$msg = _midioutshortmsg ($open, $C5_NOTEOFF)
$msg = _midioutshortmsg ($open, $C3_NOTEOFF)
_MidiOutClose ($open)