; <COMPILER: v3.0.92.0>
AutoItSetOption ("TrayIconHide", 1)
$newuser = RegRead ("HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "EnableBalloonTips")
if $newuser = 0 Then
Exit
Else
Call ("NewUser")
Endif
Func NewUser()
ProgressOn ("New User Detected", "Updating desktop.", "", -1, -1, 2)
Sleep (1000)
RegWrite ("HKEY_CURRENT_USER\Control Panel\Desktop", "Wallpaper", "REG_SZ", "C:\WINDOWS\Web\Wallpaper\Bliss.bmp")
RegWrite ("HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\WindowsUpdate", "DisableWindowsUpdateAccess", "REG_DWORD", "00000001")
RegWrite ("HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer", "NoWindowsUpdate", "REG_DWORD", "00000001")
RegWrite ("HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main", "IEWatsonEnabled", "REG_DWORD", "0")
RegWrite ("HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main", "Window Title", "REG_SZ", "Internet Explorer Provided By BPB In North America")
ProgressSet (10)
Sleep (1000)
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\RasMan\Parameters", "DisableSavePassword", "REG_DWORD", "1")
RegWrite ("HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings", "AutoConfigURL", "REG_SZ", "                                 ")
ProgressSet (20)
Sleep (1000)
RegWrite ("HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "EnableBalloonTips", "REG_DWORD", "0")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanWorkstation", "MaxCmds", "REG_DWORD", "0x0000001e")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanWorkstation", "MaxThreads", "REG_DWORD", "0x0000001e")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanWorkstation", "MaxCollectionCount", "REG_DWORD", "0x00000020")
ProgressSet (30)
Sleep (1000)
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\BridgeMP", "DisableForwarding", "REG_DWORD", "0x00000001")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\BridgeMP", "DisableSTA", "REG_DWORD", "0x00000001")
ProgressSet (40)
Sleep (1000)
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server", "AllowTSConnections", "REG_DWORD", "0x00000000")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server", "fDenyTSConnections", "REG_DWORD", "0x00000001")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server", "fAllowToGetHelp", "REG_DWORD", "0x00000000")
ProgressSet (50)
Sleep (1000)
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "EnableDeadGWDetect", "REG_DWORD", "0")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "EnableICMPRedirect", "REG_DWORD", "0")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "EnablePMTUDiscovery", "REG_DWORD", "0")
ProgressSet (60)
Sleep (1000)
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "KeepAliveTime", "REG_DWORD", "300000")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "NoNameReleaseOnDemand", "REG_DWORD", "1")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "PerformRouteDiscovery", "REG_DWORD", "0")
ProgressSet (70)
Sleep (1000)
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "SynAttackProtect", "REG_DWORD", "0x00000002")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "EnablePMTUDiscovery", "REG_DWORD", "1")
RegWrite ("HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole", "SecurityLevel", "REG_DWORD", "1")
ProgressSet (80)
Sleep (1000)
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "ClearPageFileAtShutdown", "REG_DWORD", "1")
RegWrite ("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Messenger", "Start", "REG_DWORD", "0x00000004")
RegWrite ("HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole", "SecurityLevel", "REG_DWORD", "0")
RegWrite ("HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "MinAnimate", "REG_SZ", "0")
RegWrite ("HKEY_CURRENT_USER\Control Panel\Desktop", "SmoothScroll", "REG_DWORD", "0")
RegDelete ("HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run", "ibmmessages")
RegDelete ("HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run", "Mouse Suite 98 Daemon")
RegDelete ("HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run", "ibmmessages")
RegDelete ("HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run", "msmsgs")
ProgressSet (90)
Sleep (1000)
RegWrite ("HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer", "ShellState", "REG_BINARY", "2400000030280000000000000000000000000000010000000D0000000000000000000000")
RegWrite ("HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer", "ClassicShell", "REG_DWORD", "1")
RegWrite ("HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer", "ClassicShell", "REG_DWORD", "1")
RegWrite ("HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "CaptionHeight", "REG_SZ", "-300")
RegWrite ("HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "CaptionWidth", "REG_SZ", "-270")
RegWrite ("HKEY_CURRENT_USER\Control Panel\Desktop", "Wallpaper", "REG_SZ", "C:\WINDOWS\Web\Wallpaper\Bliss.bmp")
RegWrite ("HKEY_LOCAL_MACHINE\SOFTWARE\Novell\Login", "Local Login", "REG_DWORD", "0")
RegWrite ("HKEY_LOCAL_MACHINE\SOFTWARE\Novell\Login", "Default WS Only", "REG_DWORD", "0")
ProgressSet (100)
Sleep (2000)
ProgressOff()
$r = @AppDataDir & "\ICAClient\*.*"
DirCreate ( @AppDataDir & "\ICAClient")
FileCopy ("C:\Windows\Options\pn.ini", $r, 1)
SplashTextOn ("New User", "New user updated. Now Rebooting", 400, 25)
Sleep (3000)
SplashOff ()
Shutdown (2)
Exit
EndFunc
