;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                                                       ;;
;;  AutoIt Version: 3.2.4.9                                                              ;;
;;                                                                                       ;;
;;  Template AutoIt script.                                                              ;;
;;                                                                                       ;;
;;  AUTHOR:  TheSaint <thsaint@ihug.com.au>                                              ;;
;;                                                                                       ;;
;;  SCRIPT FUNCTION:  Create a CD Cover using details from CDIni Database v5.8           ;;
;;                                                                                       ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

#region --- GuiBuilder code Start ---
; Script generated by AutoBuilder 0.7 Prototype

#include <GuiConstants.au3>

Global $Button_exit, $Button_insert
Global $Group_left, $Group_options, $Group_right
Global $Slider_left, $Slider_right

Global $CDCover, $Insert

Global $album, $artini, $artist, $cdtitle, $id, $top

If $CmdLine[0] <> 0 Then
	$id = $CmdLine[1]
	$artist = $CmdLine[2]
	$dbase = @ScriptDir & "\Database"
	$artini = $dbase & "\" & $artist & ".ini"
	If FileExists($artini) Then
		$album = IniRead($artini, $id, "title", "")
		$cdtitle = $artist & " - " & $album
	Else
		Exit
	EndIf
EndIf

$Insert = @ScriptDir & "\Insert.exe"

$top = (@DesktopHeight - 495) / 2
$CDCover = GuiCreate("CDCover v1.0", 640, 495, -1, $top, $WS_OVERLAPPED + $WS_CAPTION + $WS_SYSMENU + $WS_VISIBLE + $WS_CLIPSIBLINGS + $WS_MINIMIZEBOX)
;
; CONTROLS
$Group_left = GuiCtrlCreateGroup("", 10, 10, 50, 417)
$Slider_left = GuiCtrlCreateSlider(15, 20, 40, 405, $TBS_VERT + $TBS_BOTH + $TBS_AUTOTICKS)
;
$Group_right = GuiCtrlCreateGroup("", 580, 10, 50, 417)
$Slider_right = GuiCtrlCreateSlider(585, 20, 40, 405, $TBS_VERT + $TBS_BOTH + $TBS_AUTOTICKS)
;
$Group_options = GuiCtrlCreateGroup("", 10, 420, 620, 65)
$Button_insert = GUICtrlCreateButton("INSERT", 20, 440, 70, 35)
GUICtrlSetFont($Button_insert, 9, 600)
$Button_book = GUICtrlCreateButton("BOOKLET", 110, 440, 80, 35)
GUICtrlSetFont($Button_book, 9, 600)
$Button_print = GUICtrlCreateButton("PRINT", 210, 440, 70, 35)
GUICtrlSetFont($Button_print, 9, 600)
$Button_exit = GUICtrlCreateButton("EXIT", 550, 440, 70, 35)
GUICtrlSetFont($Button_exit, 9, 600)
;
; SETTINGS
GUICtrlSetLimit($Slider_left, 200, 0)
GUICtrlSetLimit($Slider_right, 200, 0)
;

GuiSetState()
While 1
	$msg = GuiGetMsg()
	Select
	Case $msg = $GUI_EVENT_CLOSE
		GUIDelete($CDCover)
		ExitLoop
	Case $msg = $Button_print
		; PRINT
		GUIDelete($CDCover)
		ExitLoop
	Case $msg = $Button_insert
		; INSERT
		If FileExists($Insert) Then Run($Insert & ' ' & $id & ' "' & $artist & '"')
	Case $msg = $Button_exit
		ProcessClose("Insert.exe")
		GUIDelete($CDCover)
		ExitLoop
	Case $msg = $Button_book
		; BOOKLET
		ProcessClose("Insert.exe")
	Case Else
		;;;
	EndSelect
WEnd
Exit
#endregion --- GuiBuilder generated code End ---
