; Script generated by AutoBuilder 0.6 Prototype
#include <GuiConstants.au3>
#include "constants.au3"
#include <array.au3>
#include <date.au3>
ProgressOn("Please Wait...", "Gathering Information")
$UsedSpace = DriveSpaceTotal(@HomeDrive) & "(MB)"
$FreeSpace = DriveSpaceFree(@HomeDrive) & "(MB)"
$FileSystem = DriveGetFileSystem(@HomeDrive)
$DriveLabel = DriveGetLabel(@HomeDrive)
$DriveSerial = DriveGetSerial(@HomeDrive)
$DriveType = DriveGetType(@HomeDrive)
$DriveStatus = DriveStatus(@HomeDrive)
ProgressSet(100)
Sleep(2000)
ProgressOff()
GUICreate("Computer Diagnostics", 657, 559, -1, -1, BitOR($WS_OVERLAPPEDWINDOW, $WS_CLIPSIBLINGS))
$ProcessGroup = GUICtrlCreateGroup("Process Information", 6, 22, 360, 270)
$ProcessList = GUICtrlCreateList("", 12, 67, 351, 110)
$RunningProcessesLabel = GUICtrlCreateLabel("Running Processes", 118, 45, 115, 15)
$ProcessDescLabel = GUICtrlCreateLabel("Process Description:", 14, 198, 119, 20)
$ProcessDesc = GUICtrlCreateLabel("Description", 36, 221, 280, 49)
$SystemInformationGroup = GUICtrlCreateGroup("System Information", 6, 304, 358, 243)
$SoftwareInformationGroup = GUICtrlCreateGroup("Software Information", 371, 22, 283, 270)
$MiscInfoGroup = GUICtrlCreateGroup("Misc. Information", 370, 303, 279, 244)
;System Information
GUICtrlCreateLabel("Windows Version: " & " " & $WindowsVer, 50, 330)
GUICtrlCreateLabel("Windows Build: " & " " & $BUILD, 50, 350)
GUICtrlCreateLabel("Windows Service pack: " & " " & $ServicePack, 50, 370)
GUICtrlCreateLabel("Windows Defualt Language: " & " " & _Language(), 50, 390)
GUICtrlCreateLabel("Used Hard Drive Space: " & " " & $UsedSpace, 50, 410)
GUICtrlCreateLabel("Free Hard Drive Space: " & " " & $FreeSpace, 50, 430)
GUICtrlCreateLabel("Hard Drive Label: " & " " & $DriveLabel, 50, 450)
GUICtrlCreateLabel("Hard Drive Serial: " & " " & $DriveSerial, 50, 470)
GUICtrlCreateLabel("Hard Drive Type: " & " " & $DriveType, 50, 490)
GUICtrlCreateLabel("Hard Drive Status: " & " " & $DriveStatus, 50, 510)
;Software Information
GUICtrlCreateLabel("Java Version: " & $JavaVer, 380, 50)
$CookiesSize = DirGetSize($CookiesDir) / 1024 & "(KB)"
$TemPSize = DirGetSize($TempDir) / 1024 & "(KB)"
$Cookie_Label = GUICtrlCreateLabel("Cookies Size: " & $CookiesSize, 380, 70)
$TempLabel = GUICtrlCreateLabel("Temp Size: " & $TemPSize, 380, 90)
$DelCookies = GUICtrlCreateButton("Delete Cookies", 380, 110, 100, -1)
$DelTemp = GUICtrlCreateButton("Delete Temp", 480, 110, 100, -1)
;Misc. Information
GUICtrlCreateLabel("Installed Fonts", 380, 320)
$FontList = GUICtrlCreateList("", 380, 350, 250, 100)
$Time = GUICtrlCreateLabel("System Time: ", 380, 500)
$TimeObject = GUICtrlCreateLabel("", 490, 500, 100, 100)
$Fonts = _FileListToArray (@HomeDrive & "\windows\fonts", "*.ttf", 1)
For $i = 1 To $Fonts[0]
 GUICtrlSetData($FontList, $Fonts[$i])
Next
GUISetState()
$Process = ProcessList()
For $i = 1 To $Process[0][0]
 GUICtrlSetData($ProcessList, $Process[$i][0])
Next
While 1
 GUICtrlSetData($TimeObject, _NowTime())
 $DescData = GUICtrlRead($ProcessList)
 If $DescData = "explorer.exe" Then
  $ProcData = "Microsoft Windows Explorer"
 Else
  If $DescData = "alg.exe" Then
   $ProcData = "Microsoft Windows Application Layer Gateway Service"
  Else
   If $DescData = "wscntfy.exe" Then
    $ProcData = "Windows Security Center"
   Else
    If $DescData = "hkcmd.exe" Then
     $ProcData = "Intel Hotkey command activator"
    Else
     If $DescData = "cidaemon.exe" Then
      $ProcData = "Microsoft Indexing Service"
     Else
      If $DescData = "msnmsgr.exe" Then
       $ProcData = "MSN Messenger"
      Else
       If $DescData = "igfxtray.exe" Then
        $ProcData = "Intel(R) Graphics Accelerator Helper"
       Else
        If $DescData = "cisvc.exe" Then
         $ProcData = "Microsoft Index Service Helper"
        Else
         If $DescData = "spoolsv.exe" Then
          $ProcData = "Microsoft Printer Spooler Service"
         Else
          If $DescData = "svchost.exe" Then
           $ProcData = "Microsoft Service Host Process"
          Else
           If $DescData = "mqtgsvc.exe" Then
            $ProcData = "Message Queuing Triggers Service"
           Else
            If $DescData = "iexplore.exe" Then
             $ProcData = "Microsoft Internet Explorer"
            Else
             If $DescData = "lsass.exe" Then
              $ProcData = "Local Security Authority Service"
             Else
              If $DescData = "services.exe" Then
               $ProcData = "Windows Service Controller"
              Else
               If $DescData = "winlogon.exe" Then
                $ProcData = "Microsoft Windows Logon Process"
               Else
                If $DescData = "csrss.exe" Then
                 $ProcData = "Microsoft Client/Server Runtime Server Subsystem"
                Else
                 If $DescData = "smss.exe" Then
                  $ProcData = "Session Manager Subsystem"
                 Else
                  If $DescData = "mqsvc.exe" Then
                   $ProcData = "Microsoft Message Queue Server"
                  Else
                   If $DescData = "taskmgr.exe" Then
                    $ProcData = "Windows Task Manager"
                   Else
                    If $DescData = "wdfmgr.exe" Then
                     $ProcData = "Windows Driver Foundation Manager"
                    Else
                     If $DescData = "[System Process]" Then
                      $ProcData = "System Idle Process"
                     Else
                      $Files = StringSplit($DescData, ".")
                      $ProcData = $Files[1]
                     EndIf
                    EndIf
                   EndIf
                  EndIf
                 EndIf
                EndIf
               EndIf
              EndIf
             EndIf
            EndIf
           EndIf
          EndIf
         EndIf
        EndIf
       EndIf
      EndIf
     EndIf
    EndIf
   EndIf
  EndIf
  GUICtrlSetData($ProcessDesc, $ProcData)
 EndIf
 $msg = GUIGetMsg()
 Select
  Case $msg = $GUI_EVENT_CLOSE
   ExitLoop
  Case $msg = $DelCookies
   DelCookies()
  Case $msg = $DelTemp
   DelTemp()
 EndSelect
WEnd
Func _Language()
 Select
  Case StringInStr("0413,0813", @OSLang)
   Return "Dutch"
  Case StringInStr("0409,0809,0c09,1009,1409,1809,1c09,2009, 2409,2809,2c09,3009,3409", @OSLang)
   Return "English"
  Case StringInStr("040c,080c,0c0c,100c,140c,180c", @OSLang)
   Return "French"
  Case StringInStr("0407,0807,0c07,1007,1407", @OSLang)
   Return "German"
  Case StringInStr("0410,0810", @OSLang)
   Return "Italian"
  Case StringInStr("0414,0814", @OSLang)
   Return "Norwegian"
  Case StringInStr("0415", @OSLang)
   Return "Polish"
  Case StringInStr("0416,0816", @OSLang)
   Return "Portuguese"
  Case StringInStr("040a,080a,0c0a,100a,140a,180a,1c0a,200a, 240a,280a,2c0a,300a,340a,380a,3c0a,400a, 440a,480a,4c0a,500a", @OSLang)
   Return "Spanish"
  Case StringInStr("041d,081d", @OSLang)
   Return "Swedish"
  Case Else
   Return "Other (can't determine with @OSLang directly)"
 EndSelect
EndFunc   ;==>_Language
Func DelCookies()
 FileDelete(@HomeDrive & "\documents and settings\" & @UserName & "\cookies\*.*")
 MsgBox(0, "Complete!", "Completed Deleting Files!", 3)
 GUICtrlSetData($Cookie_Label, "Cookies Size: " & DirGetSize(@HomeDrive & "\Documents and Settings\" & @UserName & "\Cookies") / 1024 & "(KB)")
EndFunc   ;==>DelCookies
Func DelTemp()
 ProgressOn("Deleting Temp", "please wait...")
 FileDelete(@HomeDrive & "windows\temp\*.*")
 ProgressSet(100)
 ProgressOff()
 MsgBox(0, "Complete!", "Files deleted successfuly!", 3)
 GUICtrlSetData($TempLabel, "Temp Size: " & DirGetSize(@HomeDrive & "\windows\temp\") / 1024 & "(KB)")
EndFunc   ;==>DelTemp
Exit
