Opt("WinWaitDelay", 100)
Opt("WinTitleMatchMode", 4)
Opt("WinDetectHiddenText", 1)
Opt("MouseCoordMode", 0)
Run('Firefox.exe')
WinWait("Mozilla Firefox Setup", "Welcome to the Mozil")
If Not WinActive("Mozilla Firefox Setup", "Welcome to the Mozil") Then WinActivate("Mozilla Firefox Setup", "Welcome to the Mozil")
WinWaitActive("Mozilla Firefox Setup", "Welcome to the Mozil")
Send("{ALTDOWN}n{ALTUP}")
WinWait("Mozilla Firefox Setup", "Choose setup options")
If Not WinActive("Mozilla Firefox Setup", "Choose setup options") Then WinActivate("Mozilla Firefox Setup", "Choose setup options")
WinWaitActive("Mozilla Firefox Setup", "Choose setup options")
Send("{ALTDOWN}u{ALTUP}{ALTDOWN}n{ALTUP}")
WinWait("Mozilla Firefox Setup", "Ready to start insta")
If Not WinActive("Mozilla Firefox Setup", "Ready to start insta") Then WinActivate("Mozilla Firefox Setup", "Ready to start insta")
WinWaitActive("Mozilla Firefox Setup", "Ready to start insta")
Send("{ALTDOWN}i{ALTUP}")
WinWait("Mozilla Firefox Setup ", "Completing the Mozil")
If Not WinActive("Mozilla Firefox Setup ", "Completing the Mozil") Then WinActivate("Mozilla Firefox Setup ", "Completing the Mozil")
WinWaitActive("Mozilla Firefox Setup ", "Completing the Mozil")
Send("{ALTDOWN}l{ALTUP}{ALTDOWN}f{ALTUP}")
