;guiflashexample 
;Author : Arcker
#include "FlashWindow.au3"
#region --- GuiBuilder code Start ---
; Script generated by AutoBuilder 0.6 Prototype
;just run and activate another window , and the gui will flash continuosly until it's on the foreground
#include <GuiConstants.au3>

$form=GuiCreate("GUI Window Example", 392, 323,-1, -1 , BitOR($WS_OVERLAPPEDWINDOW, $WS_CLIPSIBLINGS))
consolewrite($form & @crlf)

GuiSetState()

$set = 0
While 1
	$msg = GuiGetMsg()
	$hwnd=WinGetHandle("")
	Select
		case $hwnd <> $form 
			;if $set=0 then _FlashWindow($form)	
			if $set=0 then WinFlash($form)	
				$set =1
	Case $msg = $GUI_EVENT_CLOSE
		ExitLoop
	Case Else
		;;;
	
EndSelect
sleep(100)
WEnd
Exit
#endregion --- GuiBuilder generated code End ---

