#region --- GuiBuilder code Start ---
; Script generated by AutoBuilder 0.5 Prototype

#include <GuiConstants.au3>
GuiCreate("division", 392, 322,(@DesktopWidth-392)/2, (@DesktopHeight-322)/2 )

$Button_1 = GuiCtrlCreateButton("---->click here<----", 90, 20, 150, 20)
$Button_2 = GuiCtrlCreateButton("---->click here<----", 90, 70, 150, 20)
$Button_3 = GuiCtrlCreateButton("_-~calculate ~-_", 110, 140, 110, 40)
$Button_4 = GuiCtrlCreateButton("<----back", 10, 10, 80, 20)
GuiSetState()
While 1
	$msg = GuiGetMsg()
	Select
	Case $msg = $GUI_EVENT_CLOSE
					MsgBox(0, "are you sure?", "are you sure you would like to exit? click ok below")
$1 = InputBox("exit?", "type yes to exit or if not just close this box")
if $1 = "yes" then ExitLoop
	Case $msg = $button_1
		$input = InputBox("division", "type 1 number below to be divided")
		if @error then ContinueLoop
			GUICtrlSetData($button_1,$input)
			Case $msg = $button_2
		$iinput = InputBox("division", "type 1 number below to be divided")
		if @error then ContinueLoop
			GUICtrlSetData($button_2,$input)
			Case $msg = $button_3
		$messege = MsgBox(0,"", $input / $iinput)
		if @error then ContinueLoop
				Case $msg = $button_4
			Run("calculater.exe")
				ExitLoop
			if @error then ContinueLoop
	EndSelect
WEnd
Exit
#endregion --- GuiBuilder generated code End ---

