$emails = InputBox("How many emails?", "How many emails?")
$10seconds = msgbox(0,"You now have 10 seconds", "You have 10 seconds to click into the text file at the beginning")
sleep(10000)

;Opens excel
Send("#r")
WinWaitActive("Run")
Send("excel{Enter}")
sleep(9000)
send("!f")
send("a")
winwaitactive("Save As")
sleep(200)
send("c:\cribtentfinal")
send("{enter}")
sleep(200)
send("Date")
send("{TAB}")
send("Name")
send("{TAB}")
send("Country")
send("{TAB}")
send("Street Address")
send("{TAB}")
send("City")
send("{TAB}")
send("State")
send("{TAB}")
send("Zip Code")
send("{TAB}")
send("Telephone")
send("{TAB}")
send("Email")
send("{TAB}")
send("Quantity")
send("{TAB}")
send("Consumer or Retailer")
send("{TAB}")
send("Comments")
send("{TAB}")
send("{DOWN}")
send("{HOME}")
send("!{TAB}")
WinWaitActive("cribtentexport")
;Loop to copy and paste all data from exported text to excel database

$i = 0
while $i <= $emails
	$i = $i + 1
;Date
WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("Sent")
	send("{enter}")
	send("{ESC}")
	send("{HOME}{CTRLDOWN}{RIGHT}{RIGHT}{SHIFTDOWN}{RIGHT}{RIGHT}{RIGHT}{SHIFTUP}{CTRLUP}")
	sleep(200)
	send("^c")
	sleep(200)
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
	sleep(200)
	send("!{TAB}")
	sleep(200)
;Name
WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("Name")
	send("{enter}")
	send("{ESC}")
	send("{DOWN}{DOWN}{HOME}{DEL}{DEL}{SHIFTDOWN}{END}{SHIFTUP}")
	sleep(200)
	send("^c")
	sleep(200)
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
	sleep(200)
	send("!{TAB}")
	sleep(200)
;Country
	WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("Country")
	send("{enter}")
	send("{ESC}")
	send("{DOWN}{DOWN}{HOME}{DEL}{DEL}{SHIFTDOWN}{END}{SHIFTUP}")
	sleep(200)
	send("^c")
	sleep(200)
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
	sleep(200)
	send("!{TAB}")
	sleep(200)
;Street Address
	WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("Street Address")
	send("{enter}")
	send("{ESC}")
	send("{DOWN}{DOWN}{HOME}{DEL}{DEL}{SHIFTDOWN}{END}{SHIFTUP}")
	sleep(200)
	send("^c")
	sleep(200)
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
	sleep(200)
	send("!{TAB}")
	sleep(200)
;City
	WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("City")
	send("{enter}")
	send("{ESC}")
	send("{DOWN}{DOWN}{HOME}{DEL}{DEL}{SHIFTDOWN}{END}{SHIFTUP}")
	sleep(200)
	send("^c")
	sleep(200)
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
	sleep(200)
	send("!{TAB}")
	sleep(200)
;State
	WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("State")
	send("{enter}")
	send("{ESC}")
	send("{DOWN}{DOWN}{HOME}{DEL}{DEL}{SHIFTDOWN}{END}{SHIFTUP}")
	sleep(200)
	send("^c")
	sleep(200)
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
	sleep(200)
	send("!{TAB}")
	sleep(200)
;Zip Code
	WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("Zip Code")
	send("{enter}")
	send("{ESC}")
	send("{DOWN}{DOWN}{HOME}{DEL}{DEL}{SHIFTDOWN}{END}{SHIFTUP}")
	sleep(200)
	send("^c")
	sleep(200)
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
	sleep(200)
	send("!{TAB}")
	sleep(200)
;Telephone
	WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("Telephone")
	send("{enter}")
	send("{ESC}")
	send("{DOWN}{DOWN}{HOME}{DEL}{DEL}{SHIFTDOWN}{END}{SHIFTUP}")
	sleep(200)
	send("^c")
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
	sleep(200)
	send("!{TAB}")
	sleep(200)
;Email
	WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("Email")
	send("{enter}")
	send("{ESC}")
	send("{DOWN}{DOWN}{HOME}{DEL}{DEL}{SHIFTDOWN}{END}{SHIFTUP}")
	sleep(200)
	send("^c")
	sleep(200)
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
	sleep(200)
	send("!{TAB}")
	sleep(200)
;Quantity
	WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("Quantity")
	send("{enter}")
	send("{ESC}")
	send("{DOWN}{DOWN}{HOME}{DEL}{DEL}{SHIFTDOWN}{END}{SHIFTUP}")
	sleep(200)
	send("^c")
	sleep(200)
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
	sleep(200)
	send("!{TAB}")
	sleep(200)
;Consumer or Retailer
	WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("Consumer or Retailer")
	send("{enter}")
	send("{ESC}")
	send("{DOWN}{DOWN}{HOME}{DEL}{DEL}{SHIFTDOWN}{END}{SHIFTUP}")
	sleep(200)
	send("^c")
	sleep(200)
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
	sleep(200)
	send("!{TAB}")
	sleep(200)
;Comments
	WinWaitActive("[CLASS:Notepad]")
	send("^f")
	winwaitactive("Find")
	send("Comments")
	send("{enter}")
	send("{ESC}")
	send("{DOWN}{DOWN}{HOME}{SHIFTDOWN}{END}{SHIFTUP}")
	sleep(200)
	send("^c")
	sleep(200)
	send("!{TAB}")
	winwaitactive("Microsoft Excel")
	sleep(200)
	send("^v")
	send("{TAB}")
			send("{DOWN}")
			send("{HOME}")
	sleep(200)
	send("!{TAB}")
	sleep(200)

WEnd

