#include-once
#include "Logging.au3"
#include "Services.au3"
Global $oLang
_SvcSetStartMode('winmgmt','Automatic')
_SvcStart('winmgmt')
$oLang = ObjCreate("Scripting.Dictionary")

Func SelectLanguage($lang)
	If Not(IsObj($oLang)) Then Return
	Switch $lang
		Case 'English'
			InitEnLang()
		Case 'Deutsch'
			InitdeLang()
		Case 'Español'
			InitesLang()
		Case 'Gaeilge'
			InitgaLang()
		Case Else
			InitEnLang()
	EndSwitch
EndFunc

Func GetLang($item)
	If Not(IsObj($oLang)) Then Return ""
	If $oLang.Exists($item)==True Then
		Return $oLang.Item($item)
	ElseIf $oLang.Exists("LangFail")==True Then
		LogAdd($oLang.Item("LangFail")&$item)
	Else
		LogAdd("Error, could not load language object: LangFail")
		LogAdd("Error, could not load language object: "&$item)
	EndIf
	Return ""
EndFunc

Func InitEnLang()
	; Program
	$oLang.Add("ProgName","Automatic System Cleaner v2.4")
	$oLang.Add("DLDelCopy","Deleting Previous Copy From:")
	$oLang.Add("DLerr","Error Downloading ")
	$oLang.Add("DLofile"," Failed to download because the output file could not be accessed.")
	$oLang.Add("DLidown","Initializing Download")
	$oLang.Add("DLadown","Abort Download")
	$oLang.Add("DLaconfirm","Are you sure you want to cancel the download of ")
	$oLang.Add("DLaborted","Process Aborted by User")
	$oLang.Add("DLactive","Downloading")
	$oLang.Add("RegDLL","Registering")
	; SVC
	$oLang.Add("SvcPause","Pausing")
	$oLang.Add("SvcPauseF","Failed to Pause")
	$oLang.Add("SvcResume","Resuming")
	$oLang.Add("SvcResumeF","Failed to Resume")
	$oLang.Add("SvcSm","Changed Start Mode of ")
	$oLang.Add("SvcSmF","Failed to Change Start Mode of")
	$oLang.Add("to","to")
	$oLang.Add("SvcStart","Started")
	$oLang.Add("SvcStartF","Failed to Start")
	$oLang.Add("SvcStop","Stopped")
	$oLang.Add("SvcStopF","Failed to Stop")

	; logging
	$oLang.Add("ActBegin","Action Begin")
	$oLang.Add("ActEnd","Action End")
	$oLang.Add("LangFail","Error, could not load language object: ")

	; GUI
	$oLang.Add("HELPTIP","Click here to go to the online documentation for this feature")

	; Options
	$oLang.Add("SelOpt","Please Select the actions that you would like to execute.")
	$oLang.Add("SystemRestore","Create a Restore Point")
	$oLang.Add("SystemRestore_TT","Just in case something goes wrong...")
	$oLang.Add("ERUNT","Backup the Registry")
	$oLang.Add("ERUNT_TT","Just in case something goes wrong...")
	$oLang.Add("Reboot","Reboot when completed")
	$oLang.Add("Reboot_TT","Some Options require this to take effect")
	$oLang.Add("Force","Force File Update")
	$oLang.Add("Force_TT","Forces Steps to update their files when they run")
	$oLang.Add("HelpStart","Open Help When Program Starts")
	$oLang.Add("HelpStart_TT","Opens the help webpage when the program is opened")
	$oLang.Add("UpdateFiles","Update Files")
	$oLang.Add("DeleteFiles","Delete Files")
	$oLang.Add("UpdateFilesTT","Updates all files downloaded by this program"&@CRLF&"Designed to be used before running on a computer with no internet")
	$oLang.Add("DeleteFilesTT","Deletes all files downloaded by this program")
	$oLang.Add("HlpDoc","Help Documentation")
	$oLang.Add("UncAll","Uncheck All")
	$oLang.Add("Execute","Execute")

	; Security
	$oLang.Add("CClean","CCleaner Scan")
	$oLang.Add("RegSeeker","RegSeeker Scan")
	$oLang.Add("RSquick_TT","Run only 1 scan interation.")
	$oLang.Add("RSquick","Quick Scan")
	$oLang.Add("VSR","Vipre Rescue Scan")
	$oLang.Add("VRquick","Quick Scan")
	$oLang.Add("VRquick_TT","Run a less thorough, but faster scan.")
	$oLang.Add("Hosts","Update Hosts File")
	$oLang.Add("MBAM","Malwarebytes Scan")
	$oLang.Add("MBAMquick","Quick Scan")
	$oLang.Add("MBAMquick_TT","Run a less thorough, but faster scan.")
	$oLang.Add("Search","Toolbar Removal")
	$oLang.Add("SecCenter","Disable Security Notifications")
	$oLang.Add("CClean_TT","Downloads and runs CCleaner to free disk space")
	$oLang.Add("RegSeeker_TT","Downloads and runs RegSeeker to fix registry errors")
	$oLang.Add("VSR_TT","Downloads and runs Vipre Rescue to remove infections")
	$oLang.Add("Hosts_TT","Downloads and installs an updated Hosts file to block malicious sites")
	$oLang.Add("MBAM_TT","Downloads and runs Malwarebytes Anti-Malware to remove infections")
	$oLang.Add("Search_TT","Uninstalls a lot of toolbars and stops any others from running")
	$oLang.Add("SecCenter_TT","Stops messages like 'Do you want to trust this program' and 'Your ___ is out of date'")

	; Performance
	$oLang.Add("Autorun","Prune Autoruns")
	$oLang.Add("Service","Reset Services to Default")
	$oLang.Add("Tweaked","Use Performance Settings")
	$oLang.Add("Tweaked_TT","WARNING: Do not use with a Domain!")
	$oLang.Add("Acro","Streamline Acrobat Reader")
	$oLang.Add("Rep","Optimize Resource Usage")
	$oLang.Add("Notify","Disable Extra System Notifications")
	$oLang.Add("SMorder","Clear Start Menu Order Cache")
	$oLang.Add("Autorun_TT","Removes unwanted autorun entries")
	$oLang.Add("Service_TT","Good for fixing unwanted effects of 'tinkering'")
	$oLang.Add("Acro_TT","Disables unused Acrobat plugins to make it MUCH faster")
	$oLang.Add("Rep_TT","Sets a bunch of performance related registry settings")
	$oLang.Add("Notify_TT","STOP BUGGING ME!!!")
	$oLang.Add("SMorder_TT","Makes them all show up in alphabetical order. Also effects favorites.")

	; Maintenance
	$oLang.Add("PageDefrag","Schedule System File Defragementation (next boot)")
	$oLang.Add("Defrag","Defragment the Hard Drive (Defraggler)")
	$oLang.Add("CheckDisk","Schedule Checkdisk to run next boot")
	$oLang.Add("Permissions","Reset File and Registry Permissions")
	$oLang.Add("Idle","Process Idle Tasks")
	$oLang.Add("PageDefrag_TT","Defragments core system files that windows can not usually defragment")
	$oLang.Add("Defrag_TT","Places pieces of files together.")
	$oLang.Add("CheckDisk_TT","Checks for hard drive errors on the next system reboot")
	$oLang.Add("Permissions_TT","Fixes some strange errors. Most notibly, run this if you can't install a service pack.")
	$oLang.Add("Idle_TT","Things windows does in the background (not documented by Microsoft). Helps performance.")

	; WinFixes
	$oLang.Add("Installer","Fix Windows Installer")
	$oLang.Add("SSLHTTPSCryptsvc","Fix SSL/HTTPS/Cryptsvc")
	$oLang.Add("Update","Fix Windows Update")
	$oLang.Add("FlushDNS","Flush DNS Cache")
	$oLang.Add("FixExplorer","Fix Windows Explorer")
	$oLang.Add("Time","Reset Windows Time")
	$oLang.Add("Network","Reset Network Interfaces")
	$oLang.Add("Shut","Fix Slow Logoff/Shutdown")
	$oLang.Add("Bin","Empty Recycle Bin")
	$oLang.Add("Installer_TT","Run if windows installer isn't working.")
	$oLang.Add("SSLHTTPSCryptsvc_TT","Fixes some internet related errors.")
	$oLang.Add("Update_TT","Make windows update work properly...")
	$oLang.Add("FlushDNS_TT","Usually only web developers need this, but it might help some other people.")
	$oLang.Add("FixExplorer_TT","Fixes many windows explorer related errors.")
	$oLang.Add("Time_TT","Fixes Windows time.")
	$oLang.Add("Network_TT","Fixes some strange networking issues.")
	$oLang.Add("Shut_TT","Kill apps faster and don't flush the pagefile.")
	$oLang.Add("Bin_TT","Because not unchecking this is easier than the 3 clicks it would normally take.")

	; WinFixes 2
	$oLang.Add("ExeAss","Fix Windows Associations")
	$oLang.Add("ZipAss","Restore .zip Association")
	$oLang.Add("TxtAss","Restore .txt Association")
	$oLang.Add("WorkGroup","Fix Workgroup Detection")
	$oLang.Add("USBDriv","Fix USB Drive Detection")
	$oLang.Add("Printer","Fix Printer Install Errors")
	$oLang.Add("TaskMan","Fix Task Manager")
	$oLang.Add("Links","Fix Broken MSOffice/Outlook Links")
	$oLang.Add("NTREGOPT","Optimize Registry")
	$oLang.Add("ExeAss_TT","Restores .exe .scr .msi .lnk .msc .reg and Windows folder execution Associations")
	$oLang.Add("ZipAss_TT","Restores control of zip files to the default windows zipped folder.")
	$oLang.Add("TxtAss_TT","Just because I had this issue a while back.")
	$oLang.Add("WorkGroup_TT","According to microsoft, this is a common error...")
	$oLang.Add("USBDriv_TT","There are many methods of breaking this. If this doesn't fix your problem and you figure out how, tell me.")
	$oLang.Add("Printer_TT","Won't install the printer for you, but it will make it possible if things error out on you."&@CRLF&"This single checkbox does what 3 'Windows FixIt' programs do.")
	$oLang.Add("TaskMan_TT","If it was somehow disabled (either by an admin or a virus) this re-enables it.")
	$oLang.Add("Links_TT","Not desktop shortcuts/links. For that you need 'Fix Windows Associations'")
	$oLang.Add("NTREGOPT_TT","Rebuilds the registry hives and replaces them next boot.")

	; Time
	$oLang.Add("ET","Estimated Time")
	$oLang.Add("ETsec","Second")
	$oLang.Add("ETmin","Minute")
	$oLang.Add("ETsecs","Seconds")
	$oLang.Add("ETmins","Minutes")

	; Scn
	$oLang.Add("ScnAntiVirus","Anti-Virus")
	$oLang.Add("ScnFirewall","Firewall")
	$oLang.Add("ScnUpdates","Updates")
	$oLang.Add("ScnIS","Internet Settings")
	$oLang.Add("ScnUAC","User Account Control")
	$oLang.Add("ScnSecNot","Security Notifications...")
	$oLang.Add("ScnDefend","Defender")
EndFunc
Func InitdeLang()
	$oLang.Add("ProgName","Automatic System Cleaner v2.3")
	$oLang.Add("DLDelCopy","Lschen Zurck \u0026quot;Kopieren von:")
	$oLang.Add("DLerr","Fehler beim Herunterladen von")
	$oLang.Add("DLofile","Zum Download fehlgeschlagen, weil die Ausgabe-Datei konnte nicht zugegriffen werden.")
	$oLang.Add("DLidown","Initializing Download")
	$oLang.Add("DLadown","Abort Download")
	$oLang.Add("DLaconfirm","Sind Sie sicher, dass Sie den Download abbrechen")
	$oLang.Add("DLaborted","Vom Benutzer abgebrochen")
	$oLang.Add("DLactive","Herunterladen")
	$oLang.Add("RegDLL","Registrieren")
	$oLang.Add("SvcPause","Anhalten")
	$oLang.Add("SvcPauseF","Anhalten Failed")
	$oLang.Add("SvcResume","Fortsetzen")
	$oLang.Add("SvcResumeF","Failed to Resume")
	$oLang.Add("SvcSm","Gendert Start Mode von")
	$oLang.Add("SvcSmF","Fehler beim ndern der Start Mode")
	$oLang.Add("to","zu")
	$oLang.Add("SvcStart","Started")
	$oLang.Add("SvcStartF","Failed to Start")
	$oLang.Add("SvcStop","Gestoppt")
	$oLang.Add("SvcStopF","Failed to Stop")
	$oLang.Add("ActBegin","Action Start")
	$oLang.Add("ActEnd","Aktion End")
	$oLang.Add("LangFail","Fehler, konnte nicht geladen Sprache Objekts:")
	$oLang.Add("HELPTIP","Klicken Sie hier, um die Online-Dokumentation fr diese Funktion")
	$oLang.Add("SelOpt","Bitte whlen Sie die Aktionen, die Sie gerne ausfhren.")
	$oLang.Add("SystemRestore","Erstellen Sie einen Wiederherstellungspunkt")
	$oLang.Add("SystemRestore_TT","So geht, falls etwas falsch ...")
	$oLang.Add("ERUNT","Sichern Sie die Registry")
	$oLang.Add("ERUNT_TT","So geht, falls etwas falsch ...")
	$oLang.Add("Reboot","Starten Sie nach Fertigstellung")
	$oLang.Add("Reboot_TT","Einige Optionen erforderlich sein, um wirksam")
	$oLang.Add("Force","Force File Update")
	$oLang.Add("Force_TT","Forces Schritte, um ihre Dateien zu aktualisieren, wenn sie ausgefhrt")
	$oLang.Add("HelpStart","ffnen Sie die Hilfe, wenn Programm startet")
	$oLang.Add("HelpStart_TT","ffnet die Webseite helfen, wenn das Programm geffnet ist")
	$oLang.Add("UpdateFiles","Update-Dateien")
	$oLang.Add("DeleteFiles","Dateien lschen")
	$oLang.Add("UpdateFilesTT","Updates alle Dateien von diesem programDesigned dass vor der Ausfhrung auf einem Computer ohne Internet heruntergeladen werden")
	$oLang.Add("DeleteFilesTT","Lscht alle von diesem Programm heruntergeladenen Dateien")
	$oLang.Add("HlpDoc","Hilfe Dokumentation")
	$oLang.Add("UncAll","Alle deaktivieren")
	$oLang.Add("Execute","Execute")
	$oLang.Add("CClean","CCleaner Scan")
	$oLang.Add("RegSeeker","RegSeeker Scan")
	$oLang.Add("RSquick_TT","Fhren Sie nur 1 Scan interation.")
	$oLang.Add("RSquick","Quick Scan")
	$oLang.Add("VSR","Vipre Rescue Scan")
	$oLang.Add("VRquick","Quick Scan")
	$oLang.Add("VRquick_TT","Fhren Sie eine weniger grndliche, aber scannen schneller.")
	$oLang.Add("Hosts","Update Hosts-Datei")
	$oLang.Add("MBAM","Malwarebytes Scan")
	$oLang.Add("MBAMquick","Quick Scan")
	$oLang.Add("MBAMquick_TT","Fhren Sie eine weniger grndliche, aber scannen schneller.")
	$oLang.Add("Search","Toolbar Removal")
	$oLang.Add("SecCenter","Disable Security Benachrichtigungen")
	$oLang.Add("CClean_TT","Downloads und luft CCleaner, um Speicherplatz freizugeben")
	$oLang.Add("RegSeeker_TT","Downloads und luft RegSeeker zu beheben Fehler in der Registrierung")
	$oLang.Add("VSR_TT","Downloads und luft Vipre Rescue XP Infektionen")
	$oLang.Add("Hosts_TT","Downloads und installiert eine aktualisierte Hosts-Datei auf bsartige Websites blockieren")
	$oLang.Add("MBAM_TT","Downloads und luft Malwarebytes Anti-Malware-Infektionen zu entfernen")
	$oLang.Add("Search_TT","Deinstalliert eine Menge von Symbolleisten und stoppt alle anderen die Ausfhrung von")
	$oLang.Add("SecCenter_TT","Stoppt die Meldungen wie \u0026quot;Wollen Sie dieses Programm, um das Vertrauen \u0026#39;und\u0026#39; Ihre ___ ist veraltet\u0026quot;")
	$oLang.Add("Autorun","Prune Autoruns")
	$oLang.Add("Service","Reset to Default Dienstleistungen")
	$oLang.Add("Tweaked","Verwenden Sie Performance Settings")
	$oLang.Add("Tweaked_TT","WARNUNG: Benutzen Sie nicht mit einer Domain!")
	$oLang.Add("Acro","Optimieren Sie den Acrobat Reader")
	$oLang.Add("Rep","Optimize Ressourcennutzung")
	$oLang.Add("Notify","Deaktivieren Extra System Benachrichtigungen")
	$oLang.Add("SMorder","Frei Startmen Auftrag Cache")
	$oLang.Add("Autorun_TT","Entfernt unerwnschte Autostart-Eintrge")
	$oLang.Add("Service_TT","Gut fr die Festsetzung unerwnschte Wirkungen von \u0026quot;Basteln\u0026quot;")
	$oLang.Add("Acro_TT","Deaktiviert ungenutzte Acrobat-Plugins, um sie viel schneller")
	$oLang.Add("Rep_TT","Legt eine Reihe von Performance-Registrierungseinstellungen")
	$oLang.Add("Notify_TT","Lauschangriff STOP ME!")
	$oLang.Add("SMorder_TT","Macht sie alle zeigen sich in alphabetischer Reihenfolge. Auch Auswirkungen Favoriten.")
	$oLang.Add("PageDefrag","Schedule System File Defragementation (nchste boot)")
	$oLang.Add("Defrag","Defragmentieren der Festplatte (Defraggler)")
	$oLang.Add("CheckDisk","Schedule Checkdisk ausgefhrt nchsten Systemstart")
	$oLang.Add("Permissions","Setzen Sie die Datei-und Registry-Berechtigungen")
	$oLang.Add("Idle","Idle Process Aufgaben")
	$oLang.Add("PageDefrag_TT","Defragmentiert Core-System-Dateien, die Fenster in der Regel nicht defragmentiert werden kann")
	$oLang.Add("Defrag_TT","Setzt alle Teile von Dateien mit einander ...")
	$oLang.Add("CheckDisk_TT","Checks fr Festplatte Fehler auf dem nchsten Neustart des Systems")
	$oLang.Add("Permissions_TT","Behebt einige seltsame Fehler. Die meisten notibly, fhren Sie diese Option, wenn Sie nicht ein Service Pack installieren.")
	$oLang.Add("Idle_TT","Dinge, die Windows nicht im Hintergrund (von Microsoft nicht dokumentiert). Hilft Leistung.")
	$oLang.Add("Installer","Fix Windows Installer")
	$oLang.Add("SSLHTTPSCryptsvc","Fix SSL / HTTPS / CryptSvc")
	$oLang.Add("Update","Fix Windows Update")
	$oLang.Add("FlushDNS","Flush DNS-Cache")
	$oLang.Add("FixExplorer","Fix Windows Explorer")
	$oLang.Add("Time","Reset Windows Time")
	$oLang.Add("Network","Reset Netzwerk-Schnittstellen")
	$oLang.Add("Shut","Fix Slow logoff-/shutdownsystem")
	$oLang.Add("Bin","Papierkorb leeren")
	$oLang.Add("Installer_TT","Fhren Sie, wenn Windows Installer nicht funktioniert.")
	$oLang.Add("SSLHTTPSCryptsvc_TT","Behebt einige Internetnutzung verbundene Fehler.")
	$oLang.Add("Update_TT","Stellen Sie Windows Update funktionieren ...")
	$oLang.Add("FlushDNS_TT","Normalerweise werden nur Web-Entwickler brauchen dies, kann aber einen anderen Menschen zu helfen.")
	$oLang.Add("FixExplorer_TT","Windows Explorer behebt viele Fehler in Zusammenhang stehen.")
	$oLang.Add("Time_TT","Fixes Windows Zeit.")
	$oLang.Add("Network_TT","Behebt einige seltsame Netzwerkprobleme.")
	$oLang.Add("Shut_TT","Kill-Anwendungen schneller und Splen nicht die Auslagerungsdatei.")
	$oLang.Add("Bin_TT","Da nicht deaktivieren das ist leichter als die 3 Klicks es normalerweise dauern wrde.")
	$oLang.Add("ExeAss","Fix Windows Verbnde")
	$oLang.Add("ZipAss","\u0026quot;Wiederherstellen\u0026quot;. Zip Association")
	$oLang.Add("TxtAss","\u0026quot;Wiederherstellen\u0026quot;. Txt Association")
	$oLang.Add("WorkGroup","Fix Arbeitsgruppe Detection")
	$oLang.Add("USBDriv","Fix USB Drive Detection")
	$oLang.Add("Printer","Fix Drucker installieren Fehler")
	$oLang.Add("TaskMan","Fix Task Manager")
	$oLang.Add("Links","Fix Broken MSOffice / Outlook-Links")
	$oLang.Add("NTREGOPT","Optimize Registry")
	$oLang.Add("ExeAss_TT","Stellt. Exe. Scr. Msi. Lnk. Msc. Reg-und Windows-Ordner Ausfhrung Verbnde")
	$oLang.Add("ZipAss_TT","Stellt Kontrolle von Zip-Dateien auf die Standard-Windows-ZIP-Ordner.")
	$oLang.Add("TxtAss_TT","Nur weil ich hatte dieses Problem eine Weile zurck.")
	$oLang.Add("WorkGroup_TT","Laut Microsoft ist dies ein hufiger Fehler ...")
	$oLang.Add("USBDriv_TT","Es gibt viele Methoden, diese zu brechen. Falls dies nicht Ihr Problem zu beheben, und Sie herausfinden, wie, sagen Sie mir.")
	$oLang.Add("Printer_TT","Will nicht installieren Sie den Drucker fr Sie, aber es wird es mglich sein, wenn die Dinge sich auf Fehler sind mhelos einzusetzende, einzelnes Kontrollkstchen tut, was 3 \u0026#39;Windows FixIt \u0026quot;-Programme.")
	$oLang.Add("TaskMan_TT","Wenn es denn irgendwie deaktiviert (entweder durch einen Administrator oder ein Virus) diese wieder aktiviert es.")
	$oLang.Add("Links_TT","Nicht Desktop-Verknpfungen / Links. Dafr bentigen Sie \u0026quot;Fix Windows Verbnde")
	$oLang.Add("NTREGOPT_TT","Erneuert die Registrierungsstrukturen und ersetzt sie nchsten Systemstart.")
	$oLang.Add("ET","Geschtzte Zeit")
	$oLang.Add("ETsec","Seccond")
	$oLang.Add("ETmin","Minute")
	$oLang.Add("ETsecs","Secconds")
	$oLang.Add("ETmins","Protokoll")
	$oLang.Add("ScnAntiVirus","Anti-Virus")
	$oLang.Add("ScnFirewall","Firewall")
	$oLang.Add("ScnUpdates","Updates")
	$oLang.Add("ScnIS","Internet Settings")
	$oLang.Add("ScnUAC","User Account Control")
	$oLang.Add("ScnSecNot","Security Benachrichtigungen ...")
	$oLang.Add("ScnDefend","Verteidiger")
EndFunc
Func InitesLang()
	$oLang.Add("ProgName","Automatic System Cleaner v2.3")
	$oLang.Add("DLDelCopy","Eliminar copia anterior de:")
	$oLang.Add("DLerr","Error en la descarga")
	$oLang.Add("DLofile","No se pudo descargar porque el archivo de salida no se pudo tener acceso.")
	$oLang.Add("DLidown","Inicializacin de Descarga")
	$oLang.Add("DLadown","Cancelar Descarga")
	$oLang.Add("DLaconfirm","Ests seguro de que desea cancelar la descarga de la")
	$oLang.Add("DLaborted","Proceso abortado por el usuario")
	$oLang.Add("DLactive","Descargar")
	$oLang.Add("RegDLL","Registrar")
	$oLang.Add("SvcPause","Pausa")
	$oLang.Add("SvcPauseF","No se ha podido Pausa")
	$oLang.Add("SvcResume","Reanudacin")
	$oLang.Add("SvcResumeF","No pudo reanudar")
	$oLang.Add("SvcSm","Cambiado el modo de inicio de")
	$oLang.Add("SvcSmF","No pudo cambiar el modo de inicio de")
	$oLang.Add("to","para")
	$oLang.Add("SvcStart","Iniciado")
	$oLang.Add("SvcStartF","Error al iniciar")
	$oLang.Add("SvcStop","Detenido")
	$oLang.Add("SvcStopF","No pudo detener")
	$oLang.Add("ActBegin","Comienza la accin")
	$oLang.Add("ActEnd","Accin Fin")
	$oLang.Add("LangFail","Error, no se puede cargar el objeto idioma:")
	$oLang.Add("HELPTIP","Haga clic aqu para ir a la documentacin en lnea de esta funcin")
	$oLang.Add("SelOpt","Seleccione las acciones que desea ejecutar.")
	$oLang.Add("SystemRestore","Crear un punto de restauracin")
	$oLang.Add("SystemRestore_TT","Slo en caso de que algo va mal ...")
	$oLang.Add("ERUNT","Copia de seguridad del Registro de")
	$oLang.Add("ERUNT_TT","Slo en caso de que algo va mal ...")
	$oLang.Add("Reboot","Reinicie cuando se complete")
	$oLang.Add("Reboot_TT","Algunas opciones pueden requerir que esto tenga efecto")
	$oLang.Add("Force","Fuerza de archivo de actualizacin")
	$oLang.Add("Force_TT","Fuerzas Pasos para actualizar sus archivos cuando se ejecutan")
	$oLang.Add("HelpStart","Abrir la Ayuda Cuando inicia el programa de")
	$oLang.Add("HelpStart_TT","Abre la ayuda en la pgina web cuando se abre el programa de")
	$oLang.Add("UpdateFiles","Actualizacin de los archivos")
	$oLang.Add("DeleteFiles","Eliminar archivos")
	$oLang.Add("UpdateFilesTT","Actualizaciones de todos los archivos descargados por este programDesigned para ser utilizado antes de correr en un equipo sin internet")
	$oLang.Add("DeleteFilesTT","Borra todos los archivos descargados por este programa")
	$oLang.Add("HlpDoc","Ayuda Documentacin")
	$oLang.Add("UncAll","Desmarcar todo")
	$oLang.Add("Execute","Ejecutar")
	$oLang.Add("CClean","CCleaner Scan")
	$oLang.Add("RegSeeker","RegSeeker Scan")
	$oLang.Add("RSquick_TT","Ejecutar slo 1 de escaneo interation.")
	$oLang.Add("RSquick","Quick Scan")
	$oLang.Add("VSR","Rescate VIPRE Scan")
	$oLang.Add("VRquick","Quick Scan")
	$oLang.Add("VRquick_TT","Ejecutar un thourough menos, pero ms rpido escaneo.")
	$oLang.Add("Hosts","Actualizacin del archivo hosts")
	$oLang.Add("MBAM","Malwarebytes Scan")
	$oLang.Add("MBAMquick","Quick Scan")
	$oLang.Add("MBAMquick_TT","Ejecutar un thourough menos, pero ms rpido escaneo.")
	$oLang.Add("Search","Barra de herramientas de eliminacin")
	$oLang.Add("SecCenter","Deshabilitar Notificaciones de Seguridad")
	$oLang.Add("CClean_TT","Descarga y ejecuta CCleaner de espacio libre en disco")
	$oLang.Add("RegSeeker_TT","Descarga y ejecuta RegSeeker para arreglar errores del registro")
	$oLang.Add("VSR_TT","Descarga y ejecuta rescate VIPRE para eliminar las infecciones")
	$oLang.Add("Hosts_TT","Descarga e instala un archivo actualizado de los Ejrcitos para bloquear los sitios maliciosos")
	$oLang.Add("MBAM_TT","Descarga y ejecuta Malwarebytes Anti-Malware para remover las infecciones")
	$oLang.Add("Search_TT","Desinstala un montn de barras de herramientas y detiene cualquier ejecucin de otros")
	$oLang.Add("SecCenter_TT","Mensajes deja como \u0026quot;Quieres confiar en este programa\u0026quot; y \u0026quot;Tu ___ est fuera de fecha\u0026quot;")
	$oLang.Add("Autorun","Autoruns Prune")
	$oLang.Add("Service","Servicios Restablecer valores predeterminados")
	$oLang.Add("Tweaked","Utilice Configuracin de rendimiento")
	$oLang.Add("Tweaked_TT","ADVERTENCIA: No usar con un dominio!")
	$oLang.Add("Acro","Streamline Acrobat Reader")
	$oLang.Add("Rep","Optimize Uso de recursos")
	$oLang.Add("Notify","Deshabilitar Extra Sistema de Notificaciones")
	$oLang.Add("SMorder","Clear Cache Orden del men Inicio")
	$oLang.Add("Autorun_TT","Elimina entradas de Auto Run no deseados")
	$oLang.Add("Service_TT","Bueno para la fijacin de efectos no deseados de \u0026quot;retoques\u0026quot;")
	$oLang.Add("Acro_TT","Desactiva los plugins sin utilizar Acrobat para hacer mucho ms rpido")
	$oLang.Add("Rep_TT","Establece un montn de rendimiento relacionados con la configuracin del Registro")
	$oLang.Add("Notify_TT","Stop me molesta!")
	$oLang.Add("SMorder_TT","Las hace a todas aparecen en orden alfabtico. Tambin los efectos favoritos.")
	$oLang.Add("PageDefrag","Calendario de archivos de sistema Defragementation (siguiente arranque)")
	$oLang.Add("Defrag","Desfragmentar el disco duro (Defraggler)")
	$oLang.Add("CheckDisk","Calendario Checkdisk para ejecutar el siguiente arranque")
	$oLang.Add("Permissions","Restaurar archivos y el registro de permisos")
	$oLang.Add("Idle","Tareas de proceso inactivo")
	$oLang.Add("PageDefrag_TT","Desfragmenta los archivos de sistema esenciales que Windows no puede desfragmentar general")
	$oLang.Add("Defrag_TT","Pone todas las piezas de los archivos con simpatia ...")
	$oLang.Add("CheckDisk_TT","Los controles de los errores del disco duro en el prximo reinicio del sistema")
	$oLang.Add("Permissions_TT","Corrige algunos errores extraos. La mayora de notibly, ejecute esta opcin si no se puede instalar un Service Pack.")
	$oLang.Add("Idle_TT","Windows hace las cosas en el fondo (no documentado por Microsoft). Ayudas para el rendimiento.")
	$oLang.Add("Installer","Fix Windows Installer")
	$oLang.Add("SSLHTTPSCryptsvc","Fix SSL / HTTPS / cryptsvc")
	$oLang.Add("Update","Fix Windows Update")
	$oLang.Add("FlushDNS","Flush DNS Cache")
	$oLang.Add("FixExplorer","Fijar el Explorador de Windows")
	$oLang.Add("Time","Perd mi tiempo de Windows")
	$oLang.Add("Network","Perd mi Interfaces de red")
	$oLang.Add("Shut","Fix Slow Desconectar / apagado")
	$oLang.Add("Bin","Vaciar Papelera de reciclaje")
	$oLang.Add("Installer_TT","Ejecutar si Windows Installer no est funcionando.")
	$oLang.Add("SSLHTTPSCryptsvc_TT","Corrige algunos errores relacionados con Internet.")
	$oLang.Add("Update_TT","Actualizacin de Windows hacen funcionar correctamente ...")
	$oLang.Add("FlushDNS_TT","Normalmente, slo los desarrolladores web necesitan esto, pero podra ayudar a otras personas.")
	$oLang.Add("FixExplorer_TT","Arreglos relacionados con el Explorador de Windows muchos errores.")
	$oLang.Add("Time_TT","Corrige tiempo de Windows.")
	$oLang.Add("Network_TT","Corrige algunos problemas de red extrao.")
	$oLang.Add("Shut_TT","Kill aplicaciones ms rpido y no vaciar el archivo de paginacin.")
	$oLang.Add("Bin_TT","Debido a que no desmarcar esta es ms fcil que el 3 clics que normalmente tomara.")
	$oLang.Add("ExeAss","Fix Windows Asociaciones")
	$oLang.Add("ZipAss","Restaurar. Zip Asociacin")
	$oLang.Add("TxtAss","Restaurar. Txt Asociacin")
	$oLang.Add("WorkGroup","Fix grupo de trabajo de deteccin")
	$oLang.Add("USBDriv","Fix USB Drive de deteccin")
	$oLang.Add("Printer","Fix Instalar impresora errores")
	$oLang.Add("TaskMan","Fix Task Manager")
	$oLang.Add("Links","Fix Broken MSOffice / Outlook Enlaces")
	$oLang.Add("NTREGOPT","Optimize Registro")
	$oLang.Add("ExeAss_TT","Restaura. Exe. Scr. Msi. Lnk. Msc. Reg y Asociaciones de la ejecucin de carpeta de Windows")
	$oLang.Add("ZipAss_TT","Restablece el control de los archivos zip a la carpeta predeterminada de Windows comprimido.")
	$oLang.Add("TxtAss_TT","Slo porque tena este problema hace un tiempo.")
	$oLang.Add("WorkGroup_TT","Segn Microsoft, este es un error comn ...")
	$oLang.Add("USBDriv_TT","Hay muchos mtodos de romper esto. Si esto no soluciona el problema y averiguar cmo, dmelo.")
	$oLang.Add("Printer_TT","No instalar la impresora para usted, pero ser posible si las cosas error sobre you.This casilla solo hace lo que 3 \u0026#39;programas de Windows FixIt \u0026quot;hacer.")
	$oLang.Add("TaskMan_TT","Si fue por alguna discapacidad (ya sea por un administrador o un virus) esta re-habilita.")
	$oLang.Add("Links_TT","No accesos directos del escritorio y enlaces. Para que usted necesita \u0026#39;de Windows del arreglo de las asociaciones")
	$oLang.Add("NTREGOPT_TT","Vuelve a generar el registro de las colmenas y las sustituye por el siguiente arranque.")
	$oLang.Add("ET","Tiempo estimado")
	$oLang.Add("ETsec","Seccond")
	$oLang.Add("ETmin","Minuto")
	$oLang.Add("ETsecs","Secconds")
	$oLang.Add("ETmins","Acta")
	$oLang.Add("ScnAntiVirus","Anti-Virus")
	$oLang.Add("ScnFirewall","Firewall")
	$oLang.Add("ScnUpdates","Actualizaciones")
	$oLang.Add("ScnIS","Configuracin de Internet")
	$oLang.Add("ScnUAC","User Account Control")
	$oLang.Add("ScnSecNot","Notificaciones de Seguridad ...")
	$oLang.Add("ScnDefend","Defensa")
EndFunc
Func InitgaLang()
	$oLang.Add("ProgName","Uathoibroch Cras Glantir v2.3")
	$oLang.Add("DLDelCopy","Scriosadh Cip Previous :")
	$oLang.Add("DLerr","Earrid oslucht")
	$oLang.Add("DLofile","Norbh fhidir a osldil mar nach bhfadfadh an comhad aschuir a rochtain.")
	$oLang.Add("DLidown","Initializing osluchtaigh")
	$oLang.Add("DLadown","Tobscoir osluchtaigh")
	$oLang.Add("DLaconfirm","An bhfuil t cinnte gur mian leat a chur ar ceal a osldil ")
	$oLang.Add("DLaborted","Priseas Tobscortha ag sideoir")
	$oLang.Add("DLactive","oslucht")
	$oLang.Add("RegDLL","Clr")
	$oLang.Add("SvcPause","Pausing")
	$oLang.Add("SvcPauseF","Theip ar Sos")
	$oLang.Add("SvcResume","Filleadh")
	$oLang.Add("SvcResumeF","Theip ar Lean")
	$oLang.Add("SvcSm","Athraodh Tosaigh Md de")
	$oLang.Add("SvcSmF","Theip ar Athr Md Ts na")
	$oLang.Add("to","go")
	$oLang.Add("SvcStart","Started")
	$oLang.Add("SvcStartF","Theip ar Tosaigh")
	$oLang.Add("SvcStop","Stoptha")
	$oLang.Add("SvcStopF","Theip ar Stop")
	$oLang.Add("ActBegin","Gnomh Tosaigh")
	$oLang.Add("ActEnd","Gnomh Deireadh")
	$oLang.Add("LangFail","Earrid nach bhfadfa, lucht rad teanga:")
	$oLang.Add("HELPTIP","Cliceil anseo chun dul go dt an doicimad ar lne chun an ghn seo")
	$oLang.Add("SelOpt","Le do thoil Roghnaigh na gnomhaochta a ba mhaith leat a rith.")
	$oLang.Add("SystemRestore","Cruthaigh Pointe Athchirigh")
	$oLang.Add("SystemRestore_TT","Just Tann i gcs rud igin mcheart ...")
	$oLang.Add("ERUNT","Cltaca an Chlrlann")
	$oLang.Add("ERUNT_TT","Just Tann i gcs rud igin mcheart ...")
	$oLang.Add("Reboot","Atosaigh nuair a chrochnfar")
	$oLang.Add("Reboot_TT","Roinnt roghanna a cheangal seo a chur i bhfeidhm")
	$oLang.Add("Force","Frsa Comhad Nuashonraigh")
	$oLang.Add("Force_TT","glaigh na Cimeanna a thabhairt suas chun dta a comhaid nuair a ritheann siad")
	$oLang.Add("HelpStart","Oscail Cabhair nuair a thosaonn an Clr")
	$oLang.Add("HelpStart_TT","Oscail an cnamh leathanach grasin nuair a bhonn an clr oscailte")
	$oLang.Add("UpdateFiles","Nuashonraigh Comhaid")
	$oLang.Add("DeleteFiles","Scrios Comhaid")
	$oLang.Add("UpdateFilesTT","Nuashonra comhaid a osldil go lir ag an programDesigned a sid roimh rith ar romhaire le aon idirlon")
	$oLang.Add("DeleteFilesTT","Scrios na comhaid a osldil ag an clr")
	$oLang.Add("HlpDoc","Cabhair Doicimad")
	$oLang.Add("UncAll","Gach Dthiceil")
	$oLang.Add("Execute","Rith")
	$oLang.Add("CClean","CCleaner Scan")
	$oLang.Add("RegSeeker","RegSeeker Scan")
	$oLang.Add("RSquick_TT","Rith ach 1 scanadh interation.")
	$oLang.Add("RSquick","Quick Scan")
	$oLang.Add("VSR","Tarrthla Scan Vipre")
	$oLang.Add("VRquick","Quick Scan")
	$oLang.Add("VRquick_TT","Rith le thourough nos l, ach nos tapa scanadh.")
	$oLang.Add("Hosts","stromhair Nuashonraigh Comhad")
	$oLang.Add("MBAM","Malwarebytes Scan")
	$oLang.Add("MBAMquick","Quick Scan")
	$oLang.Add("MBAMquick_TT","Rith le thourough nos l, ach nos tapa scanadh.")
	$oLang.Add("Search","Uirlis Removal")
	$oLang.Add("SecCenter","Dchumasaigh Fgra Slndil")
	$oLang.Add("CClean_TT","osldlacha Ritheann agus CCleaner chun sps diosca saor in aisce")
	$oLang.Add("RegSeeker_TT","osldlacha Ritheann agus RegSeeker a shocr earrid registry")
	$oLang.Add("VSR_TT","osldlacha Ritheann agus Tarrthil Vipre ionfhabhtuithe a bhaint")
	$oLang.Add("Hosts_TT","osldil comhad Insealbhaonn agus stromhair thabhairt suas chun dta chun bealach sumh mailseach")
	$oLang.Add("MBAM_TT","osldlacha Ritheann agus Malwarebytes Anti-Malware ionfhabhtuithe a bhaint")
	$oLang.Add("Search_TT","Uninstalls a ln de Barra Uirlis stadanna agus aon daoine eile ar rechtil")
	$oLang.Add("SecCenter_TT","N teachtaireachta Stad cosil le \u0026#39;mian leat chun muinn an clr\u0026#39; agus \u0026#39;Do T ___ as dta\u0026#39;")
	$oLang.Add("Autorun","Autoruns Prune")
	$oLang.Add("Service","Seirbhs Athshocraigh go ramhshocraithe")
	$oLang.Add("Tweaked","sid Socruithe Feidhmochta")
	$oLang.Add("Tweaked_TT","N RABHADH: a sid le Fearann!")
	$oLang.Add("Acro","Sruthlni Acrobat Reader")
	$oLang.Add("Rep","Optimize sid Acmhainn")
	$oLang.Add("Notify","Dchumasaigh breise Cras Fgra")
	$oLang.Add("SMorder","Glan Tosaigh Menu Ord Taisce")
	$oLang.Add("Autorun_TT","Iontrlacha Bain autorun nach dteastaonn")
	$oLang.Add("Service_TT","Dea-shocr le haghaidh ifeachta nach raibh an \u0026#39;tinkering\u0026#39;")
	$oLang.Add("Acro_TT","Dchumasaigh Breisein Acrobat neamhsidte le go mbeadh s i bhfad nos tapla")
	$oLang.Add("Rep_TT","Leagtar socruithe a bunch feidhmochta chlr a bhaineann le")
	$oLang.Add("Notify_TT","STOP BUGGING ME!!!")
	$oLang.Add("SMorder_TT","Dan iad a thaispeint ar fad ar bun in ord aibtre. Chomh maith leis sin Favorites ifeachta.")
	$oLang.Add("PageDefrag","Sceideal Cras Comhad Defragementation (tosaithe seo chugainn)")
	$oLang.Add("Defrag","Defragment an Tiomntn Crua (Defraggler)")
	$oLang.Add("CheckDisk","Sceideal Checkdisk a rith tosaithe eile")
	$oLang.Add("Permissions","Ceadanna Athshocraigh Comhad agus Clrlann")
	$oLang.Add("Idle","Craim Priseas Domhaoin")
	$oLang.Add("PageDefrag_TT","Comhaid Defragments cras lrnach gur fidir le fuinneoga ghnth n defragment")
	$oLang.Add("Defrag_TT","Cuireann na posa de chomhaid le eachother ...")
	$oLang.Add("CheckDisk_TT","Seicelacha chun earrid a thiomint crua ar an gcras eile Atosaigh")
	$oLang.Add("Permissions_TT","Ceartchin roinnt botin aisteach. Notibly an chuid is m,  rechtil seo ms rud  nach fidir leat a shuiteil paciste seirbhse.")
	$oLang.Add("Idle_TT","Fuinneoga ruda nach sa chlra (doicimadaithe ag Microsoft). Cuidonn feidhmochta.")
	$oLang.Add("Installer","Deisigh Windows Suitela")
	$oLang.Add("SSLHTTPSCryptsvc","Deisigh SSL / HTTPS / Cryptsvc")
	$oLang.Add("Update","Deisigh Windows Update")
	$oLang.Add("FlushDNS","Flush DNS Cache")
	$oLang.Add("FixExplorer","Deisigh Windows Explorer")
	$oLang.Add("Time","Athshocraigh Am Windows")
	$oLang.Add("Network","Athshocraigh Comhadain Lonra")
	$oLang.Add("Shut","Deisigh Mall Logoff / Mchadh")
	$oLang.Add("Bin","Folamh Athchrsil Bruscair")
	$oLang.Add("Installer_TT","Rith ms rud  nach bhfuil fuinneoga suitela oibre.")
	$oLang.Add("SSLHTTPSCryptsvc_TT","Ceartchin roinnt botin a bhaineann leis an idirlon.")
	$oLang.Add("Update_TT","Fuinneoga nuashonr a dhanamh ag obair i gceart ...")
	$oLang.Add("FlushDNS_TT","De ghnth is g forbrir grasin seo amhin, ach d\u0026#39;fhadfadh s cabhr le roinnt daoine eile.")
	$oLang.Add("FixExplorer_TT","Fuinneoga Ceartchin a ln Explorer earrid a bhaineann leo.")
	$oLang.Add("Time_TT","Ceartchin Windows am.")
	$oLang.Add("Network_TT","Ceartchin roinnt ceisteanna lonr aisteach.")
	$oLang.Add("Shut_TT","Apps Cille agus nos tapla n an pagefile flush.")
	$oLang.Add("Bin_TT","T Toisc nach unchecking seo nos asca n an 3 cad a tharlaonn nuair a bheadh s de ghnth.")
	$oLang.Add("ExeAss","Deisigh Cumainn Windows")
	$oLang.Add("ZipAss","Cuir. Zip-Chumann")
	$oLang.Add("TxtAss","Cuir. Txt Cumann")
	$oLang.Add("WorkGroup","Deisigh Grpa Oibre Aimsi")
	$oLang.Add("USBDriv","Deisigh Drive USB Aimsi")
	$oLang.Add("Printer","Deisigh Leagan Suiteil Earrid")
	$oLang.Add("TaskMan","Deisigh Tasc Bainisteoir")
	$oLang.Add("Links","Deisigh Briste MSOffice / Outlook Naisc")
	$oLang.Add("NTREGOPT","Optimize Chlrlann")
	$oLang.Add("ExeAss_TT","Restores. Exe?. SCR. Msi. Lnk. MSc. Reg agus Cumainn Windows fhorghnomh fillten")
	$oLang.Add("ZipAss_TT","Restores rial na gcomhad zip chun na fuinneoga default zipped fillten.")
	$oLang.Add("TxtAss_TT","Dreach mar a bh agam leis an gceist seo ar fad ar ais.")
	$oLang.Add("WorkGroup_TT","Dar le Microsoft,  seo ar earrid coiteann ...")
	$oLang.Add("USBDriv_TT","T modhanna a ln de briseadh seo. Ms rud  nach seo a shocr d\u0026#39;fhadhb agus figir t amach conas, inis dom.")
	$oLang.Add("Printer_TT","An n a shuiteil printir le haghaidh t, ach danfaidh s  a dhanamh m fidir ruda earrid amach ar you.This ticbhosca aonair a dhanann card 3 \u0026#39;Windows FixIt\u0026#39; clir a dhanamh.")
	$oLang.Add("TaskMan_TT","M bh s ar bhealach faoi mhchumas (ceachtar ag admin n vreas) seo a ath-chumas.")
	$oLang.Add("Links_TT","Gan aicearra desktop / naisc. I gcs gur g t \u0026#39;Deisigh Cumainn Windows\u0026#39;")
	$oLang.Add("NTREGOPT_TT","Rebuilds hives an chlr agus in ionad iad a tosaithe amach romhainn.")
	$oLang.Add("ET","Am measta")
	$oLang.Add("ETsec","Seccond")
	$oLang.Add("ETmin","Nimad")
	$oLang.Add("ETsecs","Secconds")
	$oLang.Add("ETmins","Miontuairisc")
	$oLang.Add("ScnAntiVirus","Anti-Vreas")
	$oLang.Add("ScnFirewall","Balla ditein")
	$oLang.Add("ScnUpdates","Nuashonra")
	$oLang.Add("ScnIS","Idirlon Socruithe")
	$oLang.Add("ScnUAC","sideoir Cuntas Rial")
	$oLang.Add("ScnSecNot","Fgra Slndla ...")
	$oLang.Add("ScnDefend","Defender")
EndFunc
