;$VK = Virtual Key Code smile.gif
;the following script will help in _IsPressed($VK_L_MOUSE)
;Completely created by ludocus, got the codes from: http://delphi.about.com/od/objectpascalide/l/blvkc.htm
;Enjoy!
;updated to v2.0
Global Const $VK_L_MOUSE = '01'
Global Const $VK_R_MOUSE = '02'
Global Const $VK_CTRL_BREAK = '03'
Global Const $VK_M_MOUSE = '04'
Global Const $VK_BACK = '08'
Global Const $VK_TAB = '09'
Global Const $VK_CLEAR = '0C'
Global Const $VK_ENTER = '0D'
Global Const $VK_SHIFT = 10
Global Const $VK_CTRL = 11
Global Const $VK_ALT = 12
Global Const $VK_PAUSE = 13
Global Const $VK_CAPS = 14
Global Const $VK_ESC = '1B'
Global Const $VK_SPACE = 20
Global Const $VK_PAGE_UP = 21
Global Const $VK_PADE_DOWN = 22
Global Const $VK_END = 23
Global Const $VK_HOME = 24
Global Const $VK_LEFT = 25
Global Const $VK_UP = 26
Global Const $VK_RIGHT = 27
Global Const $VK_DOWN = 28
Global Const $VK_SELECT = 29
Global Const $VK_PRINT = '2A'
Global Const $VK_EXECUTE = '2B'
Global Const $VK_PRINT_SCR = '2C'
Global Const $VK_INS = '2D'
Global Const $VK_DEL = '2E'
Global Const $VK_HELP = '2F'
Global Const $VK_0 = 30
Global Const $VK_1 = 31
Global Const $VK_2 = 32
Global Const $VK_3 = 33
Global Const $VK_4 = 34
Global Const $VK_5 = 35
Global Const $VK_6 = 36
Global Const $VK_7 = 37
Global Const $VK_8 = 38
Global Const $VK_9 = 39
Global Const $VK_A = 41
Global Const $VK_B = 42
Global Const $VK_C = 43
Global Const $VK_D = 44
Global Const $VK_E = 45
Global Const $VK_F = 46
Global Const $VK_G = 47
Global Const $VK_H = 48
Global Const $VK_I = 49
Global Const $VK_J = '4A'
Global Const $VK_K = '4B'
Global Const $VK_L = '4C'
Global Const $VK_M = '4D'
Global Const $VK_N = '4E'
Global Const $VK_O = '4F'
Global Const $VK_P = 50
Global Const $VK_Q = 51
Global Const $VK_R = 52
Global Const $VK_S = 53
Global Const $VK_T = 54
Global Const $VK_U = 55
Global Const $VK_V = 56
Global Const $VK_W = 57
Global Const $VK_X = 58
Global Const $VK_Y = 59
Global Const $VK_Z = '5A'
Global Const $VK_L_WIN = '5B'
Global Const $VK_R_WIN = '5C'
Global Const $VK_APP = '5D'
Global Const $VK_NUMPAD0 = 60
Global Const $VK_NUMPAD1 = 61
Global Const $VK_NUMPAD2 = 62
Global Const $VK_NUMPAD3 = 63
Global Const $VK_NUMPAD4 = 64
Global Const $VK_NUMPAD5 = 65
Global Const $VK_NUMPAD6 = 66
Global Const $VK_NUMPAD7 = 67
Global Const $VK_NUMPAD8 = 68
Global Const $VK_NUMPAD9 = 69
Global Const $VK_MULTIPLY = '6A'
Global Const $VK_ADD = '6B'
Global Const $VK_SEPERATOR = '6C'
Global Const $VK_SUBSTRACT = '6D'
Global Const $VK_DECIMAL = '6E'
Global Const $VK_DIVIDE = '6F'
Global Const $VK_F1 = 70
Global Const $VK_F2 = 71
Global Const $VK_F3 = 72
Global Const $VK_F4 = 73
Global Const $VK_F5 = 74
Global Const $VK_F6 = 75
Global Const $VK_F7 = 76
Global Const $VK_F8 = 77
Global Const $VK_F9 = 78
Global Const $VK_F10 = 79
Global Const $VK_F11 = '7A'
Global Const $VK_F12 = '7B'
Global Const $VK_F13 = '7C'
Global Const $VK_F14 = '7D'
Global Const $VK_F15 = '7E'
Global Const $VK_F16 = '7F'
Global Const $VK_F17 = '80H'
Global Const $VK_F18 = '81H'
Global Const $VK_F19 = '82H'
Global Const $VK_F20 = '83H'
Global Const $VK_F21 = '84H'
Global Const $VK_F22 = '85H'
Global Const $VK_F23 = '86H'
Global Const $VK_F24 = '87H'
Global Const $VK_NUMLOCK = 90
Global Const $VK_SCROLL_LOCK = 91
Global Const $VK_L_SHIFT = 'A0'
Global Const $VK_R_SHIFT = 'A1'
Global Const $VK_L_CTRL = 'A2'
Global Const $VK_R_CTRL = 'A3'
Global Const $VK_L_MENU = 'A4'
Global Const $VK_R_MENU = 'A5'
Global Const $VK_PLAY = 'FA'
Global Const $VK_ZOOM = 'FB'
Global Const $VK_OFF = 'DF'
Global Const $VK_COMMA = 'BC'
Global Const $VK_POINT = 'BE'
Global Const $VK_PERIOD = 'BE'
Global Const $VK_PLUS = 'BB'
Global Const $VK_MINUS = 'BD'
;other:
Global Const $VK_COLON = 'BA' ;==> :;
Global Const $VK_SLASH = 'BF' ;==> /?
Global Const $VK_TILDE = 'C0' ;==> `~
Global Const $VK_OPEN_BRACKET = 'DB' ;==> [{
Global Const $VK_CLOSE_BRACKET = 'DD' ;==> ]}
Global Const $VK_BACK_SLASH = 'DC' ;==> \|
Global Const $VK_QUOTATION = 'DE' ;==> '"
