#include-once

Global Enum _
  $IA2_EVENT_ACTION_CHANGED = 0x101, _
  $IA2_EVENT_ACTIVE_DECENDENT_CHANGED, _
  $IA2_EVENT_ACTIVE_DESCENDANT_CHANGED = $IA2_EVENT_ACTIVE_DECENDENT_CHANGED, _
  $IA2_EVENT_DOCUMENT_ATTRIBUTE_CHANGED, _
  $IA2_EVENT_DOCUMENT_CONTENT_CHANGED, _
  $IA2_EVENT_DOCUMENT_LOAD_COMPLETE, _
  $IA2_EVENT_DOCUMENT_LOAD_STOPPED, _
  $IA2_EVENT_DOCUMENT_RELOAD, _
  $IA2_EVENT_HYPERLINK_END_INDEX_CHANGED, _
  $IA2_EVENT_HYPERLINK_NUMBER_OF_ANCHORS_CHANGED, _
  $IA2_EVENT_HYPERLINK_SELECTED_LINK_CHANGED, _
  $IA2_EVENT_HYPERTEXT_LINK_ACTIVATED, _
  $IA2_EVENT_HYPERTEXT_LINK_SELECTED, _
  $IA2_EVENT_HYPERLINK_START_INDEX_CHANGED, _
  $IA2_EVENT_HYPERTEXT_CHANGED, _
  $IA2_EVENT_HYPERTEXT_NLINKS_CHANGED, _
  $IA2_EVENT_OBJECT_ATTRIBUTE_CHANGED, _
  $IA2_EVENT_PAGE_CHANGED, _
  $IA2_EVENT_SECTION_CHANGED, _
  $IA2_EVENT_TABLE_CAPTION_CHANGED, _
  $IA2_EVENT_TABLE_COLUMN_DESCRIPTION_CHANGED, _
  $IA2_EVENT_TABLE_COLUMN_HEADER_CHANGED, _
  $IA2_EVENT_TABLE_MODEL_CHANGED, _
  $IA2_EVENT_TABLE_ROW_DESCRIPTION_CHANGED, _
  $IA2_EVENT_TABLE_ROW_HEADER_CHANGED, _
  $IA2_EVENT_TABLE_SUMMARY_CHANGED, _
  $IA2_EVENT_TEXT_ATTRIBUTE_CHANGED, _
  $IA2_EVENT_TEXT_CARET_MOVED, _
  $IA2_EVENT_TEXT_CHANGED, _
  $IA2_EVENT_TEXT_COLUMN_CHANGED, _
  $IA2_EVENT_TEXT_INSERTED, _
  $IA2_EVENT_TEXT_REMOVED, _
  $IA2_EVENT_TEXT_UPDATED, _
  $IA2_EVENT_TEXT_SELECTION_CHANGED, _
  $IA2_EVENT_VISIBLE_DATA_CHANGED
