Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
Run('7z.exe')
WinWait("7-Zip 4.65 Setup ","")
If Not WinActive("7-Zip 4.65 Setup ","") Then WinActivate("7-Zip 4.65 Setup ","")
WinWaitActive("7-Zip 4.65 Setup ","")
Send("{ALTDOWN}i{ALTUP}")
WinWaitActive("7-Zip 4.65 Setup ","Completing")
If Not WinActive("7-Zip 4.65 Setup ","Completing") Then WinActivate("7-Zip 4.65 Setup ","Completing")
Send("{ALTDOWN}f{ALTUP}")
ControlClick ("", "&Finish", "Button2")
