Run ("flsh.exe")
ProcessWaitClose("flsh.exe")
Run ("ff.exe")
ProcessWaitClose ("ff.exe")
Run ("seven.exe")
ProcessWaitClose ("seven.exe")
Run ("sunj.exe")
ProcessWaitClose ("sunj.exe")
Run ("adbrdr.exe")
ProcessWaitClose ("adbrdr.exe")
Run ("dvd.exe")
ProcessWaitClose ("dvd.exe")
ProcessWaitClose ("divx.exe")
Run ("av.exe")
ProcessWaitClose ("av.exe")
;Shutdown(2)
