Run("C:\Program Files\DataFlux\dfPower Tools\8.0\dbmswin8.exe")
WinWaitActive("Welcome to dfPower DBMS/Copy!")
Send("O")
Send("C C:\Users\eSpace\Desktop\Studies\Newlink\prg")
Send("{ENTER}")
Sleep(100)
Send("ae.prg")
Sleep(100)
Send("{ENTER}")
Sleep(100)
Send("{ALT}+F")
Sleep(100)
Send("RUN")
Sleep(10000)
WinWait("dfPower DBMS/Copy for Windows V8.0.0")
Send("{ALT}+F")
Sleep(100)
Send("CLOSE")
Sleep(100)
Send("NO")
Sleep(100)

WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0")
Send("{ALT}+F")
Sleep(100)
Send("Ope")
Sleep(100)
Send("cm.prg")
Sleep(100)
Send("{ENTER}")
Sleep(100)
Send("{ALT}+F")
Sleep(100)
Send("RUN")
Sleep(1000)
WinWait("dfPower DBMS/Copy for Windows V8.0.0")
Send("{ALT}+F")
Sleep(100)
Send("CLOSE")
Sleep(100)
Send("NO")
Sleep(100)

WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0")
Send("{ALT}+F")
Sleep(100)
Send("Op")
Sleep(100)
Send("dm.prg")
Sleep(100)
Send("{ENTER}")
Sleep(100)
Send("{ALT}+F")
Sleep(100)
Send("RUN")
Sleep(1000)
WinWait("dfPower DBMS/Copy for Windows V8.0.0")
Send("{ALT}+F")
Sleep(100)
Send("CLOSE")
Sleep(100)
Send("NO")
Sleep(100)
