Opt("MustDeclareVars", 1)
Global $aRadio[65] = [64],$Radio,$Gui,$Tab1, $Tab2, $Tab3

$Gui = GUICreate("     Robots", 212, 657, 759, 39, -1)
Local $go = GUICtrlCreateButton("OK", 15, 615, 75, 25, 0x0F00)
Local $tab = GUICtrlCreateTab(8, 8, 196, 640)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$Tab1 = GUICtrlCreateTabItem("Gen")
$Tab2 = GUICtrlCreateTabItem("Misc Imps")
$Tab3 = GUICtrlCreateTabItem("Fuel Misc Imps")
GUICtrlCreateTabItem("")

GUISwitch($Gui,$tab1)
$aRadio[01] = GUICtrlCreateRadio(" New James' Zap", 15, 40, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)	
$aRadio[02] = GUICtrlCreateRadio(" New Greg's Zap", 15, 60, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[03] = GUICtrlCreateRadio(" New Tony's Zap", 15, 80, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[04] = GUICtrlCreateRadio(" Change James' Zap", 15, 110, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[05] = GUICtrlCreateRadio(" Change Greg's Zap", 15, 130, 180, 20)	
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[06] = GUICtrlCreateRadio(" Change Tony's Zap", 15, 150, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[07] = GUICtrlCreateRadio(" Change James' Zap NC", 15, 180, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[08] = GUICtrlCreateRadio(" Change Greg's Zap NC", 15, 200, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[09] = GUICtrlCreateRadio(" Change Tony's Zap NC", 15, 220, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[10] = GUICtrlCreateRadio("Copy PN Excel to Proval", 15, 250, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[11] = GUICtrlCreateRadio("Copy PN Excel to Lotus", 15, 270, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[12] = GUICtrlCreateRadio("Paste to Ascend", 15, 290, 190, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[13] = GUICtrlCreateRadio("Copy PN FS to Proval", 15, 310, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[14] = GUICtrlCreateRadio("Copy PN to Geo Media", 15, 330, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[15] = GUICtrlCreateRadio("Lease Present Memo", 15, 360, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[16] = GUICtrlCreateRadio("Listing Present Memo", 15, 380, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[17] = GUICtrlCreateRadio("Add a Memo", 15, 400, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[18] = GUICtrlCreateRadio("Open Permit Screen", 15, 420, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[19] = GUICtrlCreateRadio("View Sales History", 15, 440, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[20] = GUICtrlCreateRadio("BLA Memo Acres", 15, 470, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[21] = GUICtrlCreateRadio("BLA Memo SF", 15, 490, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[22] = GUICtrlCreateRadio("Economic Unit Memo", 15, 510, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[23] = GUICtrlCreateRadio("New Parcel Settup", 15, 530, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[24] = GUICtrlCreateRadio("Land Size Memo", 15, 550, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[25] = GUICtrlCreateRadio("Seg Memo", 15, 570, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
	
GUISwitch($Gui,$tab2)

$aRadio[26] = GUICtrlCreateRadio(" Asphalt", 15, 40, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)	
$aRadio[27] = GUICtrlCreateRadio(" Flatwork", 15, 60, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[28] = GUICtrlCreateRadio(" Canopy Low", 15, 80, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[29] = GUICtrlCreateRadio(" Canopy Ave", 15, 100, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[30] = GUICtrlCreateRadio(" Canopy Good", 15, 120, 180, 20)	
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[31] = GUICtrlCreateRadio(" Canopy High", 15, 140, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[32] = GUICtrlCreateRadio(" Trash Enclosure", 15, 160, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[33] = GUICtrlCreateRadio(" Miscellaneous", 15, 180, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[34] = GUICtrlCreateRadio(" Add Misc Imp", 15, 200, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[35] = GUICtrlCreateRadio(" CLF 4' TR", 15, 230, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[36] = GUICtrlCreateRadio(" CLF 4' Slats", 15, 250, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[37] = GUICtrlCreateRadio(" CLF 6' TR", 15, 270, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[38] = GUICtrlCreateRadio(" CLF 6' Slats", 15, 290, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[39] = GUICtrlCreateRadio(" CLF 6' TR 3SBW", 15, 310, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[40] = GUICtrlCreateRadio(" Lights Single Lamp", 15, 340, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[41] = GUICtrlCreateRadio(" Lights Double Lamp", 15, 360, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[42] = GUICtrlCreateRadio(" Lights triple Lamp", 15, 380, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[43] = GUICtrlCreateRadio(" Lights Quad Lamp", 15, 400, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[44] = GUICtrlCreateRadio(" Loading Dock", 15, 430, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[45] = GUICtrlCreateRadio(" Loading Well", 15, 450, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[46] = GUICtrlCreateRadio(" Loading Well Walls", 15, 470, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[47] = GUICtrlCreateRadio(" CB or Masonry Walls", 15, 490, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[48] = GUICtrlCreateRadio(" Wrought Iron Fence", 15, 510, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[49] = GUICtrlCreateRadio(" Solid Board Fence", 15, 530, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[50] = GUICtrlCreateRadio(" Stacked Blk Wall", 15, 550, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[51] = GUICtrlCreateRadio(" Concrete Wall", 15, 570, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
	
GUISwitch($Gui,$tab3)
$aRadio[52] = GUICtrlCreateRadio(" Asphalt", 15, 40, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)	
$aRadio[53] = GUICtrlCreateRadio(" Flatwork", 15, 60, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[54] = GUICtrlCreateRadio(" Fuel Canopy", 15, 80, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[55] = GUICtrlCreateRadio(" Concrete Over Tanks", 15, 100, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[56] = GUICtrlCreateRadio(" Drive Slab", 15, 120, 180, 20)	
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[57] = GUICtrlCreateRadio(" Excavation", 15, 140, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[58] = GUICtrlCreateRadio(" Electrical", 15, 160, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[59] = GUICtrlCreateRadio(" UG Tanks", 15, 180, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[60] = GUICtrlCreateRadio(" Valves, Pumps & LMS", 15, 200, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[61] = GUICtrlCreateRadio(" Piping", 15, 220, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[62] = GUICtrlCreateRadio(" Trash Enclosure", 15, 240, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[63] = GUICtrlCreateRadio(" Lights Single Lamp", 15, 260, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$aRadio[64] = GUICtrlCreateRadio(" Lights Double Lamp", 15, 280, 180, 20)
	GUICtrlSetFont(-1, 10, 800, 2, "Arial")
	GUICtrlSetColor(-1, 0x800000)
	GUICtrlSetBkColor(-1, 0xC0DCC0)
$Radio = 0

GUISetState(@SW_SHOW)

While 1
   Local $msg = GUIGetMsg()
    Select
        Case $msg = -3
            Exit
			
        Case $go = $Radio
            For $i = 1 To 64
				Next
           		
			Func run_selected()
					If BitAND(GUICtrlRead($aRadio[01]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\NewZapTH.exe")
					If BitAND(GUICtrlRead($aRadio[02]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\NewZapGH.exe")
					If BitAND(GUICtrlRead($aRadio[03]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\NewZapB$$.exe")
					If BitAND(GUICtrlRead($aRadio[04]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\New_Seg_Memo.exe")
					If BitAND(GUICtrlRead($aRadio[05]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Lease_Memo.exe")
					If BitAND(GUICtrlRead($aRadio[06]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Copy_PN_from_Excel_to_Proval.exe")
					If BitAND(GUICtrlRead($aRadio[07]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Copy_PN_from_Excel_to_Lotus.exe")
					If BitAND(GUICtrlRead($aRadio[08]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Copy_PN_to_Ascend.exe")
					If BitAND(GUICtrlRead($aRadio[09]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\EU_Memo.exe")
					If BitAND(GUICtrlRead($aRadio[10]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\test.exe")
					If BitAND(GUICtrlRead($aRadio[11]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Asphalt.exe")
					If BitAND(GUICtrlRead($aRadio[12]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Flatwork.exe")
					If BitAND(GUICtrlRead($aRadio[13]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\CB_Wall.exe")
					If BitAND(GUICtrlRead($aRadio[14]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\SB_Wall.exe")
					If BitAND(GUICtrlRead($aRadio[15]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\CLF_4TR.exe")
					If BitAND(GUICtrlRead($aRadio[16]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\4Slats.exe")
					If BitAND(GUICtrlRead($aRadio[17]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\CLF_6TR.exe")
					If BitAND(GUICtrlRead($aRadio[18]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\6Slats.exe")
					If BitAND(GUICtrlRead($aRadio[19]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\CLF_6TR3sbw.exe")
					If BitAND(GUICtrlRead($aRadio[20]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Light_SL.exe")
					If BitAND(GUICtrlRead($aRadio[21]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Light_DL.exe")
					If BitAND(GUICtrlRead($aRadio[22]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Light_TL.exe")
					If BitAND(GUICtrlRead($aRadio[23]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Light_QL.exe")
					If BitAND(GUICtrlRead($aRadio[24]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\SB_Fence.exe")
					If BitAND(GUICtrlRead($aRadio[25]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Loading_Dock.exe")
					If BitAND(GUICtrlRead($aRadio[26]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Loading_Well.exe")
					If BitAND(GUICtrlRead($aRadio[27]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Loading_Well_Walls.exe")
					If BitAND(GUICtrlRead($aRadio[28]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Trash_Enclosure.exe")
					If BitAND(GUICtrlRead($aRadio[29]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\WI_Fence.exe")
					If BitAND(GUICtrlRead($aRadio[30]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Canopy_Low.exe")
					If BitAND(GUICtrlRead($aRadio[31]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Copy_PN_from_FS_to_Proval.exe")
					If BitAND(GUICtrlRead($aRadio[32]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Land_Size.exe")
					If BitAND(GUICtrlRead($aRadio[33]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\BLA_Memo_sf.exe")
					If BitAND(GUICtrlRead($aRadio[34]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\BLA_Memo_ac.exe")
					If BitAND(GUICtrlRead($aRadio[35]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\changeZaptoGH2008.exe")
					If BitAND(GUICtrlRead($aRadio[36]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\changeZaptoBJM2008.exe")
					If BitAND(GUICtrlRead($aRadio[37]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\changeZaptoTH2008.exe")
					If BitAND(GUICtrlRead($aRadio[38]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\changeZaptoBJM2008nc.exe")
					If BitAND(GUICtrlRead($aRadio[39]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\changeZaptoGH2008NC.exe")
					If BitAND(GUICtrlRead($aRadio[40]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\changeZaptoTH2008nc.exe")
					If BitAND(GUICtrlRead($aRadio[41]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Asphalt.exe")
					If BitAND(GUICtrlRead($aRadio[42]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Flatwork.exe")
					If BitAND(GUICtrlRead($aRadio[43]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Canopy_High.exe")
					If BitAND(GUICtrlRead($aRadio[44]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Conc_over_tanks.exe")
					If BitAND(GUICtrlRead($aRadio[45]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Driveslab.exe")
					If BitAND(GUICtrlRead($aRadio[46]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Excavation.exe")
					If BitAND(GUICtrlRead($aRadio[47]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Electrical.exe")
					If BitAND(GUICtrlRead($aRadio[48]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\UG_Tanks.exe")
					If BitAND(GUICtrlRead($aRadio[49]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\VP_LMS.exe")
					If BitAND(GUICtrlRead($aRadio[50]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Trash_Enclosure.exe")
					If BitAND(GUICtrlRead($aRadio[51]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Piping.exe")
					If BitAND(GUICtrlRead($aRadio[52]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\LightSL.exe")
					If BitAND(GUICtrlRead($aRadio[53]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\LightDL.exe")
					If BitAND(GUICtrlRead($aRadio[54]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Listing_Memo.exe")
					If BitAND(GUICtrlRead($aRadio[55]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Canopy_Ave.exe")
					If BitAND(GUICtrlRead($aRadio[56]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Canopy_Good.exe")
					If BitAND(GUICtrlRead($aRadio[57]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Canopy_High.exe")
					If BitAND(GUICtrlRead($aRadio[58]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Miscellaneous.exe")
					If BitAND(GUICtrlRead($aRadio[59]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Add_Misc.exe")
					If BitAND(GUICtrlRead($aRadio[60]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Add_Memo.exe")
					If BitAND(GUICtrlRead($aRadio[61]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Permits.exe")
					If BitAND(GUICtrlRead($aRadio[62]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Sale_History.exe")
					If BitAND(GUICtrlRead($aRadio[63]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\Con_Ret_Wall.exe")
					If BitAND(GUICtrlRead($aRadio[64]), $GUI_CHECKED) = $GUI_CHECKED Then Run("C:\Documents and Settings\CurrentUser\Desktop\Robots\EXE.files\new_parcel_settup.exe")
				EndFunc	


					


		
	
	
WEnd


