#region --- GuiBuilder code Start ---
; Script generated by AutoBuilder 0.5 Prototype

#include <GuiConstants.au3>
GuiCreate("CalCUlaTEr", 392, 322,(@DesktopWidth-392)/2, (@DesktopHeight-322)/2)

$Button_1 = GuiCtrlCreateButton("multiplacation", 100, 40, 170, 20)
$Button_2 = GuiCtrlCreateButton("division", 100, 70, 170, 20)
$Button_3 = GuiCtrlCreateButton("addition", 100, 100, 170, 20)
$Button_4 = GuiCtrlCreateButton("subtraction", 100, 130, 170, 20)

GuiSetState()
While 1
	$msg = GuiGetMsg()
	Select
	Case $msg = $GUI_EVENT_CLOSE
				MsgBox(0, "are you sure?", "are you sure you would like to exit? click ok below")
$1 = InputBox("exit?", "type yes to exit or if not just close this box")
if $1 = "yes" then ExitLoop
Case $msg = $button_1
	run("multiplacation.exe")
				ExitLoop
			if @error then ContinueLoop
Case $msg = $button_2
	Run("division.exe")
		ExitLoop
		if @error then ContinueLoop
Case $msg = $button_3
	run("addition.exe")
		ExitLoop
			if @error then ContinueLoop
Case $msg = $button_4
	Run("subtraction.exe")
		ExitLoop
			if @error then ContinueLoop
EndSelect
WEnd
Exit
#endregion --- GuiBuilder generated code End ---
