#cs ----------------------------------------------------------------------------
	
	AutoIt Version: 3.2.4.1
	Author:         lokster
	
	Script Function:
	Exx Food additives dadabase.
	
#ce ----------------------------------------------------------------------------

#include <GUIConstants.au3>
#include <Array.au3>

#region ### Tab delimited database ###
$db = "" ; data converted from CSV format
$db &= "Curcumin" & @TAB & "E100" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "" & @TAB & "orange-yellow color; derived from the root of the curcuma (turmeric) plant, but can be artificially produced; used in cheese, margarine, baked sweets and fish fingers" & @CR
$db &= "Riboflavin, Riboflavin-5'-phosphate" & @TAB & "E101" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "" & @TAB & "'Vitamin B2' and color; occurs naturally in greenveges, eggs, milk, liver and kidney; used in margarine and cheese" & @CR
$db &= "Tartrazine" & @TAB & "E102" & @TAB & "Colors" & @TAB & "No" & @TAB & "Provokes asthma attacks, urticaria in children, linked to thyroid tumors, chromosomal damage. Banned in Norway and Austria " & @TAB & "FD&C Yellow No.5; known to provoke asthma attacks (though the US FDA do not recognise this) and urticaria (nettle rash) in children (the US FDA estimates 1:10 000); also linked to thyroid tumours, chromosomal damage, urticaria (hives) and hyperactivity; tartrazine sensitivity is also linked to aspirin sensitivity; used to color drinks, sweets, jams, cereals, snack foods, canned fish, packaged soups; banned in Norway and Austria" & @CR
$db &= "Quinoline Yellow" & @TAB & "E104" & @TAB & "Colors" & @TAB & "No" & @TAB & "cause dermatitis, banned in Australia, USA and Norway" & @TAB & "FD&C Yellow No.10; used in lipsticks hair products, colognes; also in a wide range of medications; cause dermatitis; banned in Australia, USA and Norway" & @CR
$db &= "Yellow 7G" & @TAB & "E107" & @TAB & "Colors" & @TAB & "No" & @TAB & "People who suffer Asthma may also show an allergic reaction to it. Banned in Australia and USA" & @TAB & "yellow color; the HACSG recommends to avoid it; people who suffer Asthma may also show an allergic reaction to it; typical products are soft drinks; banned in Australia and USA" & @CR
$db &= "Sunset Yellow FCF, Orange Yellow S" & @TAB & "E110" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "Many sideeffects, seen increased incidence of tumours in animals. Banned in Norway" & @TAB & "FD&C Yellow No.6; used in cereals, bakery, sweets, snack foods, ice cream, drinks and canned fish; synthetic; also in many medications including Berocca, Polaramine, Ventolin syrup; side effects are urticaria (hives), rhinitis (runny nose), nasal congestion, allergies, hyperactivity, kidney tumours, chromosomal damage, abdominal pain, nausea and vomiting, indigestion, distaste for food; seen increased incidence of tumours in animals; banned in Norway" & @CR
$db &= "Amylase" & @TAB & "E1100" & @TAB & "Miscellaneous" & @TAB & "Yes" & @TAB & "" & @TAB & "derived from mould mushroom or pig pancreas" & @CR
$db &= "Cochineal, Carminic acid, Carmines" & @TAB & "E120" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "HASCG recommends to avoid it" & @TAB & "red color; made from insects; rarely used; the HASCG recommends to avoid it" & @CR
$db &= "Polydextrose" & @TAB & "E1200" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "seems safe in small doses" & @CR
$db &= "Polyvinylpyrrolidone" & @TAB & "E1201" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "dispersing agent, coating for tablets; used in artificial sweeteners" & @CR
$db &= "Polyvinylpolypyrrolidone" & @TAB & "E1202" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "clarifying agent for wine, color and colloidal stabiliser" & @CR
$db &= "Azorubine, Carmoisine" & @TAB & "E122" & @TAB & "Colors" & @TAB & "No" & @TAB & "Banned in Sweden, USA, Austria and Norway" & @TAB & "red color; coal tar derivative; can produce bad reactions in asthmatics and people allergic to aspirin; typical products are confectionary, marzipan, jelly crystals; banned in Sweden, USA, Austria and Norway" & @CR
$db &= "Amaranth" & @TAB & "E123" & @TAB & "Colors" & @TAB & "No" & @TAB & "Can provoke asthma, eczema and hyperactivity; it caused birth defects and foetal deaths in some animal tests, possibly also cancer. Banned in the USA, Russia, Austria and Norway and other countries" & @TAB & "FD&C Red No.2; derived from the small herbaceous plant of the same name; used in cake mixes, fruit-flavoured fillings, jelly crystals; can provoke asthma, eczema and hyperactivity; it caused birth defects and foetal deaths in some animal tests, possibly also cancer. Banned in the USA, Russia, Austria and Norway and other countries" & @CR
$db &= "Ponceau 4R, Cochineal Red A" & @TAB & "E124" & @TAB & "Colors" & @TAB & "No" & @TAB & "Carcinogen in animals, can produce bad reactions in asthmatics and people allergic to aspirin. Banned in USA & Norway" & @TAB & "FD&C Red No.4; synthetic coal tar and azo dye, carcinogen in animals, can produce bad reactions in asthmatics and people allergic to aspirin; banned in USA & Norway" & @CR
$db &= "Erythrosine" & @TAB & "E127" & @TAB & "Colors" & @TAB & "No" & @TAB & "Can lead to hyperthyroidism, thyroid cancer in rats. Banned in January 1990, banned in Norway" & @TAB & "FD&C Red No.3; red color used in cherries, canned fruit, custard mix, sweets, bakery, snack foods; can cause sensitivity to light; can increase thyroid hormone levels and lead to hyperthyroidism, was shown to cause thyroid cancer in rats in a study in 1990; banned in January 1990, but not recalled by the US FDA; banned in Norway" & @CR
$db &= "Red 2G" & @TAB & "E128" & @TAB & "Colors" & @TAB & "No" & @TAB & "Banned in Australia and many other places except UK" & @TAB & "Banned in Australia and many other places except UK" & @CR
$db &= "Allura red AC" & @TAB & "E129" & @TAB & "Colors" & @TAB & "No" & @TAB & "Connected with cancer in mice. Banned in Denmark, Belgium, France, Germany, Switzerland, Sweden, Austria and Norway" & @TAB & "FD&C Red No.40; Orange-red color used in sweets, drinks and condiments, medications and cosmetics, synthetic; introduced in the early eighties to replace amaranth which was considered not safe due to conflicting test results; allura red has also been connected with cancer in mice; banned in Denmark, Belgium, France, Germany, Switzerland, Sweden, Austria and Norway" & @CR
$db &= "Patent blue V" & @TAB & "E131" & @TAB & "Colors" & @TAB & "No" & @TAB & "Banned in Australia, USA and Norway" & @TAB & "Banned in Australia, USA and Norway" & @CR
$db &= "Indigotine, Indigo carmine" & @TAB & "E132" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "May cause nausea, vomiting, high blood pressure, skin rashes, breathing problems and other allergic reactions. Banned in Norway" & @TAB & "FD&C Blue No.2, commonly added to tablets and capsules; also used in ice cream, sweets, baked goods, confectionary, biscuits, synthetic coal tar derivative; may cause nausea, vomiting, high blood pressure, skin rashes, breathing problems and other allergic reactions. Banned in Norway" & @CR
$db &= "Brilliant blue FCF" & @TAB & "E133" & @TAB & "Colors" & @TAB & "No" & @TAB & "Banned in Belgium, France, Germany, Switzerland, Sweden, Austria, Norway" & @TAB & "FD&C Blue Dye No.1; used in dairy products, sweets and drinks, synthetic usually occurring as aluminium lake (solution) or ammonium salt; banned in Belgium, France, Germany, Switzerland, Sweden, Austria, Norway" & @CR
$db &= "Chlorophylis, Chlorophyllins" & @TAB & "E140" & @TAB & "Colors" & @TAB & "No" & @TAB & "" & @TAB & "green color occurs naturally in all plants; used for dyeing waxes and oils, used in medicines and cosmetics" & @CR
$db &= "Starches" & @TAB & "E1400-E1450" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Copper complexes of chloropyll and chlorophyllins" & @TAB & "E141" & @TAB & "Colors" & @TAB & "No" & @TAB & "" & @TAB & "olive color, no adverse effects are known" & @CR
$db &= "Green S" & @TAB & "E142" & @TAB & "Colors" & @TAB & "No" & @TAB & "Banned in Sweden, USA and Norway" & @TAB & "green color; synthetic coal tar derivative; used in canned peas, mint jelly and sauce, packet bread crumbs and cake mixes; banned inSweden, USA and Norway" & @CR
$db &= "Plain caramel" & @TAB & "E150(a)" & @TAB & "Colors" & @TAB & "No" & @TAB & "HACSG recommends to avoid it" & @TAB & "dark brown color made from sucrose; the HACSG recommends to avoid it. used in oyster, soy, fruit and canned sauces, beer, whiskey, biscuits, pickles" & @CR
$db &= "Caustic sulphite caramel" & @TAB & "E150(b)" & @TAB & "Colors" & @TAB & "No" & @TAB & "" & @TAB & "see E150(a)" & @CR
$db &= "Ammonia caramel" & @TAB & "E150(c)" & @TAB & "Colors" & @TAB & "No" & @TAB & "" & @TAB & "see E150(a)" & @CR
$db &= "Sulphite ammonia caramel" & @TAB & "E150(d)" & @TAB & "Colors" & @TAB & "No" & @TAB & "" & @TAB & "see E150(a)" & @CR
$db &= "Triethyl acetate" & @TAB & "E1505" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "Part becomes alcohol in the body" & @TAB & "part becomes alcohol in the body" & @CR
$db &= "Brilliant Black BN, Black PN" & @TAB & "E151" & @TAB & "Colors" & @TAB & "No" & @TAB & "Banned in Denmark, Australia, Belgium, France, Germany, Switzerland, Sweden, Austria, USA, Norway" & @TAB & "coloor; coal tar derivative; used in brown sauces, blackcurrant cake mixes; banned in Denmark, Australia, Belgium, France, Germany, Switzerland, Sweden, Austria, USA, Norway" & @CR
$db &= "Ethanol" & @TAB & "E1510" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "Alcohol" & @TAB & "alcohol" & @CR
$db &= "Glycerol acetates" & @TAB & "E1517, E1518" & @TAB & "Miscellaneous" & @TAB & "Yes" & @TAB & "" & @TAB & "humectants and solvent derived from glycerol; used to coat fresh fruit in the US" & @CR
$db &= "Propylene glycol" & @TAB & "E1520" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "Has been linked with fatal heart attacks, central nervous system depression, contact dermatitis" & @TAB & "humectants, wetting agent, dispersing agent, petroleum based; its glycerine like taste has made it popular for children's medications and other elixirs; used in many topical creams and ointments, cosmetics, hair products and deodorants; has been linked with fatal heart attacks (when given intravenously), central nervous system depression and cosmetic or pharmaceutical contact dermatitis" & @CR
$db &= "Vegetable carbon" & @TAB & "E153" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "Banned in the United States" & @TAB & "black color, charcoal pigment; used in jams, jelly crystals, liquorice; only the vegetable derived variety permitted in Australia, banned in the United States" & @CR
$db &= "Brown FK" & @TAB & "E154" & @TAB & "Colors" & @TAB & "No" & @TAB & "Banned in USA" & @TAB & "banned in USA" & @CR
$db &= "Brown HT (Chocolate)" & @TAB & "E155" & @TAB & "Colors" & @TAB & "No" & @TAB & "Bad reactions in asthmatics and people allergic to aspirin" & @TAB & "brown color, coal tar and azo dye; used in chocolate cake mixes; can produce bad reactions in asthmatics and people allergic to aspirin; also known to induce skin sensitivity; banned in Denmark, Belgium, France, Germany, Switzerland, Sweden, Austria, USA, Norway" & @CR
$db &= "Carotene, alpha-, beta-, gamma-" & @TAB & "E160(a)" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "" & @TAB & "orange-yellow color; human body converts it to 'Vitamin A' in the liver, found in carrots and other yellow or orange fruits and vegetables" & @CR
$db &= "Annatto (Arnatto, Annato), bixin, norbixin" & @TAB & "E160(b)" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "Known to cause urticaria (nettle rash), the HACSG recommends to avoid it" & @TAB & "red color; derived from a tree (Bixa orellana); used as a body paint, fabric dye, digestive aid and expectorant; used to dye cheese, butter, margarine, cereals, snack foods, soaps, textiles and varnishes; known to cause urticaria (nettle rash), the HACSG recommends to avoid it" & @CR
$db &= "Paprika extract, capsanthin, capsorubin" & @TAB & "E160(c)" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Lycopene" & @TAB & "E160(d)" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "" & @TAB & "red colored carotenoid found in tomatoes and pink grapefruit, can cause decreasing risk of cancer" & @CR
$db &= "Beta-apo-8'-carotenal (C 30)" & @TAB & "E160(e)" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "" & @TAB & "orange color, no adverse effects are known" & @CR
$db &= "Ethyl ester of beta-apo-8'-carotenic acid (C 30)" & @TAB & "E160(f)" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "" & @TAB & "orange color, no adverse effects are known" & @CR
$db &= "Xanthophylls - Lutein" & @TAB & "E161(b)" & @TAB & "Colors" & @TAB & "No" & @TAB & "" & @TAB & "yellow color derived from plants, naturally found in green leaves, marigolds and egg yolks" & @CR
$db &= "Xanthophylls - Canthaxanthin" & @TAB & "E161(g)" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "Found to accumulate on the retina, having a detrimental effect on eyesight" & @TAB & "yellow color possibly derived from animal sources (retinol); the pigment is found in some mushrooms, crustacea, fish, flamingo feathers" & @CR
$db &= "Beetroot Red, Betanin" & @TAB & "E162" & @TAB & "Colors" & @TAB & "No" & @TAB & "" & @TAB & "purple color derived from beets; no adverse effects are known" & @CR
$db &= "Anthocyanins" & @TAB & "E163" & @TAB & "Colors" & @TAB & "No" & @TAB & "" & @TAB & "violet color matter of flowers and plants; seems safe" & @CR
$db &= "Calcium carbonate" & @TAB & "E170" & @TAB & "Colors" & @TAB & "Yes" & @TAB & "" & @TAB & "mineral salt, used in toothpastes, white paint and cleaning powders; may be derived from rock mineral or animal bones; sometimes used to deacidify wines and firm canned fruit and veg.; toxic at 'high doses'" & @CR
$db &= "Titanium dioxide" & @TAB & "E171" & @TAB & "Colors" & @TAB & "No" & @TAB & "" & @TAB & "white color used in toothpaste and white paint, pollutes waterways; no adverse effects are known" & @CR
$db &= "Iron oxides and hydroxides" & @TAB & "E172" & @TAB & "Colors" & @TAB & "No" & @TAB & "" & @TAB & "black, yellow, red color used in salmon and shrimp pastes; toxic at 'high doses'" & @CR
$db &= "Aluminium" & @TAB & "E173" & @TAB & "Colors" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Silver" & @TAB & "E174" & @TAB & "Colors" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Gold" & @TAB & "E175" & @TAB & "Colors" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Latolrubine BK" & @TAB & "E180" & @TAB & "Colors" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Tannic acid, tannins" & @TAB & "E181" & @TAB & "Colors" & @TAB & "No" & @TAB & "" & @TAB & "clarifying agent in alcohol; derived from the nutgalls and twigs of oak trees; occurs naturally in tea" & @CR
$db &= "Sorbic acid" & @TAB & "E200" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Possible skin irritant" & @TAB & "either obtained from berries or synthesised from ketene; possible skin irritant" & @CR
$db &= "Sodium sorbate" & @TAB & "E201" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Potassium sorbate" & @TAB & "E202" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Calcium sorbate" & @TAB & "E203" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Benzoic acid" & @TAB & "E210" & @TAB & "Preservatives" & @TAB & "Yes" & @TAB & "Can cause asthma, hyperactivity in children" & @TAB & "also known as flowers of benzoin, phenlycarboxylic acid, carboxybenzene; added to alcoholic beverages, baked goods, cheeses, gum, condiments, frozen dairy, relishes, soft sweets, cordials and sugar substitutes; used in cosmetics, as an antiseptic in many cough medications and an antifungal in ointments; can cause asthma, especially in those dependant on steroid asthma medications, is also reputed to cause neurological disorders and to react with sulphur bisulphite (222), shown to provoke hyperactivity in children; obtained from Benzoin, a resin exuded by trees native to Asia" & @CR
$db &= "Sodium benzoate" & @TAB & "E211" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Known to causes nettle rash and aggravate asthma" & @TAB & "used as antiseptic, as a food preservative and to disguise taste, as of poor-quality food; orange soft drinks contain a high amount of it, upto 25mg per 250ml; also in milk and meat products, relishes and condiments, baked goods and lollies; used in many oral medications including Actifed, Phenergan and Tylenol; known to causes nettle rash and aggravate asthma" & @CR
$db &= "Potassium benzoate" & @TAB & "E212" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Allergic reactions" & @TAB & "people with a history of allergies may show allergic reactions. for using see 210" & @CR
$db &= "Calcium benzoate" & @TAB & "E213" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "" & @TAB & "see 212" & @CR
$db &= "Ethyl p-hydroxybenzoate" & @TAB & "E214" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Sodium ethyl p-hydroxybenzoate" & @TAB & "E215" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Propyl p-hydroxybenzoate" & @TAB & "E216" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Possible contact allergen" & @TAB & "possible contact allergen" & @CR
$db &= "Sodium propyl p-hydroxybenzoate" & @TAB & "E217" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Methyl p-hydroxybenzoate" & @TAB & "E218" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Allergic reactions possible, mainly affecting the skin" & @TAB & "allergic reactions possible, mainly affecting the skin" & @CR
$db &= "Sodium methyl p-hydroxybenzoate" & @TAB & "E219" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Sulphur dioxide" & @TAB & "E220" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Known to provoke asthma attacks, difficult to metabolize, destroys vitamin B1" & @TAB & "derived from coal tar; all sulphur drugs are toxic and restricted in use (in USA, FDA prohibits their use on raw fruits and vegetables), produced by combustion of sulphur or gypsum; known to provoke asthma attacks and difficult to metabolise for those with impaired kidney function, also destroys vitamin B1; typical products are beer, soft drinks, dried fruit, juices, cordials, wine, vinegar, potato products" & @CR
$db &= "Sodium sulphite" & @TAB & "E221" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Dangerous additives for health" & @TAB & "decontaminating agent used in fresh orange juice; see 220" & @CR
$db &= "Sodium hydrogen sulphite" & @TAB & "E222" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Dangerous additives for health" & @TAB & "see 220" & @CR
$db &= "Sodium metabisulphite" & @TAB & "E223" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Dangerous additives for health" & @TAB & "treating agent, see 220" & @CR
$db &= "Potassium metabisulphite" & @TAB & "E224" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Dangerous additives for health" & @TAB & "see 220" & @CR
$db &= "Potassium sulphite" & @TAB & "E225" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Dangerous additives for health" & @TAB & "see 220" & @CR
$db &= "Calcium sulphite" & @TAB & "E226" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Calcium hydrogen sulphite" & @TAB & "E227" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Potassium hydrogen sulphite" & @TAB & "E228" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Dangerous additives for health" & @TAB & "see 220" & @CR
$db &= "Biphenyl, Diphenyl" & @TAB & "E230" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "banned in some countries; can be used for agricultural purposes; typical products are citrus fruit" & @CR
$db &= "Orthophenyl phenol" & @TAB & "E231" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "banned in some countries; can be used for agricultural purposes; typical products are pears, carrots, peaches, plums, prunes, sweet potatoe, citrus fruit, pineapples, tomatoes, peppers, cherries, nectarines" & @CR
$db &= "Sodium orthophenyl phenol" & @TAB & "E232" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "see 231" & @CR
$db &= "Thiabendazole" & @TAB & "E233" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "banned in some countries, can be used for agricultural purposes, typical products are citrus fruits, apples, pears, potatoes, bananas, mushrooms, meat, milk" & @CR
$db &= "Nisin" & @TAB & "E234" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "" & @TAB & "antibiotic derived from bacteria; found in beer, processed cheese products, tomato paste" & @CR
$db &= "Natamycin" & @TAB & "E235" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Can cause nausea, vomiting, anorexia, diarrhea and skin irritation" & @TAB & "mould inhibitor derived from bacteria; sometimes used medically to treat candidiasis; can cause nausea, vomiting, anorexia, diarrhoea and skin irritation;.typical products are meat, cheese" & @CR
$db &= "Formic acid" & @TAB & "E236" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Sodium formate" & @TAB & "E237" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Calcium formate" & @TAB & "E238" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Hexamethylene tetramine" & @TAB & "E239" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Potassium nitrite" & @TAB & "E249" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Dangerous additives for health" & @TAB & "color fixative and curing agent for meat; nitrites can effect the body's ability to carry oxygen, resulting in shortness of breath, dizziness and headaches; potential carcinogen; not permitted in foods for infant and young children" & @CR
$db &= "Sodium nitrite" & @TAB & "E250" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Potentially carcinogenic, restricted in many countries" & @TAB & "may provoke hyperactivity and other adverse reactions, potentially carcinogenic, restricted in many countries, can combine with chemicals in stomach to form nitrosamine, the HACSG recommends to avoid it" & @CR
$db &= "Sodium nitrate" & @TAB & "E251" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Dangerous additiv for health" & @TAB & "also used in the manufacture of nitric acid, as a fertiliser and in fermented meat products (see 250)" & @CR
$db &= "Potassium nitrate" & @TAB & "E252" & @TAB & "Preservatives" & @TAB & "Yes" & @TAB & "Potentially carcinogenic; restricted in many countries" & @TAB & "may be derived from waste animal or vegetable matter; used in gunpowder, explosives and fertilisers, and in the preservation of meat; may provoke hyperactivity and other adverse reactions; potentially carcinogenic; restricted in many countries (see 249)" & @CR
$db &= "Acetic acid" & @TAB & "E260" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "" & @TAB & "main component of vinegar, synthetically produced from wood fibres; used in pickles, chutneys, and sauces" & @CR
$db &= "Potassium acetate" & @TAB & "E261" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Should be avoided by people with impaired kidney function" & @TAB & "food acid; should be avoided by people with impaired kidney function; typical products are sauces, pickles" & @CR
$db &= "Sodium acetate, Sodium diacetate" & @TAB & "E262" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "" & @TAB & "food acid, acidity regulator; no known adverse effects" & @CR
$db &= "Calcium acetate" & @TAB & "E263" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "" & @TAB & "food acid, acidity regulator; by product in the manufacture of wood alcohol; used to make acetic acid (vinegar) and in the production of dyers mordants" & @CR
$db &= "Ammonium acetate" & @TAB & "E264" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Can cause nausea and vomiting" & @TAB & "can cause nausea and vomiting" & @CR
$db &= "Lactic acid" & @TAB & "E270" & @TAB & "Preservatives" & @TAB & "Yes" & @TAB & "Difficult for babies to metabolize" & @TAB & "food acid, acidity regulator; produced by heating and fermenting carbohydrates in milk whey, potatoes, cornstarch or molasses; difficult for babies to metabolise; used in sweets, dressings, soft drinks (sometimes beer) infant formulas and confectionary" & @CR
$db &= "Propionic acid" & @TAB & "E280" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Dangerous additiv for health" & @TAB & "all propionates are thought to be linked with migraine headaches; propionates occur naturally in fermented foods, human perspiration and ruminants digestive tract, also can be derived commercially from ethylene and carbon monoxide or propionaldehyde or natural gas or fermented wood pulp; produced when bacteria decompose fibre; commonly used in bread and flour products;" & @CR
$db &= "Sodium propionate" & @TAB & "E281" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Linked to migraines" & @TAB & "may be linked to migraines, typical products are flour products" & @CR
$db &= "Calcium propionate" & @TAB & "E282" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Linked to migraines" & @TAB & "see 281" & @CR
$db &= "Potassium propionate" & @TAB & "E283" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Linked to migraines" & @TAB & "see 281" & @CR
$db &= "Carbon dioxide" & @TAB & "E290" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "" & @TAB & "propellant, coolant, derived from lime manufacture; may increase the effect of alcohol; typical products are wine, soft drinks, confectionary" & @CR
$db &= "Malic acid" & @TAB & "E296" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "Infants and young children should avoid it" & @TAB & "derived from fruit or synthetic; infants and young children should avoid it" & @CR
$db &= "Fumaric acid" & @TAB & "E297" & @TAB & "Preservatives" & @TAB & "No" & @TAB & "" & @TAB & "derived from plants of the genus Fumaria esp. F.officianalis or from the fermentation of glucose with fungi; can be used to flavour, acidify, as an antioxidant or raising agent used in soft drinks and cake mixes" & @CR
$db &= "Ascorbic acid" & @TAB & "E300" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "flour treating agent, 'vitamin C'; may be made synthetically from glucose, naturally occurs in fruit and vegetables; added to products as diverse as cured meat, breakfast cereals, frozen fish and wine" & @CR
$db &= "Sodium ascorbate" & @TAB & "E301" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "sodium salt of vitamin C" & @CR
$db &= "Calcium ascorbate" & @TAB & "E302" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "vitamin C, may increase the formation of calcium oxalate stones" & @CR
$db &= "Potassium ascorbate" & @TAB & "E303" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "potassium salt of vitamin C" & @CR
$db &= "Ascorbyl palmitate, Ascorbyl stearate" & @TAB & "E304" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "fatty acid esters of ascorbic acid, same function as E300" & @CR
$db &= "Tocopherol-rich extract (natural)" & @TAB & "E306" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "Vitamin E, known as the anti-sterility vitamin - from the Greek tokos (child) and pherein (bear), is fat-soluble and is a mixture of alpha-, beta-, gamma- and delta- tocopherols. Although eight chemically similar substances have Vitamin E activity, alpha-tocopherol is the most active of these with 100%, followed by beta- (15-40%), gamma- (1-20% then delta (1%). Found in most foods, it is abundant in, amongst other things, whole grain cereals, corn and cottonseed oils, egg yolks, meat and milk. E306 is an antioxidant for polyunsaturated fatty acids in tissue fats and is used in meat pies, desert toppings and vegetable oils as well as a vitamin supplement. Has a greater antioxidant effect than gamma-tocopherol (E308) in animals but not in cells or non-biological matter. It also protects other nutrients, such as Vitamin A, from oxidation but is largely destroyed by freezing. Commercially it can be extracted, by distillation in a vacuum, from cottonseed, maize, rice germ, soya been oil, wheat germ, or green leaves and may, therefore, come from Genetically Modified sources. Because of its antioxidant synergy with Ascorbyl palmitate it is likely to be found in combination with E304." & @CR
$db &= "Alpha-tocopherol (synthetic)" & @TAB & "E307" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "Vitamin E, known as the anti-sterility vitamin - from the Greek tokos (child) and pherein (bear), is fat-soluble and is a mixture of alpha-, beta-, gamma- and delta- tocopherols. Although eight chemically similar substances have Vitamin E activity, alpha-tocopherol is the most active of these with 100%, followed by beta- (15-40%), gamma- (1-20% then delta (1%). Found in most foods, it is abundant in, amongst other things, whole grain cereals, corn and cottonseed oils, egg yolks, meat and milk. E307 is an antioxidant and is used in pork pies and sausages as well as a vitamin supplement. Has a greater antioxidant effect than gamma-tocopherol (E308) in animals but not in cells or non-biological matter. It also protects other nutrients, such as Vitamin A, from oxidation but is largely destroyed by freezing. Commercially it can be produced from cottonseed, maize, rice germ, soya been oil, wheat germ, or green leaves and may, therefore, come from Genetically Modified sources. Because of its antioxidant synergy with Ascorbyl palmitate it is likely to be found in combination with E304." & @CR
$db &= "Gamma-tocopherol (synthetic)" & @TAB & "E308" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "Vitamin E, known as the anti-sterility vitamin - from the Greek tokos (child) and pherein (bear), is fat-soluble and is a mixture of alpha-, beta-, gamma- and delta- tocopherols. Although eight chemically similar substances have Vitamin E activity, alpha-tocopherol is the most active of these with 100%, followed by beta- (15-40%), gamma- (1-20% then delta (1%). Found in most foods, it is abundant in, amongst other things, whole grain cereals, corn and cottonseed oils, egg yolks, meat and milk. E308 is an antioxidant for polyunsaturated fatty acids as well as a vitamin. Less effective than alpha-tocopherol (E306 and E307) in animals but not in non-biological matter. It also protects other nutrients, such as Vitamin A, from oxidation but is largely destroyed by freezing. Commercially it can be produced from cottonseed, maize, rice germ, soya been oil, wheat germ, or green leaves and may, therefore, come from Genetically Modified sources." & @CR
$db &= "Delta-tocopherol (synthetic)" & @TAB & "E309" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "Vitamin E, known as the anti-sterility vitamin - from the Greek tokos (child) and pherein (bear), is fat-soluble and is a mixture of alpha-, beta-, gamma- and delta- tocopherols. Although eight chemically similar substances have Vitamin E activity, alpha-tocopherol is the most active of these with 100%, followed by beta- (15-40%), gamma- (1-20% then delta (1%). Found in most foods, it is abundant in, amongst other things, whole grain cereals, corn and cottonseed oils, egg yolks, meat and milk. E309 is an antioxidant for polyunsaturated fatty acids as well as a vitamin. Reported to be the most effective antioxidant of all the tocopherols in non-biological matter. It also protects other nutrients, such as Vitamin A, from oxidation but is largely destroyed by freezing. Commercially it can be produced from cottonseed, maize, rice germ, soya been oil, wheat germ, or green leaves and may, therefore, come from Genetically Modified sources." & @CR
$db &= "Propyl gallate" & @TAB & "E310" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "May cause gastric or skin irritation, blood disorder, methemoglobinemia" & @TAB & "used to prevent rancidity in oily substances; derived from nutgalls; may cause gastric or skin irritation, gallates are not permitted in foods for infants and small children because of their known tendency to cause the blood disorder, methaemoglobinemia; used in oils, margarine, lard and salad dressings, sometimes used in packaging" & @CR
$db &= "Octyl gallate" & @TAB & "E311" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "See 310" & @TAB & "see 310" & @CR
$db &= "Dodecyl gallate" & @TAB & "E312" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "See 310" & @TAB & "see 310" & @CR
$db &= "Erythorbic acid" & @TAB & "E317" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "produced from sucrose" & @CR
$db &= "Sodium erythorbate" & @TAB & "E318" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "produced from E317" & @CR
$db &= "Tert-ButylHydroQuinone (TBHQ)" & @TAB & "E319" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "May cause nausea, vomiting, delirium. A dose of 5g is considered fatal" & @TAB & "petroleum based; the HACSG recommends to avoid it. May cause nausea, vomiting, delirium. A dose of 5g is considered fatal. Typical products are fats, oils, margarine" & @CR
$db &= "Butylated hydroxy-anisole (BHA)" & @TAB & "E320" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "Not permitted in infant foods, allergic reaction, may trigger hyperactivity, concerns over carcinogenicity and estrogenic effects" & @TAB & "petroleum derivative, retards spoilage due to oxidation; used in edible oils, chewing gum, fats, margarine, nuts, instant potato products, polyethylene food wraps; not permitted in infant foods, can provoke an allergic reaction in some people, may trigger hyperactivity and other intolerances; serious concerns over carcinogenicity and estrogenic effects, in large doses caused tumours in lab animals, banned in Japan in 1958, official committees of experts recommended that it be banned in the UK, however due to industry pressure it was not banned, McDonald's eliminated BHT from their US products by 1986, see also Butyl compounds" & @CR
$db &= "Butylated hydroxy-toluene (BHT)" & @TAB & "E321" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "See 320" & @TAB & "petroleum derivative; see E320" & @CR
$db &= "Lecithins" & @TAB & "E322" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "Yes" & @TAB & "" & @TAB & "emulsifier derived from soy beans, egg yolks, peanuts, corn or animal resources; non toxic but overdose can upset the stomach, kill the appetite and cause profuse sweating; used to allow combination of oils in margarine, chocolate, mayonnaise, milk powder; must be chosen vegetable type" & @CR
$db &= "Sodium lactate" & @TAB & "E325" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "Yes" & @TAB & "Young children with lactose intolerance may show adverse reactions" & @TAB & "derived from milk (lactic acid); may contain pork rennin or whey in process, young children with lactose intolerance may show adverse reactions" & @CR
$db &= "Potassium lactate" & @TAB & "E326" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "Yes" & @TAB & "See 325" & @TAB & "see 325" & @CR
$db &= "Calcium lactate" & @TAB & "E327" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "Yes" & @TAB & "See 325" & @TAB & "see 325" & @CR
$db &= "Ammonium lactate" & @TAB & "E328" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "Yes" & @TAB & "See 325" & @TAB & "see 325" & @CR
$db &= "Magnesium lactate" & @TAB & "E329" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "Yes" & @TAB & "See 325" & @TAB & "see 325" & @CR
$db &= "Citric acid" & @TAB & "E330" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "food acid, naturally derived from citrus fruit, used in biscuits, canned fish, cheese and processed cheese products, infant formulas, cake and soup mixes, rye bread, soft drinks, fermented meat products" & @CR
$db &= "Sodium citrates" & @TAB & "E331" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "food acid; no known adverse effects" & @CR
$db &= "Potassium citrates" & @TAB & "E332" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "food acid; no known adverse effects" & @CR
$db &= "Calcium citrates" & @TAB & "E333" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "food acid; no known adverse effects in small quantities" & @CR
$db &= "Tartaric acid" & @TAB & "E334" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "food acid, obtained from unripe fruit, grape juice; no known adverse effects in small quantities" & @CR
$db &= "Sodium tartrates" & @TAB & "E335" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "food acid; no known adverse effects" & @CR
$db &= "Potassium tartrates" & @TAB & "E336" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "food acid; no known adverse effects" & @CR
$db &= "Sodium potassium tartrate" & @TAB & "E337" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "food acid; no known adverse effects" & @CR
$db &= "Phosphoric acid" & @TAB & "E338" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "food acid, derived from phosphate ore; used in cheese products; no known adverse effects" & @CR
$db &= "Sodium phosphates" & @TAB & "E339" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "mineral salt, used as a laxative and a fixing agent in textile dyeing; high intakes may upset the calcium/phosphorus equilibrium" & @CR
$db &= "Potassium phosphates" & @TAB & "E340" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "see 339" & @CR
$db &= "Calcium phosphates" & @TAB & "E341" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "Yes" & @TAB & "" & @TAB & "mineral salt found in rocks and bones; used in medicines as an antacid and polishing agent in enamels" & @CR
$db &= "Magnesium phosphates" & @TAB & "E343" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "essential mineral, anticaking agent found in salt substitutes" & @CR
$db &= "Sodium malates" & @TAB & "E350" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Potassium malate" & @TAB & "E351" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Calcium malates" & @TAB & "E352" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Metatartaric acid" & @TAB & "E353" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Calcium tartrate" & @TAB & "E354" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "seems safe" & @CR
$db &= "Adipic acid" & @TAB & "E355" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "food acid from the root adipose (pertaining to fat?)" & @CR
$db &= "Potassium adipate" & @TAB & "E357" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Succinic acid" & @TAB & "E363" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Sodium fumarate" & @TAB & "E365" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "food acid, salt of fumaric acid (derived from plants of the genus Fumaria esp. F.officianalis)" & @CR
$db &= "Potassium fumarate" & @TAB & "E366" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Calcium fumarate" & @TAB & "E367" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Heptonolactone" & @TAB & "E370" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Niacin" & @TAB & "E375" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "vitamin B3; naturally occurs in bean, pea and other legumes, milk, egg, meat, poultry, and fish; at doses in excess of 1,000 mg per day can cause liver damage, diabetes, gastritis, eye damage, and elevated blood levels of uric acid (which can cause gout); at amounts as low as 50-100 mg may cause flushing (harmless but painful), headache, and stomach-ache especially if taken on an empty stomach" & @CR
$db &= "Tri-ammonium citrate" & @TAB & "E380" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "may interfere with liver and pancreas function" & @CR
$db &= "Ammonium ferric citrates" & @TAB & "E381" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "" & @TAB & "essential mineral, food acid derived from citric acid; used as a dietary iron supplement in breakfast cereals and dietary formulas" & @CR
$db &= "Calcium disodium EDTA" & @TAB & "E385" & @TAB & "Acids, Antioxidants, Mineral salts" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Alginic acid" & @TAB & "E400" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "thickener and vegetable gum, derived from seaweed; used in custard mix, cordial, flavoured milk, ice blocks, thickened cream and yoghurt; no known adverse effects in small quantities, large quantities can inhibit the absorption of some nutrients" & @CR
$db &= "Sodium alginate" & @TAB & "E401" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "see 400" & @CR
$db &= "Potassium alginate" & @TAB & "E402" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "see 400" & @CR
$db &= "Ammonium alginate" & @TAB & "E403" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "see 400" & @CR
$db &= "Calcium alginate" & @TAB & "E404" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "see 400" & @CR
$db &= "Propylene glycol alginate" & @TAB & "E405" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "thickener and vegetable gum, derived from petroleum; see separate entry" & @CR
$db &= "Agar" & @TAB & "E406" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "thickener and vegetable gum derived from red seaweed; sometimes used as a laxative, found in manufactured meats and ice cream" & @CR
$db &= "Carrageenan" & @TAB & "E407" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "Linked with cancer" & @TAB & "a fibre extracted from seaweed, it has recently been linked with cancer because it may become contaminated when ethylene oxide is added to an inferior product, this results in ethylene chlorohydrins forming, a highly carcinogenic compound; linked to toxic hazards, including ulcers and cancer; the most serious concerns relate to degraded carrageen, which is not a permitted additive; however, native carrageen an, which is used, may become degraded in the gut" & @CR
$db &= "Locust bean gum" & @TAB & "E410" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "derived from Carob or Locust bean tree Ceratonia siliqua; used in lollies, cordials, essences, some flour products, dressings, fruit juice drinks; frequently used as a caffeine-free chocolate substitute; may lower cholesterol levels" & @CR
$db &= "Guar gum" & @TAB & "E412" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "Can cause nausea, flatulence and cramps" & @TAB & "derived from the seeds of Cyamoposis tetragonolobus of Indian origin; fed to cattle in the US; can cause nausea, flatulence and cramps, may reduced cholesterol levels" & @CR
$db &= "Tragacanth" & @TAB & "E413" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "Possible contact allergy" & @TAB & "resin form the tree Astragalus gummifer; used in foods, drugs including nasal solutions, elixirs and tablets; also used as a binder in cosmetics; possible contact allergy" & @CR
$db &= "Acacia" & @TAB & "E414" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "Possible allergen, soothes irritations of mucous membranes" & @TAB & "derived from the sap of Acacia Sengal; easily broken down by the human digestive system; possible allergen, soothes irritations of mucous membranes" & @CR
$db &= "Xanthan gum" & @TAB & "E415" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "derived from the fermentation of corn sugar with a bacterium" & @CR
$db &= "Karaya gum" & @TAB & "E416" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "Possible allergen" & @TAB & "derived from the tree Sterculia urens; often used in conjunction with Carob (E 410), in ice cream, custard and sweets, as a filler for its capability to multiply its volume by 100 times with the addition of water; possible allergen" & @CR
$db &= "Tara gum" & @TAB & "E417" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "derived from the Tara bush, Caesalpinia Spinosa is indigenous to Ecuador and Peru and is grown in Kenya" & @CR
$db &= "Sorbitol" & @TAB & "E420" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "Not permitted in foods for infants and young children, can cause gastric disturbance" & @TAB & "artificial sweetener and humectants; derived from glucose, either obtained from berries or synthesised; used in lollies, dried fruit, pastries, confectionary, low calorie foods, pharmaceutical syrups and ophthalmic preparations and is the seventh most widely used preservative in cosmetics; not permitted in foods for infants and young children, can cause gastric disturbance" & @CR
$db &= "Mannitol" & @TAB & "E421" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "Possible allergen, not permitted in infant foods, may cause nausea, vomiting" & @TAB & "artificial sweetener and humectants; derived from seaweed or the manna ash tree; possible allergen, not permitted in infant foods due to its ability to cause diarrhoea and kidney dysfunction, also may cause nausea, vomiting; typical products are low calorie foods" & @CR
$db &= "Glycerol" & @TAB & "E422" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "Large quantities can cause headaches, thirst, nausea and high blood sugar levels" & @TAB & "humectants and sweetener; oily colorless alcohol; derived by decomposition of natural fats with alkalis; usually as a by-product of soap making using animal fat or vegetable oil; can be obtained from petroleum products sometimes synthesised from propylene or fermented from sugar; used in flexible coatings on sausages and cheeses, also in crystallised and dried fruit, liqueurs and vodka. Glycerine has been shown to protect against DNA damage induced by tumour promoters, ultraviolet lights and radiation, presumably via free radical scavenging; large quantities can cause headaches, thirst, nausea and high blood sugar levels. Typical products are liquors, confectionary, dried fruit, low calorie foods" & @CR
$db &= "Polyoxyethylene stearate" & @TAB & "E430" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "" & @CR
$db &= "Polyoxyethylene stearate " & @TAB & "E431" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "" & @CR
$db &= "Polysorbate 20" & @TAB & "E432" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Polysorbate 80" & @TAB & "E433" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "emulsifiers derived from animal fatty acids; used as synthetic flavourings, surfactants, defoaming agents and dough conditioners; may increase the absorption of fat-soluble substances" & @CR
$db &= "Polysorbate 40" & @TAB & "E434" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Polysorbate 60" & @TAB & "E435" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "see 433" & @CR
$db &= "Polysorbate 65" & @TAB & "E436" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "see 433" & @CR
$db &= "Pectin" & @TAB & "E440(a)" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "Large quantities may cause temporary flatulence or intestinal discomfort" & @TAB & "naturally occurring in the skins of apples; used to thicken jams, jellies and sauces; large quantities may cause temporary flatulence or intestinal discomfort" & @CR
$db &= "Amidated pectin" & @TAB & "E440(b)" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Gelatine" & @TAB & "E441" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "Possible allergen" & @TAB & "possible allergen, may contain 220, asthmatics and people allergic to sulphites beware!" & @CR
$db &= "Ammonium phosphatides" & @TAB & "E442" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Diphosphates" & @TAB & "E450" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "High intakes may upset the calcium/phosphate equilibrium" & @CR
$db &= "Triphosphates" & @TAB & "E451" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "see 450" & @CR
$db &= "Polyphosphates" & @TAB & "E452" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "May cause calcification of the pelvic region in rats, intensify the activity of heavy metals" & @TAB & "can alter the metabolytical activity in humans; in addition to modified starch, they may cause calcification of the pelvic region in rats; they intensify the activity of heavy metals making them easier to cross the intestine wall; they may contain a lot of impurities; in Japan, a group of children were intoxicated with arsine as impurity of ortophosphate used in food" & @CR
$db &= "Cellulose" & @TAB & "E460" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "anti-caking agent; no adverse effects known" & @CR
$db &= "Methyl cellulose" & @TAB & "E461" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "Can cause flatulence, distension, intestinal obstruction" & @TAB & "can cause flatulence, distension, intestinal obstruction" & @CR
$db &= "Hydroxypropyl cellulose" & @TAB & "E463" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Hydroxypropyl methyl cellulose" & @TAB & "E464" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Ethyl methyl cellulose" & @TAB & "E465" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Carboxy methyl cellulose, Sodium carboxy methyl cellulose" & @TAB & "E466" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Sodium caseinate" & @TAB & "E469" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Fatty acids salts" & @TAB & "E470" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Mono & di glycerides of fatty acids" & @TAB & "E471" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Fatty acid esters of glycerides" & @TAB & "E472" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Sucrose esters of fatty acids" & @TAB & "E473" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Sucroglycerides" & @TAB & "E474" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Polyglycerol esters of fatty acids" & @TAB & "E475" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Polyglycerol polyricinoleate" & @TAB & "E476" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Propylene glycol esters of fatty acids" & @TAB & "E477" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "derived from petroleum; no known adverse effects" & @CR
$db &= "Lactylated fatty acid esters of glycerol and propane" & @TAB & "E478" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "" & @CR
$db &= "Thermally oxidized soya bean oil interacted with mono- and diglycerides of fatty acids" & @TAB & "E479(b)" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "Thermally oxidized soya bean oil interacted with mono- and diglycerides of fatty acids" & @CR
$db &= "Dioctyl sodium sulphosuccinate" & @TAB & "E480" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "No" & @TAB & "" & @TAB & "awaiting results of studies" & @CR
$db &= "Sodium stearoyl-2-lactylate" & @TAB & "E481" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Calcium stearoyl-2-lactylate" & @TAB & "E482" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Stearyl tartrate" & @TAB & "E483" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Sorbitan monos tearate" & @TAB & "E491" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Sorbitan tristearate" & @TAB & "E492" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "" & @TAB & "may increase the absorption of fat-soluble substances" & @CR
$db &= "Sorbitan monolaurate" & @TAB & "E493" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Sorbitan mono-oleate" & @TAB & "E494" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Sorbitan monopalmitate" & @TAB & "E495" & @TAB & "Emulsifiers & Stabilisers" & @TAB & "Yes" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Sodium carbonates" & @TAB & "E500" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects in small quantities" & @CR
$db &= "Potassium carbonates" & @TAB & "E501" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Ammonium carbonates" & @TAB & "E503" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Irritant to mucous membranes" & @TAB & "irritant to mucous membranes" & @CR
$db &= "Magnesium carbonate" & @TAB & "E504" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "medically used as an antacid and laxative" & @CR
$db &= "Hydrochloric acid" & @TAB & "E507" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "safe in small quantities" & @CR
$db &= "Potassium chloride" & @TAB & "E508" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Large quantities can cause gastric ulceration" & @TAB & "large quantities can cause gastric ulceration" & @CR
$db &= "Calcium chloride" & @TAB & "E509" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "derived from brine" & @CR
$db &= "Ammonium chloride" & @TAB & "E510" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Should be avoided by people with impaired liver or kidney function" & @TAB & "should be avoided by people with impaired liver or kidney function. Typical products are flour products" & @CR
$db &= "Magnesium chloride" & @TAB & "E511" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "magnesium is an essential mineral" & @CR
$db &= "Sulphuric acid" & @TAB & "E513" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Sodium sulphates" & @TAB & "E514" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "May upset the body's water balance" & @TAB & "may upset the body's water balance" & @CR
$db &= "Potassium sulphates" & @TAB & "E515" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Calcium sulphate" & @TAB & "E516" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "derived from limestone" & @CR
$db &= "Magnesium sulphate" & @TAB & "E518" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "a laxative" & @CR
$db &= "Copper sulphate" & @TAB & "E519" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "essential mineral" & @CR
$db &= "Sodium hydroxide" & @TAB & "E524" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Potassium hydroxide" & @TAB & "E525" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Calcium hydroxide" & @TAB & "E526" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "no adverse effects in small quantities" & @CR
$db &= "Ammonium hydroxide" & @TAB & "E527" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Magnesium hydroxide" & @TAB & "E528" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Calcium oxide" & @TAB & "E529" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "safe in small quantities" & @CR
$db &= "Magnesium oxide" & @TAB & "E530" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Sodium ferrocyanide" & @TAB & "E535" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "no adverse effects known" & @CR
$db &= "Potassium ferrocyanide" & @TAB & "E536" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "by-product of coal gas production; low toxicity" & @CR
$db &= "Dicalcium diphosphate" & @TAB & "E540" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Sodium aluminium phosphate, Acidic" & @TAB & "E541" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Bone phosphate" & @TAB & "E542" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "Yes" & @TAB & "" & @TAB & "derived from bones; used in dried milk for coffee machines" & @CR
$db &= "Calcium polyphosphates" & @TAB & "E544" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Ammonium polyphosphates" & @TAB & "E545" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Silicon dioxide" & @TAB & "E551" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "no adverse effects are known in food use" & @CR
$db &= "Calcium silicate" & @TAB & "E552" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "derived from limestone and diatomaceous earth (the silicified skeletons of diatoms, a single celled plankton), antacid; no known adverse effects" & @CR
$db &= "Magnesium silicates" & @TAB & "E553(a)" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Talc" & @TAB & "E553(b)" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Linked to stomach cancer" & @TAB & "has been linked to stomach cancer, typical products are polished rice, chocolate, confectionary" & @CR
$db &= "Sodium aluminium silicate" & @TAB & "E554" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Known to cause placental problems in pregnancy and has been linked to Alzheimer's" & @TAB & "used in salt, dried milk substitutes and flours; aluminium is known to cause placental problems in pregnancy and has been linked to Alzheimer's" & @CR
$db &= "Calcium aluminium silicate" & @TAB & "E556" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "see 554" & @TAB & "derived from minerals; used in milk powders; see E554" & @CR
$db &= "Bentonite" & @TAB & "E558" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Aluminium silicate (Kaolin)" & @TAB & "E559" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Stearic acid" & @TAB & "E570" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "Yes" & @TAB & "" & @TAB & "possibly of animal origin; see stearates" & @CR
$db &= "Magnesium stearate" & @TAB & "E572" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "Yes" & @TAB & "" & @TAB & "no known adverse effects in food use" & @CR
$db &= "Glucono delta-lactone" & @TAB & "E575" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Sodium gluconate" & @TAB & "E576" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Potassium gluconate" & @TAB & "E577" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Calcium gluconate" & @TAB & "E578" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "no known adverse effects" & @CR
$db &= "Ferrous gluconate" & @TAB & "E579" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "color-retention agent; derived from iron and glucose; used in olives, iron supplements; safe in small amounts" & @CR
$db &= "Ferrous lactate" & @TAB & "E585" & @TAB & "Mineral salts & Anti-caking agents" & @TAB & "No" & @TAB & "" & @TAB & "" & @CR
$db &= "Glutamic acid" & @TAB & "E620" & @TAB & "Flavour enhancers" & @TAB & "Yes" & @TAB & "Young children should avoid it" & @TAB & "flavour enhancer, salt substitute; amino acid present in many animal and vegetable proteins, derived commercially from bacteria; might cause similar problems as MSG(621), young children should avoid it" & @CR
$db &= "Monosodium glutamate (MSG)" & @TAB & "E621" & @TAB & "Flavour enhancers" & @TAB & "No" & @TAB & "Adverse effects appear in some asthmatic people, not permitted in foods for infants and young children; typical products are canned vegetables" & @TAB & "flavour enhancer derived from the fermentation of molasses, salt substitute; adverse effects appear in some asthmatic people, not permitted in foods for infants and young children; typical products are canned vegetables, canned tuna, dressings, many frozen foods" & @CR
$db &= "Monopotassium glutamate" & @TAB & "E622" & @TAB & "Flavour enhancers" & @TAB & "No" & @TAB & "Can cause nausea, vomiting, diarrhea, abdominal cramps" & @TAB & "can cause nausea, vomiting, diarrhoea, abdominal cramps; typical products are low sodium salt substitutes" & @CR
$db &= "Calcium diglutamate" & @TAB & "E623" & @TAB & "Flavour enhancers" & @TAB & "No" & @TAB & "" & @TAB & "salt substitute, no known adverse effects" & @CR
$db &= "Monoammonium glutamate" & @TAB & "E624" & @TAB & "Flavour enhancers" & @TAB & "No" & @TAB & "" & @TAB & "salt substitute, no known adverse effects" & @CR
$db &= "Magnesium diglutamate" & @TAB & "E625" & @TAB & "Flavour enhancers" & @TAB & "No" & @TAB & "" & @TAB & "salt substitute, no known adverse effects" & @CR
$db &= "Guanylic acid" & @TAB & "E626" & @TAB & "Flavour enhancers" & @TAB & "No" & @TAB & "May trigger gout" & @TAB & "may trigger gout" & @CR
$db &= "Disodium guanylate" & @TAB & "E627" & @TAB & "Flavour enhancers" & @TAB & "No" & @TAB & "May trigger gout, not permitted in foods for infants and young children" & @TAB & "isolated from sardines or yeast extract; may trigger gout, not permitted in foods for infants and young children" & @CR
$db &= "Calcium guanylate" & @TAB & "E629" & @TAB & "Flavour enhancers" & @TAB & "No" & @TAB & "May trigger gout" & @TAB & "may trigger gout" & @CR
$db &= "Disodium inosinate" & @TAB & "E631" & @TAB & "Flavour enhancers" & @TAB & "Yes" & @TAB & "May trigger gout, not permitted in foods for infants and young children" & @TAB & "may be prepared from meat or sardines; may trigger gout, not permitted in foods for infants and young children" & @CR
$db &= "Calcium inosinate" & @TAB & "E633" & @TAB & "Flavour enhancers" & @TAB & "No" & @TAB & "May trigger gout" & @TAB & "may trigger gout" & @CR
$db &= "Disodium 5'-ribonucleotide" & @TAB & "E635" & @TAB & "Flavour enhancers" & @TAB & "Yes" & @TAB & "May be associated with itchy skin rashes " & @TAB & "may be associated with itchy skin rashes up to 30 hours after ingestion; rashes may vary from mild to dramatic; the reaction is dose-related and cumulative, some individuals are more sensitive than others; typical foods include flavoured chips, instant noodles and party pies; avoid it, banned in some countries" & @CR
$db &= "Maltol" & @TAB & "E636" & @TAB & "Flavour enhancers" & @TAB & "No" & @TAB & "" & @TAB & "derived from the bark of larch trees, pine needles, chicory wood, oils and roasted malt; it may be produced synthetically" & @CR
$db &= "Ethyl maltol" & @TAB & "E637" & @TAB & "Flavour enhancers" & @TAB & "No" & @TAB & "" & @TAB & "derived from maltol" & @CR
$db &= "Glycine & its sodium salt" & @TAB & "E640" & @TAB & "Flavour enhancers" & @TAB & "Yes" & @TAB & "" & @TAB & "" & @CR
$db &= "Dimethyl polysiloxane" & @TAB & "E900" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "silicone based" & @CR
$db &= "Beeswaxes" & @TAB & "E901" & @TAB & "Miscellaneous" & @TAB & "Yes" & @TAB & "Occasionally causes allergic reactions" & @TAB & "glazing agent, used to wax fruit; see bee products; occasionally causes allergic reactions" & @CR
$db &= "Carnauba wax" & @TAB & "E903" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "Occasionally causes allergic reactions" & @TAB & "derived from a South American palm; used in cosmetics and inks, and to wax fruit; occasionally causes allergic reactions" & @CR
$db &= "Shellac" & @TAB & "E904" & @TAB & "Miscellaneous" & @TAB & "Yes" & @TAB & "Occasionally causes irritations of the skin" & @TAB & "derived from insects; occasionally causes irritations of the skin" & @CR
$db &= "Paraffins, Microcrystalline wax" & @TAB & "E905" & @TAB & "Miscellaneous" & @TAB & "Yes" & @TAB & "May be a link to bowel cancer" & @TAB & "may inhibit absorption of fats and fat soluble vitamins, mild laxative, there may be a link to bowel cancer; used on sweets, in processing yeast, vitamin tablets, dried fruit, confectionary, collagen" & @CR
$db &= "Refined microcrystalline wax" & @TAB & "E907" & @TAB & "Miscellaneous" & @TAB & "Yes" & @TAB & "Avoid it, banned in some countries" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Lanolin" & @TAB & "E913" & @TAB & "Miscellaneous" & @TAB & "Yes" & @TAB & "" & @TAB & "derived from sheep wool" & @CR
$db &= "L-Cystein" & @TAB & "E920" & @TAB & "Miscellaneous" & @TAB & "Yes" & @TAB & "" & @TAB & "flour treatment agent derived from animal hair and chicken feathers" & @CR
$db &= "L-Cystin" & @TAB & "E921" & @TAB & "Miscellaneous" & @TAB & "Yes" & @TAB & "" & @TAB & "see E920" & @CR
$db &= "Potassium bromate" & @TAB & "E924" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "Can cause nausea, vomiting, diarrhea, pain" & @TAB & "large quantities can cause nausea, vomiting, diarrhoea, pain. Typical products are flour products" & @CR
$db &= "Chlorine" & @TAB & "E925" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "destroys nutrients, carcinogen, in some areas tab water is contaminated with it, to make it 'safer' to drink. Typical products are flour products" & @CR
$db &= "Chlorine dioxide" & @TAB & "E926" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "see 925" & @CR
$db &= "Azodicarbonamide" & @TAB & "E927" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "avoid it, banned in some countries" & @CR
$db &= "Benzoyl peroxide" & @TAB & "E928" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "Asthmatics and people with a history of allergies must beware" & @TAB & "approved by FDA for bleaching the carotenoids in refined flours; asthmatics and people with a history of allergies BEWARE, see 210" & @CR
$db &= "Nitrogen" & @TAB & "E931" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "used in freezing and vacuum packing; seems safe" & @CR
$db &= "Nitrous oxide" & @TAB & "E932" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "seems quite safe in small quantities" & @CR
$db &= "Acesulphane potassium" & @TAB & "E950" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "Have been found to cause cancer in animals and may increase your risk of cancer" & @TAB & "High-intensity, non-caloric sweetener; it is about 200 times sweeter than sugar; discovered in 1967 by Hoechst AG; also called Sunett as brand name; used for baked goods, frozen desserts, candies, dairy products, confectionery, pharmaceuticals, oral hygiene, and, most recently, beverages; has not been approved for use in such a wide range of foods; The Center for Science in the Public Interest (CSPI) includes the artificial sweeteners aspartame, saccharine, and acesulfame K as part of their list of the Ten Worst Additives; all three of these sweeteners have been found to cause cancer in animals and may increase your risk of cancer" & @CR
$db &= "Aspartame" & @TAB & "E951" & @TAB & "Miscellaneous" & @TAB & "Yes" & @TAB & "Adverse effects, migraine headaches" & @TAB & "artificial sweetener, too many adverse effects possible to list, some people are allergic to aspartame, migraine headaches a common reaction in these people" & @CR
$db &= "Cyclamic acid" & @TAB & "E952" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "Migraines, can be carcinogenic, banned in the US and UK" & @TAB & "calcium & sodium cyclamate, artificial sweetener; known to cause migraines and other reactions, can be carcinogenic, caused damage ot rats testicles and mouse embriyos in tests, banned in the US and UK due its links with cancer" & @CR
$db &= "Saccharines" & @TAB & "E954" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "May be hazardous to your health, determined to cause cancer in laboratory animals" & @TAB & "calcium & sodium saccharin; artificial sweetener derived from toluene (a known carcinogen); banned in 1977 in the US, but reinstated subject to strict labelling starting: Use of this product may be hazardous to your health, this product contains saccharin which has been determined to cause cancer in laboratory animals" & @CR
$db &= "Thaumatin" & @TAB & "E957" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "artificial sweetener, a protein derived from the tropical plant Thaumococcus danielli; used to sweeten wines, bread and fruit" & @CR
$db &= "Maltitol, Hydrogenated glucose syrup" & @TAB & "E965" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "humectant, starch decomposed with digestive enzymes; used in confectionery, dried fruits, low-joule foods; laxative in high concentrations" & @CR
$db &= "Xylitol" & @TAB & "E967" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "humectant, found in raspberries, plums, lettuce and endives, though produced for commercial purposes from wood pulp; caused kidney stones and a diuretic effect on test rats: a waste of time and the lives of the rats, for the JEFCA in 1983 ruled the tests invalid in relation to humans, the symptoms caused by 'physiological disturbances' in the rats!, we can only imagine what conditions led to upset rats; used in low-joule foods and carbohydratemodified sweets, icecream and jams" & @CR
$db &= "Quillaia extract" & @TAB & "E999" & @TAB & "Miscellaneous" & @TAB & "No" & @TAB & "" & @TAB & "foaming agent, emulsifier, natural surfactant; derived from chilean soap bark tree (Quillaia Saponaria); used in beer and soda; known to promote healing and reduce excessive oiliness in the skin" & @CR
#endregion

Opt("GUIOnEventMode", 1)
#Region ### START Koda GUI section ### Form=E:\FORCDR\AutoIt\fAdditives\Form1.kxf
$Form1_1 = GUICreate("Exx food additives db by lokster", 384, 313, -1, -1)
$Combo1 = GUICtrlCreateCombo("", 8, 8, 369, 25)
GUICtrlSetOnEvent(-1, "Combo1Change")
$Label1 = GUICtrlCreateLabel("Name:", 8, 32, 65, 18)
$Label2 = GUICtrlCreateLabel("Number:", 8, 48, 65, 17)
$Label3 = GUICtrlCreateLabel("Group:", 8, 64, 65, 17)
$Label4 = GUICtrlCreateLabel("Animal origin:", 8, 80, 65, 17)
$Label5 = GUICtrlCreateLabel("Warning:", 8, 96, 65, 17)
$Label6 = GUICtrlCreateLabel("", 80, 32, 292, 17)
$Label7 = GUICtrlCreateLabel("", 80, 48, 292, 17)
$Label8 = GUICtrlCreateLabel("", 80, 64, 292, 17)
$Label9 = GUICtrlCreateLabel("", 80, 80, 292, 17)
$Label10 = GUICtrlCreateLabel("", 80, 96, 292, 57)
$Edit1 = GUICtrlCreateEdit("", 8, 168, 369, 137, BitOR($ES_AUTOVSCROLL, $ES_READONLY, $ES_WANTRETURN, $WS_VSCROLL))
$Label11 = GUICtrlCreateLabel("Description:", 8, 152, 60, 14)
GUISetState(@SW_SHOW)
#EndRegion ### END Koda GUI section ###

GUISetOnEvent($GUI_EVENT_CLOSE, "Bye")

Dim $aRecords
$aRecords = StringSplit($db, @CR)

Dim $names[1], $numbers[1], $groups[1], $origins[1], $warnings[1], $descriptions[1]

For $x = 1 To $aRecords[0]
	$rec = StringSplit($aRecords[$x], @TAB)
	If UBound($rec) >= 7 Then
		_ArrayAdd($names, $rec[1])
		_ArrayAdd($numbers, $rec[2])
		_ArrayAdd($groups, $rec[3])
		_ArrayAdd($origins, $rec[4])
		_ArrayAdd($warnings, $rec[5])
		_ArrayAdd($descriptions, $rec[6])
		GUICtrlSetData($Combo1, $rec[2] & " - " & $rec[1] & "|")
	EndIf
Next

While 1
	Sleep(100)
WEnd

Func Combo1Change()
	Local $index = GUICtrlSendMsg($Combo1, 0x147, 0, 0) + 1 ;CB_GETCURSEL
	GUICtrlSetData($Label6, $names[$index])
	GUICtrlSetData($Label7, $numbers[$index])
	GUICtrlSetData($Label8, $groups[$index])
	GUICtrlSetData($Label9, $origins[$index])
	GUICtrlSetData($Label10, $warnings[$index])
	GUICtrlSetData($Edit1, $descriptions[$index])
EndFunc   ;==>Combo1Change

Func Bye()
	Exit
EndFunc   ;==>Bye