; ----------------------------------------------------------------------------
;
; AutoIt Version: 3.1.0
; Author:        The Blue Vulcan
;
; Script Function:
;	Organise Video Log Files
;
; ----------------------------------------------------------------------------

; Script Start - Add your code below here



LoadMenu()

Func LoadMenu()
	#region --- GuiBuilder code Start ---
; Script generated by AutoBuilder 0.6 Prototype

#include <GuiConstants.au3>

GuiCreate("Pro-Logger Task Chooser", 273, 164,-1, -1 , BitOR($WS_OVERLAPPEDWINDOW, $WS_CLIPSIBLINGS))

$Group_1 = GuiCtrlCreateGroup("Task Chooser", 10, 10, 250, 140)
$Button_2 = GuiCtrlCreateButton("Log New Clips", 20, 30, 110, 30)
$Button_3 = GuiCtrlCreateButton("View Clips and Info", 140, 30, 110, 30)
$Button_4 = GuiCtrlCreateButton("Delete Clips", 20, 70, 110, 30)
$Button_5 = GuiCtrlCreateButton("Export Info", 140, 70, 110, 30)
$Button_6 = GuiCtrlCreateButton("Exit Pro-Logger", 70, 110, 130, 30)

GuiSetState()
While 1
	$msg = GuiGetMsg()
	Select
	Case $msg = $GUI_EVENT_CLOSE
		ExitLoop
	Case $msg = $Button_6
		Exit 0
	Case $msg = $Button_2
		Loadinfo()
	Case $msg = $Button_3
		MainWindow()
	Case Else
		;;;
	EndSelect
WEnd
Exit
#endregion --- GuiBuilder generated code End ---


EndFunc

Func Loadinfo()
Dim $Directory


#region --- GuiBuilder code Start ---
; Script generated by AutoBuilder 0.6 Prototype

#include <GuiConstants.au3>

GUICreate("Pro Logger", 174, 427, -1, -1, BitOR($WS_OVERLAPPEDWINDOW, $WS_CLIPSIBLINGS))

$Group_1 = GUICtrlCreateGroup("Clip Info", 10, 10, 150, 220)
$Button_20 = GUICtrlCreateButton("Set Reel Name:", 20, 30, 130, 30)
$Button_21 = GUICtrlCreateButton("Delete Clip", 70, 65, 80, 30)
$Label_3 = GUICtrlCreateLabel("Clip Name:", 20, 70, 40, 70)
;$Input_4 = GuiCtrlCreateInput("", 20, 50, 130, 20)
$Group_5 = GUICtrlCreateGroup("Time Code", 10, 240, 150, 120)
$Label_6 = GUICtrlCreateLabel("In Point:", 20, 260, 60, 20)
$Label_7 = GUICtrlCreateLabel("Out Point:", 20, 310, 70, 30)
$Input_8 = GUICtrlCreateInput("", 20, 100, 130, 20)
$Input_9 = GUICtrlCreateInput("", 20, 280, 30, 20)
$Input_10 = GUICtrlCreateInput("", 60, 280, 30, 20)
$Input_11 = GUICtrlCreateInput("", 100, 280, 50, 20)
$Input_12 = GUICtrlCreateInput("", 20, 330, 30, 20)
$Input_13 = GUICtrlCreateInput("", 60, 330, 30, 20)
$Input_14 = GUICtrlCreateInput("", 100, 330, 50, 20)
$Button_15 = GUICtrlCreateButton("Log Clip", 10, 370, 80, 40)
$Button_16 = GUICtrlCreateButton("Done", 100, 370, 60, 40)
$Label_17 = GUICtrlCreateLabel("Description:", 20, 130, 60, 20)
$Input_18 = GUICtrlCreateInput("Input18", 150, 220, 1, 1)
$Input_19 = GUICtrlCreateInput("", 20, 150, 130, 70)



GUISetState()
While 1
     $msg = GUIGetMsg()
     Select
		Case $msg = $GUI_EVENT_CLOSE
;			Run("C:\ProLoggerDATA\Pro Logger V0.1.AU3")
              Exit 0
          Case $msg = $Button_15
               ;		$Reel = GuiCtrlRead($Input_4)
               $ClipName = GUICtrlRead($Input_8)
               $Description = GUICtrlRead($Input_19)
               $InHour = GUICtrlRead($Input_9)
               $InMinute = GUICtrlRead($Input_10)
               $InSecond = GUICtrlRead($Input_11)
               $OutHour = GUICtrlRead($Input_12)
               $OutMinute = GUICtrlRead($Input_13)
               $OutSecond = GUICtrlRead($Input_14)
               PrintLogFile()
;               MsgBox(0, "System", "test")
          Case $msg = $Button_16
;			  Run("C:\ProLoggerDATA\Pro Logger V0.1.AU3")
				Exit 0
          Case $msg = $Button_20
               If FileExists("C:\ProLoggerRoot") Then
                    SelectDirectory()
               Else
                    DirCreate("C:\ProLoggerRoot")
                    SelectDirectory()
				EndIf
		Case $msg = $Button_21
				$Deletefile = FileOpenDialog ( "Pro Logger", "C:\ProLoggerRoot", "Text files (*.txt)", 3)
				FileDelete($Deletefile)
     EndSelect
WEnd
#endregion --- GuiBuilder generated code End ---

EndFunc

Func MainWindow()
	#region --- GuiBuilder code Start ---
; Script generated by AutoBuilder 0.6 Prototype

#include <GuiConstants.au3>

GuiCreate("Pro Logger", 760, 564,-1, -1 , BitOR($WS_OVERLAPPEDWINDOW, $WS_CLIPSIBLINGS))

$Group_1 = GuiCtrlCreateGroup("Logged Clips", 10, 10, 240, 510)
$Treeview_2 = GuiCtrlCreateTreeview(20, 30, 220, 480, BitOr($TVS_HASBUTTONS,$TVS_HASLINES,$TVS_LINESATROOT,$TVS_DISABLEDRAGDROP,$TVS_SHOWSELALWAYS),$WS_EX_CLIENTEDGE)
$Group_4 = GuiCtrlCreateGroup("Time-Line", 260, 10, 240, 510)
$Treeview_5 = GuiCtrlCreateTreeview(250, 20, 1, 500,BitOr($TVS_HASBUTTONS,$TVS_HASLINES,$TVS_LINESATROOT,$TVS_DISABLEDRAGDROP,$TVS_SHOWSELALWAYS),$WS_EX_CLIENTEDGE)
$Treeview_7 = GuiCtrlCreateTreeview(270, 30, 220, 480, BitOr($TVS_HASBUTTONS,$TVS_HASLINES,$TVS_LINESATROOT,$TVS_DISABLEDRAGDROP,$TVS_SHOWSELALWAYS),$WS_EX_CLIENTEDGE)
$Button_9 = GuiCtrlCreateButton("->", 230, 530, 60, 20)
$Group_10 = GuiCtrlCreateGroup("Clip Data", 510, 10, 240, 510)
$Group_11 = GuiCtrlCreateGroup("Clip and Reel Name", 520, 30, 220, 80)
$Label_12 = GuiCtrlCreateLabel("Reel Name:", 530, 50, 60, 20)
$Label_13 = GuiCtrlCreateLabel("Clip Name:", 530, 80, 60, 30)
$Label_14 = GuiCtrlCreateLabel("Label14", 590, 50, 1, 20)
$Label_15 = GuiCtrlCreateLabel("(Reel)", 590, 50, 140, 20)
$Label_16 = GuiCtrlCreateLabel("(Clip)", 590, 80, 150, 20)
$Group_17 = GuiCtrlCreateGroup("Time Code Data", 520, 110, 140, 80)
$Label_18 = GuiCtrlCreateLabel("00", 530, 130, 20, 20)
$Label_19 = GuiCtrlCreateLabel(":", 550, 130, 10, 20)
$Label_20 = GuiCtrlCreateLabel("Label20", 550, 140, 1, 1)
$Label_21 = GuiCtrlCreateLabel("52", 560, 130, 20, 20)
$Label_22 = GuiCtrlCreateLabel(":", 580, 130, 10, 20)
$Label_23 = GuiCtrlCreateLabel("16", 590, 130, 20, 20)
$Label_24 = GuiCtrlCreateLabel("In Point", 610, 130, 40, 20)
$Label_25 = GuiCtrlCreateLabel("01", 530, 160, 20, 20)
$Label_26 = GuiCtrlCreateLabel(":", 550, 160, 10, 20)
$Label_27 = GuiCtrlCreateLabel("53", 560, 160, 20, 20)
$Label_28 = GuiCtrlCreateLabel(":", 580, 160, 10, 20)
$Label_29 = GuiCtrlCreateLabel("17", 590, 160, 20, 20)
$Label_30 = GuiCtrlCreateLabel("Out Point", 610, 160, 50, 20)
$Group_31 = GuiCtrlCreateGroup("Clip Description And Quotes", 510, 200, 240, 320)
$Label_32 = GuiCtrlCreateLabel("Clip Description", 520, 220, 220, 290)

;;;Defines existing clips in browser tree
$Reel1Name = "Test Clip"
$Reel1 = GUICtrlCreateTreeViewitem ($Reel1Name ,$Treeview_2)
$Clip1Name = "Jumpingmonkeys"
$Clip1 = GUICtrlCreateTreeViewitem ($Clip1Name, $Reel1)

GuiSetState()
While 1
	$msg = GuiGetMsg()
	Select
	Case $msg = $GUI_EVENT_CLOSE
		ExitLoop
	Case Else
		;;;
	EndSelect
WEnd
Exit
#endregion --- GuiBuilder generated code End ---

EndFunc

Func SelectDirectory()
     $Directory = FileSelectFolder("Please Select a Reel Folder", "C:\ProLoggerRoot", 5)
EndFunc   ;==>SelectDirectory

Func PrintLogFile()
     If FileExists($Directory & "\" & $ClipName & ".txt") = 1 Then
          $overwrite = MsgBox(16, "Pro Logger", "This clip name is already in use for this reel. Useing the same name will result in non-recording of data!")
               $ClipName = InputBox("Pro Logger", "Enter a new name for the clip:", $ClipName)
			   PrintLogFile()
	Else
		  FileChangeDir($Directory)
          FileInstall("C:\ProLoggerDATA\systemdata\VITALDONOTDELETE.txt", $ClipName & ".txt")
		  FileOpen ($ClipName & ".txt.", 2)
		  FileWriteLine($ClipName & ".txt", $Description)
		  FileWriteLine($ClipName & ".txt", $InHour & ":" & $InMinute & ":" & $InSecond)
		  FileWriteLine($ClipName & ".txt", $OutHour & ":" & $OutMinute & ":" & $OutSecond)
		  FileClose($ClipName & ".txt.")
		  
     EndIf
 EndFunc   ;==>PrintLogFile

