
WinWait("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб")
If Not WinActive("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб") Then WinActivate("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб")
WinWaitActive("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб")
MouseMove(721,585)
MouseDown("left")
MouseUp("left")
WinWait("Send virtual smile - Windows Internet Explorer","Командная строка изб")
If Not WinActive("Send virtual smile - Windows Internet Explorer","Командная строка изб") Then WinActivate("Send virtual smile - Windows Internet Explorer","Командная строка изб")
WinWaitActive("Send virtual smile - Windows Internet Explorer","Командная строка изб")
MouseMove(414,98)
MouseDown("left")
MouseUp("left")
WinWait("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб")
If Not WinActive("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб") Then WinActivate("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб")
WinWaitActive("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб")
MouseMove(287,277)
MouseDown("left")
MouseUp("left")
MouseMove(727,592)
MouseDown("left")
MouseUp("left")
WinWait("Send virtual smile - Windows Internet Explorer","Командная строка изб")
If Not WinActive("Send virtual smile - Windows Internet Explorer","Командная строка изб") Then WinActivate("Send virtual smile - Windows Internet Explorer","Командная строка изб")
WinWaitActive("Send virtual smile - Windows Internet Explorer","Командная строка изб")
MouseMove(414,99)
MouseDown("left")
MouseUp("left")
WinWait("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб")
If Not WinActive("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб") Then WinActivate("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб")
WinWaitActive("Windows Live Hotmail - Windows Internet Explorer","Командная строка изб")
MouseMove(283,273)
MouseDown("left")
MouseUp("left")
