$answer = MsgBox(4, "Diablo II", "Login To Battle.Net?")
; Check the user's answer to the prompt (see the help file for MsgBox return values)
; If "No" was clicked (7) then exit the script
If $answer = 7 Then
	iniwrite(@scriptdir & "\D2.ini", "D2Config", "Account", "")
IniWrite(@scriptdir & "\D2.ini", "D2Config", "Password", "")
IniWrite(@scriptdir & "\D2.ini", "D2Config", "SecondsToRunD2", "")
    Exit
EndIf
$acct = iniread(@Desktopdir & "\D2.ini", "D2Config", "Account", "")
sleep(50)
$pw = iniread(@Desktopdir & "\D2.ini", "D2Config", "Password", "")
$sleep = iniread(@desktopdir & "\d2.ini", "D2Config", "SecondsToRunD2", "")
sleep(50)
; run Diablo II
Run("C:\Program Files\Diablo II\Diablo II.exe")
; running sleep for execution
Sleep($sleep)
Send("{ENTER}")
Send("{ENTER}")
Send("{ENTER}")
Sleep(3000)
MouseClick("left", 450, 340)
Sleep(2000)
MouseClick("left")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send("{BACKSPACE}")
Send($acct)
Send("{TAB}")
Sleep(500)
Send($pw)
Send("{ENTER}")
Sleep(1000)
MouseClick("left", 192, 307)
Sleep(500)
Send("{ENTER}")
Sleep(500)
MouseClick("left", 91, 462)

