Run("Setup.exe")
WinWaitActive("Home Cinema Setup")
Send("!n")
WinWaitActive("Home Cinema Setup", "End User License Agreement")
Send("!y")
WinWaitActive("Home Cinema Setup", "Please enter your name and the name of the company for whom you work.")
Send("!n")
WinWaitActive("Home Cinema Setup", "Setup will install Home Cinema in the following folder.")
Send("!n")
WinWaitActive("Home Cinema Setup", "Setup will add program icons to the Program Folder listed below.")
Send("!n")
WinWaitActive("Home Cinema Setup", "Please select the software you want to install from the following list.")
Send("!n")
WinWaitActive("Home Cinema Setup", "Setup has completed the Home Cinema installation.")
Send("{TAB}")
Send("{SPACE}")
Send("{TAB}")
Send("{SPACE}")
Send("!F")
