Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
Run('reader.exe')
WinWait("Adobe Reader 9 - Setup","Change &Destination ")
If Not WinActive("Adobe Reader 9 - Setup","Change &Destination ") Then WinActivate("Adobe Reader 9 - Setup","Change &Destination ")
WinWaitActive("Adobe Reader 9 - Setup","Change &Destination ")
Send("{ALTDOWN}n{ALTUP}")
WinWait("Adobe Reader 9 - Setup","Click Install to beg")
If Not WinActive("Adobe Reader 9 - Setup","Click Install to beg") Then WinActivate("Adobe Reader 9 - Setup","Click Install to beg")
WinWaitActive("Adobe Reader 9 - Setup","Click Install to beg")
Send("{ALTDOWN}i{ALTUP}")
WinWait("Adobe Reader 9 - Setup","Setup has successful")
If Not WinActive("Adobe Reader 9 - Setup","Setup has successful") Then WinActivate("Adobe Reader 9 - Setup","Setup has successful")
WinWaitActive("Adobe Reader 9 - Setup","Setup has successful")
Send("{ALTDOWN}f{ALTUP}")
WinWait("Adobe Reader 9 - Setup","&Resume")
If Not WinActive("Adobe Reader 9 - Setup","&Resume") Then WinActivate("Adobe Reader 9 - Setup","&Resume")
WinWaitActive("Adobe Reader 9 - Setup","&Resume")
Send("{ALTDOWN}{ALTUP}")
