Run("C:\Program Files\DataFlux\dfPower Tools\8.0\dbmswin8.exe")
WinWaitActive("Welcome to dfPower DBMS/Copy!")
Send("O")
Send("C C:\Users\eSpace\Desktop\Studies\Newlink\prg\dov.prg")
Send("{ENTER}")
Send("{ALT}+F")
Send("RUN")
WinWaitActive("Processing","",30)
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0","",30)
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0","",30)
Send("{ALT}+F")
Send("Op")
Send("C:\Users\eSpace\Desktop\Studies\Newlink\prg\ds.prg")
Send("{ENTER}")
Send("{ALT}+F")
Send("RUN")
WinWaitActive("Processing","",30)
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0","",30)
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0","",30)
Send("{ALT}+F")
Send("Op")
Send("C:\Users\eSpace\Desktop\Studies\Newlink\prg\ex.prg")
Send("{ENTER}")
Send("{ALT}+F")
Send("RUN")
WinWaitActive("Processing","",30)
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0","",30)
