Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
Run('C:\V8_5\Setup\Setup.exe')
WinWait("NetScreen-Remote Setup","Welcome to the NetSc")
If Not WinActive("NetScreen-Remote Setup","Welcome to the NetSc") Then WinActivate("NetScreen-Remote Setup","Welcome to the NetSc")
WinWaitActive("NetScreen-Remote Setup","Welcome to the NetSc")
MouseMove(346,362)
MouseDown("left")
MouseUp("left")
WinWait("Confirm Uninstall","Do you want to compl")
If Not WinActive("Confirm Uninstall","Do you want to compl") Then WinActivate("Confirm Uninstall","Do you want to compl")
WinWaitActive("Confirm Uninstall","Do you want to compl")
MouseMove(201,78)
MouseDown("left")
MouseUp("left")
WinWait("Uninstall IPSec Security Policy","Would you like to de")
If Not WinActive("Uninstall IPSec Security Policy","Would you like to de") Then WinActivate("Uninstall IPSec Security Policy","Would you like to de")
WinWaitActive("Uninstall IPSec Security Policy","Would you like to de")
MouseMove(190,98)
MouseDown("left")
MouseUp("left")
WinWait("NetScreen-Remote Setup","NetScreen-Remote Set")
If Not WinActive("NetScreen-Remote Setup","NetScreen-Remote Set") Then WinActivate("NetScreen-Remote Setup","NetScreen-Remote Set")
WinWaitActive("NetScreen-Remote Setup","NetScreen-Remote Set")
MouseMove(441,365)
MouseDown("left")
MouseUp("left")
WinWait("NetScreen-Remote Setup","Yes, I want to resta")
If Not WinActive("NetScreen-Remote Setup","Yes, I want to resta") Then WinActivate("NetScreen-Remote Setup","Yes, I want to resta")
WinWaitActive("NetScreen-Remote Setup","Yes, I want to resta")
MouseMove(283,18)
MouseDown("left")
MouseMove(426,21)
MouseUp("left")
MouseMove(344,356)
MouseDown("left")
MouseUp("left")
