#cs ----------------------------------------------------------------------------

 AutoIt Version: 3.2.12.0
 Author:         ludocus

 Script Function:
	Template AutoIt script.

#ce ----------------------------------------------------------------------------

; Script Start - Add your code below here

global const $L_AFRIKAN = '0436'
global const $L_ALBANIAN = '041c' 
global const $L_ARABIC_SUADI_ARABIA = '0401' 
global const $L_ARABIC_IRAQ = '0801'
global const $L_ARABIC_EGYPT = '0c01' 
global const $L_ARABIC_LIBYA = 1001 
global const $L_ARABIC_ALGERIA = 1401 
global const $L_ARABIC_MOROCCO = 1801
global const $L_ARABIC_TUNISIA = '1c01'
global const $L_ARABIC_OMAN = 2001
global const $L_ARABIC_YEMEN = 2401 
global const $L_ARABIC_SYRIA = 2801 
global const $L_ARABIC_JORDAN = '2c01'
global const $L_ARABIC_LEBANON = 3001 
global const $L_ARABIC_KUWAIT = 3401
global const $L_ARABIC_UAE = 3801
global const $L_ARABIC_BAHRAIN = '3c01'
global const $L_ARABIC_QATAR = 4001
global const $L_ARMENIAN = '042b'
global const $L_AZERI_LATIN0= '042c'
global const $L_AZERI_CYRILLIC = '082c'
global const $L_BASQUE = '042d'
global const $L_BELARUSIAN = '0423'
global const $L_BULGARAIN = '0402'
global const $L_CATALAN = '0403'
global const $L_CHINESE_TAIWAN = '0404'
global const $L_CHINESE_PRC = '0804'
global const $L_CHINESE_HONG_KONG = '0c04'
global const $L_CHINESE_SINGAPORE= 1004
global const $L_CHINESE_MACAU = 1404
global const $L_CROATIAN = '041a'
global const $L_CZECH = '0405'
global const $L_DANISH = '0406'
global const $L_DUTCH = '0413'
global const $L_DUTCH_BELGIAN = '0813'
global const $L_ENGLISH_USA = '0409'
global const $L_ENGLISH_UK = '0809'
global const $L_ENGLISH_AUSTRALIAN = '0c09'
global const $L_ENGLISH_CANADIAN = 1009
global const $L_ENGLISH_NEW_ZEALAND = 1409
global const $L_ENGLISH_IRISH = 1809
global const $L_ENGLISH_SOUTH_AFRICA = '1c09'
global const $L_ENGLISH_JAMAICA = 2009
global const $L_ENGLISH_CARIBBEAN = 2409
global const $L_ENGLISH_BELIZE = 2809
global const $L_ENGLISH_TRINIDAD = '2c09'
global const $L_ENGLISH_ZIMBABWE = 3009
global const $L_ENGLISH_PHILIPPINES = 3409
global const $L_ESTONIAN = '0425'
global const $L_FAEROESE = '0438'
global const $L_FARSI = '0429'
global const $L_FINISH = '040b'
global const $L_FRENCH = '040c'
global const $L_FRENCH_BELGIAN = '080c'
global const $L_FRENCH_CANADIAN = '0c0c'
global const $L_FRENC_SWISS = '100c'
global const $L_FRENCH_LUXEMBOURG = '140c'
global const $L_FRENCH_MONACO = '180c'
global const $L_GEORGIAN = '0437'
global const $L_GERMAN = '0407'
global const $L_GERMAN_SWISS = '0807'
global const $L_GERMAN_AUSTRIAN = '0c07'
global const $L_GERMAN_LUXEMBOURG = 1007
global const $L_GERMAN_LIECHTENSTEIN = 1407
global const $L_GREEK = 408
global const $L_HEBREW = '040d'
global const $L_HINDI = '0439'
global const $L_HUNGARIAN = '040e'
global const $L_ICELANDIC = '040f'
global const $L_INDONESIAN = '0421'
global const $L_ITALIAN = '0410'
global const $L_ITALIAN_SWISS = '0810'
global const $L_JAPANESE = '0411'
global const $L_KAZAKH = '043f'
global const $L_KONKANI = '0457'
global const $L_KOREAN = '0412'
global const $L_LATVIA = '0426'
global const $L_LITHUANIAN = '0427'
global const $L_MACEDONIAN = '042f'
global const $L_MALAY_MALAYSIA = '043e'
global const $L_MALAY_BRUNEI_DARUSSALAM = '083e'
global const $L_MARATHI = '044e'
global const $L_NORWEGIAN_BOKMAL = '0414'
global const $L_NORWEGIAN_NYNORSK = '0814'
global const $L_POLISH = '0415'
global const $L_PORTUGUESE_BRAZILIAN = '0416'
global const $L_PORTUGUESE = '0816'
global const $L_ROMANIAN = '0418'
global const $L_RUSSIAN = '0419'
global const $L_SANSKRIT = '044f'
global const $L_SERBIAN_LATIN = '081a'
global const $L_SERBIAN_CYRILLIC = '0c1a'
global const $L_SLOVAK = '041b'
global const $L_SLOVENIAN = '0424'
global const $L_SPANISH_TRADITIONAL_SORT = '040a'
global const $L_SPANISH_MEXICAN = '080a'
global const $L_SPANISH_MODERN_SORT = '0c0a'
global const $L_SPANISH_GUATEMALA = '100a'
global const $L_SPANISH_COSTA_RICA = '140a'
global const $L_SPANISH_PANAMA = '180a'
global const $L_SPANISH_DOMINICAN_REPUBLIC = '1c0a'
global const $L_SPANISH_VENEZUELA = '200a'
global const $L_SPANISH_COLOMBIA = '240a'
global const $L_SPANISH_PERU = '280a'
global const $L_SPANISH_ARGENTINA = '2c0a'
global const $L_SPANISH_ECUADOR = '300a'
global const $L_SPANISH_CHILE = '340a'
global const $L_SPANISH_URUGUAY = '380a'
global const $L_SPANISH_PARAGUAY = '3c0a'
global const $L_SPANISH_BOLIVIA = '400a'
global const $L_SPANISH_EL_SALVADOR = '440a'
global const $L_SPANISH_HONDURAS = '480a'
global const $L_SPANISH_NICARAGUA = '4c0a'
global const $L_SPANISH_PUERTO_RICO = '500a'
global const $L_SWAHILI = '0441'
global const $L_SWEDISH = '041d'
global const $L_SWEDISH_FINLAND = '081d'
global const $L_TAMIL = '0449'
global const $L_TATAR = '0444'
global const $L_THAI = '041e'
global const $L_TURKISH = '041f'
global const $L_UKRAINIAN = '0422'
global const $L_URDU = '0420'
global const $L_UZBEK_LATIN = '0443'
global const $UZBEK_CYRILLIC = '0843'
global const $L_VIETNAMESE = '042a'