;"Author BASICOS ; Written by BASICOS autoit forum                                
Run("RUNDLL32 SHELL32.DLL,Control_RunDLL Netcpl.cpl,@0,2")
$nompc=inputbox("Poner nombre Pc","Que nombre de ordenador es este (Nombre en la red)","C-31")
$numpc=inputbox("Poner número","Que número de ordenador es este (para dirección Ip)",StringRight($nompc, 2))
$subred=inputbox("Poner número","Normalmente no cambiar, Que Subred Es este pc, 0 o 2, etc..","0")
Sleep(500)
ControlClick("Red", "", "ListBox1")
send("{DOWN 8}")
ControlClick("Red", "", "Button3")
sleep(1000)
ControlClick("Propiedades de TCP/IP", "", "Button1","left")
Opt("MouseCoordMode", 0)
mouseclick("left",56,202)
sleep(1000)
ControlClick("Propiedades de TCP/IP", "", "Edit1","left",3)
sleep(1000)
send("{BS 3}{DEL 3}192.168." & $subred & "." & $numpc &"{TAB}")
send("255.255.255.0")
MouseClick("left",72,57)
sleep(1000)
send("{DOWN}")
send("{UP}")
mouseclick("left",83,261)
sleep(1000)
ControlClick("Propiedades de TCP/IP", "", "Button3")
ControlClick("Propiedades de TCP/IP", "", "Edit1")
send("192.168." & $subred & ".2")
ControlClick("Propiedades de TCP/IP", "", "Button1")
sleep(2000)
ControlClick("Propiedades de TCP/IP", "", "Button7")
sleep(2000)
ControlCommand("Red", "", "SysTabControl1", "TabRight", "")
ControlClick("Red", "", "Edit1","left",2)
sleep(1000)
send("{BS 8}" & $nompc & "{ENTER}")