#include <Excel.au3>
Local $oExcel = _ExcelBookOpen(@ScriptDir & '\account.xlsx', 0, 0)
For $i = 1 To 1 ;Loop
    $sCellValue = _ExcelReadCell($oExcel, $i, 1)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $j = 1 To 1 ;Loop
    $sCellValue2 = _ExcelReadCell($oExcel, $j, 2)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $k = 1 To 1 ;Loop
    $sCellValue3 = _ExcelReadCell($oExcel, $k, 3)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
WinActivate ("                                                                            - Windows Internet Explorer")
WinWaitActive ("                                                                            - Windows Internet Explorer")
Sleep (1000)
MouseMove ( 1478, 180)
MouseClick ("primary", 1478, 180, 1)
Sleep (3000)
MouseMove ( 96, 402 )
Sleep (3000)
MouseClick("primary", 96, 402, 1)
MouseClick("primary", 48, 416, 1)
Send ( $sCellValue)
Send ( "{TAB}")
Send ( $sCellValue2)
Send ( "{TAB}")
Send ( $sCellValue3)
Send ("{ENTER}")
Sleep (5000)
MouseMove ( 478, 402)
MouseClick("primary", 478, 402, 1)
Sleep (3000)
Send("{CTRLDOWN}")
Send("{SHIFTDOWN}")
Send("s")
Send("{CTRLUP}")
Send("{SHIFTUP}")
Sleep (1000)
Send ( "w:\Imaging\ArchivedReports\Statements\MSSB\" & $sCellValue2 )
Send ("{ENTER}")
winactivate("                                                                                                - Windows Internet Explorer")
winwaitactive("                                                                                                - Windows Internet Explorer")
send ("!{F4}")
For $i = 2 To 2 ;Loop
    $sCellValue = _ExcelReadCell($oExcel, $i, 1)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $j = 2 To 2 ;Loop
    $sCellValue2 = _ExcelReadCell($oExcel, $j, 2)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $k = 2 To 2 ;Loop
    $sCellValue3 = _ExcelReadCell($oExcel, $k, 3)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
WinActivate ("                                                                            - Windows Internet Explorer")
WinWaitActive ("                                                                            - Windows Internet Explorer")
Sleep (1000)
MouseMove ( 1478, 180)
MouseClick ("primary", 1478, 180, 1)
Sleep (3000)
MouseMove ( 96, 402 )
Sleep (3000)
MouseClick("primary", 96, 402, 1)
MouseClick("primary", 48, 416, 1)
Send ( $sCellValue)
Send ( "{TAB}")
Send ( $sCellValue2)
Send ( "{TAB}")
Send ( $sCellValue3)
Send ("{ENTER}")
Sleep (5000)
MouseMove ( 478, 402)
MouseClick("primary", 478, 402, 1)
Sleep (3000)
Send("{CTRLDOWN}")
Send("{SHIFTDOWN}")
Send("s")
Send("{CTRLUP}")
Send("{SHIFTUP}")
Sleep (1000)
Send ( "w:\Imaging\ArchivedReports\Statements\MSSB\" & $sCellValue2 )
Send ("{ENTER}")
winactivate("                                                                                                - Windows Internet Explorer")
winwaitactive("                                                                                                - Windows Internet Explorer")
send ("!{F4}")
For $i = 3 To 3 ;Loop
    $sCellValue = _ExcelReadCell($oExcel, $i, 1)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $j = 3 To 3 ;Loop
    $sCellValue2 = _ExcelReadCell($oExcel, $j, 2)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $k = 3 To 3 ;Loop
    $sCellValue3 = _ExcelReadCell($oExcel, $k, 3)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
WinActivate ("                                                                            - Windows Internet Explorer")
WinWaitActive ("                                                                            - Windows Internet Explorer")
Sleep (1000)
MouseMove ( 1478, 180)
MouseClick ("primary", 1478, 180, 1)
Sleep (3000)
MouseMove ( 96, 402 )
Sleep (3000)
MouseClick("primary", 96, 402, 1)
MouseClick("primary", 48, 416, 1)
Send ( $sCellValue)
Send ( "{TAB}")
Send ( $sCellValue2)
Send ( "{TAB}")
Send ( $sCellValue3)
Send ("{ENTER}")
Sleep (5000)
MouseMove ( 478, 402)
MouseClick("primary", 478, 402, 1)
Sleep (3000)
Send("{CTRLDOWN}")
Send("{SHIFTDOWN}")
Send("s")
Send("{CTRLUP}")
Send("{SHIFTUP}")
Sleep (1000)
Send ( "w:\Imaging\ArchivedReports\Statements\MSSB\" & $sCellValue2 )
Send ("{ENTER}")
winactivate("                                                                                                - Windows Internet Explorer")
winwaitactive("                                                                                                - Windows Internet Explorer")
send ("!{F4}")
For $i = 4 To 4 ;Loop
    $sCellValue = _ExcelReadCell($oExcel, $i, 1)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $j = 4 To 4 ;Loop
    $sCellValue2 = _ExcelReadCell($oExcel, $j, 2)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $k = 4 To 4 ;Loop
    $sCellValue3 = _ExcelReadCell($oExcel, $k, 3)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
WinActivate ("                                                                            - Windows Internet Explorer")
WinWaitActive ("                                                                            - Windows Internet Explorer")
Sleep (1000)
MouseMove ( 1478, 180)
MouseClick ("primary", 1478, 180, 1)
Sleep (3000)
MouseMove ( 96, 402 )
Sleep (3000)
MouseClick("primary", 96, 402, 1)
MouseClick("primary", 48, 416, 1)
Send ( $sCellValue)
Send ( "{TAB}")
Send ( $sCellValue2)
Send ( "{TAB}")
Send ( $sCellValue3)
Send ("{ENTER}")
Sleep (5000)
MouseMove ( 478, 402)
MouseClick("primary", 478, 402, 1)
Sleep (3000)
Send("{CTRLDOWN}")
Send("{SHIFTDOWN}")
Send("s")
Send("{CTRLUP}")
Send("{SHIFTUP}")
Sleep (1000)
Send ( "w:\Imaging\ArchivedReports\Statements\MSSB\" & $sCellValue2 )
Send ("{ENTER}")
winactivate("                                                                                                - Windows Internet Explorer")
winwaitactive("                                                                                                - Windows Internet Explorer")
send ("!{F4}")
For $i = 5 To 5 ;Loop
    $sCellValue = _ExcelReadCell($oExcel, $i, 1)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $j = 5 To 5 ;Loop
    $sCellValue2 = _ExcelReadCell($oExcel, $j, 2)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $k = 5 To 5 ;Loop
    $sCellValue3 = _ExcelReadCell($oExcel, $k, 3)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
WinActivate ("                                                                            - Windows Internet Explorer")
WinWaitActive ("                                                                            - Windows Internet Explorer")
Sleep (1000)
MouseMove ( 1478, 180)
MouseClick ("primary", 1478, 180, 1)
Sleep (3000)
MouseMove ( 96, 402 )
Sleep (3000)
MouseClick("primary", 96, 402, 1)
MouseClick("primary", 48, 416, 1)
Send ( $sCellValue)
Send ( "{TAB}")
Send ( $sCellValue2)
Send ( "{TAB}")
Send ( $sCellValue3)
Send ("{ENTER}")
Sleep (5000)
MouseMove ( 478, 402)
MouseClick("primary", 478, 402, 1)
Sleep (3000)
Send("{CTRLDOWN}")
Send("{SHIFTDOWN}")
Send("s")
Send("{CTRLUP}")
Send("{SHIFTUP}")
Sleep (1000)
Send ( "w:\Imaging\ArchivedReports\Statements\MSSB\" & $sCellValue2 )
Send ("{ENTER}")
winactivate("                                                                                                - Windows Internet Explorer")
winwaitactive("                                                                                                - Windows Internet Explorer")
send ("!{F4}")
For $i = 6 To 6 ;Loop
    $sCellValue = _ExcelReadCell($oExcel, $i, 1)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $j = 6 To 6 ;Loop
    $sCellValue2 = _ExcelReadCell($oExcel, $j, 2)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $k = 6 To 6 ;Loop
    $sCellValue3 = _ExcelReadCell($oExcel, $k, 3)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
WinActivate ("                                                                            - Windows Internet Explorer")
WinWaitActive ("                                                                            - Windows Internet Explorer")
Sleep (1000)
MouseMove ( 1478, 180)
MouseClick ("primary", 1478, 180, 1)
Sleep (3000)
MouseMove ( 96, 402 )
Sleep (3000)
MouseClick("primary", 96, 402, 1)
MouseClick("primary", 48, 416, 1)
Send ( $sCellValue)
Send ( "{TAB}")
Send ( $sCellValue2)
Send ( "{TAB}")
Send ( $sCellValue3)
Send ("{ENTER}")
Sleep (5000)
MouseMove ( 478, 402)
MouseClick("primary", 478, 402, 1)
Sleep (3000)
Send("{CTRLDOWN}")
Send("{SHIFTDOWN}")
Send("s")
Send("{CTRLUP}")
Send("{SHIFTUP}")
Sleep (1000)
Send ( "w:\Imaging\ArchivedReports\Statements\MSSB\" & $sCellValue2 )
Send ("{ENTER}")
winactivate("                                                                                                - Windows Internet Explorer")
winwaitactive("                                                                                                - Windows Internet Explorer")
send ("!{F4}")
For $i = 7 To 7 ;Loop
    $sCellValue = _ExcelReadCell($oExcel, $i, 1)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $j = 7 To 7 ;Loop
    $sCellValue2 = _ExcelReadCell($oExcel, $j, 2)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $k = 7 To 7 ;Loop
    $sCellValue3 = _ExcelReadCell($oExcel, $k, 3)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
WinActivate ("                                                                            - Windows Internet Explorer")
WinWaitActive ("                                                                            - Windows Internet Explorer")
Sleep (1000)
MouseMove ( 1478, 180)
MouseClick ("primary", 1478, 180, 1)
Sleep (3000)
MouseMove ( 96, 402 )
Sleep (3000)
MouseClick("primary", 96, 402, 1)
MouseClick("primary", 48, 416, 1)
Send ( $sCellValue)
Send ( "{TAB}")
Send ( $sCellValue2)
Send ( "{TAB}")
Send ( $sCellValue3)
Send ("{ENTER}")
Sleep (5000)
MouseMove ( 478, 402)
MouseClick("primary", 478, 402, 1)
Sleep (3000)
Send("{CTRLDOWN}")
Send("{SHIFTDOWN}")
Send("s")
Send("{CTRLUP}")
Send("{SHIFTUP}")
Sleep (1000)
Send ( "w:\Imaging\ArchivedReports\Statements\MSSB\" & $sCellValue2 )
Send ("{ENTER}")
winactivate("                                                                                                - Windows Internet Explorer")
winwaitactive("                                                                                                - Windows Internet Explorer")
send ("!{F4}")
For $i = 8 To 8 ;Loop
    $sCellValue = _ExcelReadCell($oExcel, $i, 1)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $j = 8 To 8 ;Loop
    $sCellValue2 = _ExcelReadCell($oExcel, $j, 2)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $k = 8 To 8 ;Loop
    $sCellValue3 = _ExcelReadCell($oExcel, $k, 3)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
WinActivate ("                                                                            - Windows Internet Explorer")
WinWaitActive ("                                                                            - Windows Internet Explorer")
Sleep (1000)
MouseMove ( 1478, 180)
MouseClick ("primary", 1478, 180, 1)
Sleep (3000)
MouseMove ( 96, 402 )
Sleep (3000)
MouseClick("primary", 96, 402, 1)
MouseClick("primary", 48, 416, 1)
Send ( $sCellValue)
Send ( "{TAB}")
Send ( $sCellValue2)
Send ( "{TAB}")
Send ( $sCellValue3)
Send ("{ENTER}")
Sleep (5000)
MouseMove ( 478, 402)
MouseClick("primary", 478, 402, 1)
Sleep (3000)
Send("{CTRLDOWN}")
Send("{SHIFTDOWN}")
Send("s")
Send("{CTRLUP}")
Send("{SHIFTUP}")
Sleep (1000)
Send ( "w:\Imaging\ArchivedReports\Statements\MSSB\" & $sCellValue2 )
Send ("{ENTER}")
winactivate("                                                                                                - Windows Internet Explorer")
winwaitactive("                                                                                                - Windows Internet Explorer")
send ("!{F4}")
For $i = 9 To 9 ;Loop
    $sCellValue = _ExcelReadCell($oExcel, $i, 1)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $j = 9 To 9 ;Loop
    $sCellValue2 = _ExcelReadCell($oExcel, $j, 2)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $k = 9 To 9 ;Loop
    $sCellValue3 = _ExcelReadCell($oExcel, $k, 3)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
WinActivate ("                                                                            - Windows Internet Explorer")
WinWaitActive ("                                                                            - Windows Internet Explorer")
Sleep (1000)
MouseMove ( 1478, 180)
MouseClick ("primary", 1478, 180, 1)
Sleep (3000)
MouseMove ( 96, 402 )
Sleep (3000)
MouseClick("primary", 96, 402, 1)
MouseClick("primary", 48, 416, 1)
Send ( $sCellValue)
Send ( "{TAB}")
Send ( $sCellValue2)
Send ( "{TAB}")
Send ( $sCellValue3)
Send ("{ENTER}")
Sleep (5000)
MouseMove ( 478, 402)
MouseClick("primary", 478, 402, 1)
Sleep (3000)
Send("{CTRLDOWN}")
Send("{SHIFTDOWN}")
Send("s")
Send("{CTRLUP}")
Send("{SHIFTUP}")
Sleep (1000)
Send ( "w:\Imaging\ArchivedReports\Statements\MSSB\" & $sCellValue2 )
Send ("{ENTER}")
winactivate("                                                                                                - Windows Internet Explorer")
winwaitactive("                                                                                                - Windows Internet Explorer")
send ("!{F4}")
For $i = 10 To 10 ;Loop
    $sCellValue = _ExcelReadCell($oExcel, $i, 1)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $j = 10 To 10 ;Loop
    $sCellValue2 = _ExcelReadCell($oExcel, $j, 2)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
 For $k = 10 To 10 ;Loop
    $sCellValue3 = _ExcelReadCell($oExcel, $k, 3)
    ;ConsoleWrite($sCellValue & @CRLF)
 Next
WinActivate ("                                                                            - Windows Internet Explorer")
WinWaitActive ("                                                                            - Windows Internet Explorer")
Sleep (1000)
MouseMove ( 1478, 180)
MouseClick ("primary", 1478, 180, 1)
Sleep (3000)
MouseMove ( 96, 402 )
Sleep (3000)
MouseClick("primary", 96, 402, 1)
MouseClick("primary", 48, 416, 1)
Send ( $sCellValue)
Send ( "{TAB}")
Send ( $sCellValue2)
Send ( "{TAB}")
Send ( $sCellValue3)
Send ("{ENTER}")
Sleep (5000)
MouseMove ( 478, 402)
MouseClick("primary", 478, 402, 1)
Sleep (3000)
Send("{CTRLDOWN}")
Send("{SHIFTDOWN}")
Send("s")
Send("{CTRLUP}")
Send("{SHIFTUP}")
Sleep (1000)
Send ( "w:\Imaging\ArchivedReports\Statements\MSSB\" & $sCellValue2 )
Send ("{ENTER}")
winactivate("                                                                                                - Windows Internet Explorer")
winwaitactive("                                                                                                - Windows Internet Explorer")
send ("!{F4}")