Run("C:\Program Files\DataFlux\dfPower Tools\8.0\dbmswin8.exe")
WinWaitActive("Welcome to dfPower DBMS/Copy!")
Send("O")
Send("C C:\Users\eSpace\Desktop\Studies\Newlink\prg")
Send("{ENTER}")
Send("ds.prg")
Send("{ENTER}")
Send("{ALT}+F")
Send("RUN")
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0","",30)
Send("{ALT}+F")
Send("CLOSE")
Send("NO")
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0","",30)
Send("{ALT}+F")
Send("Ope")
Send("ex.prg")
Send("{ENTER}")
Send("{ALT}+F")
Send("RUN")
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0","",30)
Send("{ALT}+F")
Send("CLOSE")
Send("NO")
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0","",30)
Send("{ALT}+F")
Send("Op")
Send("fa.prg")
Send("{ENTER}")
Send("{ALT}+F")
Send("RUN")
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0","",30)
Send("{ALT}+F")
Send("CLOSE")
Send("NO")