Run("C:\Program Files\DataFlux\dfPower Tools\8.0\dbmswin8.exe")
WinWaitActive("Welcome to dfPower DBMS/Copy!")
Send("O")
Send("C C:\Users\eSpace\Desktop\Studies\Newlink\prg")
Send("{ENTER}")
Send("ae.prg")
Send("{ENTER}")
Send("{ALT}+F")
Send("RUN")
WinWait("dfPower DBMS/Copy for Windows V8.0.0")
Send("{ALT}+F")
Send("CLOSE")
Send("NO")
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0")
Send("{ALT}+F")
Send("Ope")
Send("cm.prg")
Send("{ENTER}")
Send("{ALT}+F")
Send("RUN")
WinWait("dfPower DBMS/Copy for Windows V8.0.0")
Send("{ALT}+F")
Send("CLOSE")
Send("NO")
WinWaitActive("dfPower DBMS/Copy for Windows V8.0.0")
Send("{ALT}+F")
Send("Ope")
Send("dm.prg")
Send("{ENTER}")
Send("{ALT}+F")
Send("RUN")
WinWait("dfPower DBMS/Copy for Windows V8.0.0")
Send("{ALT}+F")
Send("CLOSE")
Send("NO")
