Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
WinWait("classname=Shell_TrayWnd","TF_FloatingLangBar_W")
If Not WinActive("classname=Shell_TrayWnd","TF_FloatingLangBar_W") Then WinActivate("classname=Shell_TrayWnd","TF_FloatingLangBar_W")
WinWaitActive("classname=Shell_TrayWnd","TF_FloatingLangBar_W")
Send("{LWINDOWN}r{LWINUP}")
WinWait("Run","Type the name of a p")
If Not WinActive("Run","Type the name of a p") Then WinActivate("Run","Type the name of a p")
WinWaitActive("Run","Type the name of a p")
Send("e{SHIFTDOWN};{SHIFTUP}\client\setup.exe{ENTER}")
WinWait("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The InstallShield(R)")
If Not WinActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The InstallShield(R)") Then WinActivate("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The InstallShield(R)")
WinWaitActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The InstallShield(R)")
Send("{ALTDOWN}n{ALTUP}")
WinWait("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","I &do not accept the")
If Not WinActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","I &do not accept the") Then WinActivate("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","I &do not accept the")
WinWaitActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","I &do not accept the")
Send("{ALTDOWN}a{ALTUP}{ALTDOWN}n{ALTUP}")
WinWait("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","&Anyone who uses thi")
If Not WinActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","&Anyone who uses thi") Then WinActivate("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","&Anyone who uses thi")
WinWaitActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","&Anyone who uses thi")
Send("courts{ALTDOWN}o{ALTUP}courts{ALTDOWN}n{ALTUP}")
WinWait("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The minimum number o")
If Not WinActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The minimum number o") Then WinActivate("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The minimum number o")
WinWaitActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The minimum number o")
Send("{ALTDOWN}s{ALTUP}{ALTDOWN}n{ALTUP}")
WinWait("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","This feature require")
If Not WinActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","This feature require") Then WinActivate("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","This feature require")
WinWaitActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","This feature require")
Send("{ALTDOWN}c{ALTUP}")
WinWait("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","Browse to the destin")
If Not WinActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","Browse to the destin") Then WinActivate("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","Browse to the destin")
WinWaitActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","Browse to the destin")
Send("{HOME}{SHIFTDOWN}d{SHIFTUP}{RIGHT}{BACKSPACE}{END}{LEFT}{LEFT}{LEFT}{LEFT}{LEFT}{LEFT}{LEFT}{LEFT}{SHIFTDOWN}v{SHIFTUP}40{SHIFTDOWN}w{SHIFTUP}1{ENTER}")
WinWait("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","This feature require")
If Not WinActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","This feature require") Then WinActivate("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","This feature require")
WinWaitActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","This feature require")
Send("{DOWN}{DOWN}{SPACE}{DOWN}{DOWN}{DOWN}{ENTER}{DOWN}{SPACE}{DOWN}{DOWN}{DOWN}{ENTER}{DOWN}{DOWN}{DOWN}{DOWN}{DOWN}{SPACE}{DOWN}{DOWN}{DOWN}{ENTER}{ALTDOWN}n{ALTUP}")
WinWait("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","Click Install to beg")
If Not WinActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","Click Install to beg") Then WinActivate("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","Click Install to beg")
WinWaitActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","Click Install to beg")
Send("{ALTDOWN}i{ALTUP}")
WinWait("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The InstallShield Wi")
If Not WinActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The InstallShield Wi") Then WinActivate("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The InstallShield Wi")
WinWaitActive("Microsoft Business Solutions-Navision 4.0 - InstallShield Wizard","The InstallShield Wi")
Send("{ALTDOWN}f{ALTUP}")
