$handle = PluginOpen("ruby.dll")
$retval = RubyPrivateEval("a='hello world';a")
msgbox(0,"",$retval & "   @error: " & @error & " @extended: " & @extended)
$retval = RubyEval("a")
msgbox(0,"",$retval & "   @error: " & @error & " @extended: " & @extended)
RubyEval("a=2")
$retval = RubyEval("a")
msgbox(0,"",$retval & "   @error: " & @error & " @extended: " & @extended)
PluginClose($handle)
