Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
WinWait("Program Manager","FolderView")
If Not WinActive("Program Manager","FolderView") Then WinActivate("Program Manager","FolderView")
WinWaitActive("Program Manager","FolderView")
MouseMove(36,169)
MouseDown("right")
MouseUp("right")
MouseMove(72,341)
MouseDown("left")
MouseUp("left")
WinWait("Network Connections","FolderView")
If Not WinActive("Network Connections","FolderView") Then WinActivate("Network Connections","FolderView")
WinWaitActive("Network Connections","FolderView")
MouseMove(312,178)
MouseDown("right")
MouseUp("right")
MouseMove(325,346)
MouseDown("left")
MouseUp("left")
WinWait("Wireless Network Connection Properties","This c&onnection use")
If Not WinActive("Wireless Network Connection Properties","This c&onnection use") Then WinActivate("Wireless Network Connection Properties","This c&onnection use")
WinWaitActive("Wireless Network Connection Properties","This c&onnection use")
MouseMove(268,101)
MouseDown("left")
MouseUp("left")
WinWait("Dell Wireless 1510 Wireless-N WLAN Mini-Card Properties","Dell Wireless 1510 W")
If Not WinActive("Dell Wireless 1510 Wireless-N WLAN Mini-Card Properties","Dell Wireless 1510 W") Then WinActivate("Dell Wireless 1510 Wireless-N WLAN Mini-Card Properties","Dell Wireless 1510 W")
WinWaitActive("Dell Wireless 1510 Wireless-N WLAN Mini-Card Properties","Dell Wireless 1510 W")
MouseMove(89,47)
MouseDown("left")
MouseUp("left")
WinWait("Dell Wireless 1510 Wireless-N WLAN Mini-Card Properties","The following proper")
If Not WinActive("Dell Wireless 1510 Wireless-N WLAN Mini-Card Properties","The following proper") Then WinActivate("Dell Wireless 1510 Wireless-N WLAN Mini-Card Properties","The following proper")
WinWaitActive("Dell Wireless 1510 Wireless-N WLAN Mini-Card Properties","The following proper")
MouseMove(53,261)
MouseDown("left")
MouseUp("left")
MouseMove(371,147)
MouseDown("left")
MouseUp("left")
MouseMove(319,175)
MouseDown("left")
MouseUp("left")
MouseMove(75,302)
MouseDown("left")
MouseUp("left")
MouseMove(369,146)
MouseDown("left")
MouseUp("left")
MouseMove(298,163)
MouseDown("left")
MouseUp("left")
MouseMove(197,309)
MouseDown("left")
MouseMove(197,308)
MouseUp("left")
MouseMove(199,210)
MouseDown("left")
MouseMove(188,246)
MouseUp("left")
MouseMove(98,249)
MouseDown("left")
MouseUp("left")
MouseMove(370,148)
MouseDown("left")
MouseUp("left")
MouseMove(325,166)
MouseDown("left")
MouseUp("left")
MouseMove(101,264)
MouseDown("left")
MouseUp("left")
MouseMove(369,145)
MouseDown("left")
MouseMove(366,145)
MouseUp("left")
MouseMove(317,162)
MouseDown("left")
MouseUp("left")
MouseMove(102,286)
MouseDown("left")
MouseMove(102,285)
MouseUp("left")
MouseMove(365,143)
MouseDown("left")
MouseMove(363,144)
MouseUp("left")
MouseMove(312,162)
MouseDown("left")
MouseUp("left")
MouseMove(275,429)
MouseDown("left")
MouseUp("left")
