Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
Run('divx.exe')
WinWait("Language selection","")
If Not WinActive("Language selection","") Then WinActivate("Language selection","")
WinWaitActive("Language selection","")
Send("{ENTER}")
WinWait("DivX for Windows Setup","")
If Not WinActive("DivX for Windows Setup","") Then WinActivate("DivX for Windows Setup","")
WinWaitActive("DivX for Windows Setup","")
Send("{ENTER}")
WinWait("DivX for Windows Setup ","")
If Not WinActive("DivX for Windows Setup ","") Then WinActivate("DivX for Windows Setup ","")
WinWaitActive("DivX for Windows Setup ","")
Send("{ALTDOWN}s{ALTUP}{ALTDOWN}{ALTUP}{ALTDOWN}a{ALTUP}{ALTDOWN}n{ALTUP}{ALTDOWN}n{ALTUP}{ALTDOWN}n{ALTUP}")
WinWait("DivX for Windows Setup","")
If Not WinActive("DivX for Windows Setup","") Then WinActivate("DivX for Windows Setup","")
WinWaitActive("DivX for Windows Setup","")
Send("{ALTDOWN}n{ALTUP}{ALTDOWN}{ALTUP}{ALTDOWN}c{ALTUP}")
