FileInstall("g:\incontrol setup.exe", "%userprofile%\local settings\temp\incontrol setup.exe")
Run("%userprofile%\local settings\temp\incontrol setup.exe")
WinWait("InCtrl5 Installation","This installation pr")
If Not WinActive("InCtrl5 Installation","This installation pr") Then WinActivate("InCtrl5 Installation","This installation pr")
WinWaitActive("InCtrl5 Installation","This installation pr")
Send("{ALTDOWN}n{ALTUP}")
WinWait("InCtrl5 Installation","Select Destination D")
If Not WinActive("InCtrl5 Installation","Select Destination D") Then WinActivate("InCtrl5 Installation","Select Destination D")
WinWaitActive("InCtrl5 Installation","Select Destination D")
Send("{ALTDOWN}n{ALTUP}")
WinWait("InCtrl5 Installation","Select Start Menu Fo")
If Not WinActive("InCtrl5 Installation","Select Start Menu Fo") Then WinActivate("InCtrl5 Installation","Select Start Menu Fo")
WinWaitActive("InCtrl5 Installation","Select Start Menu Fo")
Send("{ALTDOWN}n{ALTUP}")
WinWait("InCtrl5 Installation","You are now ready to")
If Not WinActive("InCtrl5 Installation","You are now ready to") Then WinActivate("InCtrl5 Installation","You are now ready to")
WinWaitActive("InCtrl5 Installation","You are now ready to")
Send("{ALTDOWN}n{ALTUP}")
WinWait("InCtrl5 Installation","Installation Complet")
If Not WinActive("InCtrl5 Installation","Installation Complet") Then WinActivate("InCtrl5 Installation","Installation Complet")
WinWaitActive("InCtrl5 Installation","Installation Complet")
Send("{ALTDOWN}f{ALTUP}")
Exit