Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
Run('java.exe')
WinWait("Java Setup - Welcome","View License Agreeme")
If Not WinActive("Java Setup - Welcome","View License Agreeme") Then WinActivate("Java Setup - Welcome","View License Agreeme")
WinWaitActive("Java Setup - Welcome","View License Agreeme")
Send("{ALTDOWN}a{ALTUP}")
WinWait("Java Setup - Yahoo! Toolbar","Yahoo! Toolbar for F")
If Not WinActive("Java Setup - Yahoo! Toolbar","Yahoo! Toolbar for F") Then WinActivate("Java Setup - Yahoo! Toolbar","Yahoo! Toolbar for F")
WinWaitActive("Java Setup - Yahoo! Toolbar","Yahoo! Toolbar for F")
Send("{TAB}{SPACE}{ALTDOWN}n{ALTUP}")
WinWait("Java Setup - Complete","You have Successfull")
If Not WinActive("Java Setup - Complete","You have Successfull") Then WinActivate("Java Setup - Complete","You have Successfull")
WinWaitActive("Java Setup - Complete","You have Successfull")
Send("{ALTDOWN}f{ALTUP}")
