#cs ----------------------------------------------------------------------------

 AutoIt Version: 3.2.1.13 (beta)
 Author:         myName

 Script Function:
	Template AutoIt script.

#ce ----------------------------------------------------------------------------

Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
WinWait("classname=Shell_TrayWnd","Running Applications")
If Not WinActive("classname=Shell_TrayWnd","Running Applications") Then WinActivate("classname=Shell_TrayWnd","Running Applications")
WinWaitActive("classname=Shell_TrayWnd","Running Applications")
Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
MouseMove(44,16)
MouseDown("left")
MouseUp("left")
MouseMove(70,-57)
MouseDown("left")
MouseUp("left")
WinWait("Run","Type the name of a p")
Sleep(1000)
Send("{DEL}")
Sleep(3000)
If Not WinActive("Run","Type the name of a p") Then WinActivate("Run","Type the name of a p")
WinWaitActive("Run","Type the name of a p")
Send("{DEL}{SHIFTDOWN}c;{SHIFTUP}\{SHIFTDOWN}d{SHIFTUP}ocuments{SPACE}and{SPACE}{SHIFTDOWN}s{SHIFTUP}ettings\crowderr.{SHIFTDOWN}rory{SHIFTUP}\{SHIFTDOWN}d{SHIFTUP}esktop\{SHIFTDOWN}m{SHIFTUP}arket{SPACE}{SHIFTDOWN}i{SHIFTUP}llustrations\{SHIFTDOWN}s{SHIFTUP}ample{SPACE}{SHIFTDOWN}s{SHIFTUP}tock{SPACE}{SHIFTDOWN}r{SHIFTUP}eport{SPACE}{SHIFTDOWN}g{SHIFTUP}raphics\{SHIFTDOWN}m{SHIFTUP}aster{SPACE}{SHIFTDOWN}t{SHIFTUP}emplate\{SHIFTDOWN}m{SHIFTUP}aster{SPACE}{SHIFTDOWN}ss{SHIFTUP}\251-500.xls")
Sleep(3000)
MouseMove(142,152)
MouseDown("left")
MouseUp("left")
WinWait("Microsoft Excel","The workbook you ope")
If Not WinActive("Microsoft Excel","The workbook you ope") Then WinActivate("Microsoft Excel","The workbook you ope")
WinWaitActive("Microsoft Excel","The workbook you ope")
MouseMove(311,127)
MouseDown("left")
MouseUp("left")
Sleep(22000)
MouseMove(104,776)
sleep(300)
Mouseclick("left")
Sleep(300)
MouseMove(21,137)
sleep(300)
Mouseclick("left")
MouseMove(68,41)
sleep(300)
Mouseclick("left")
MouseMove(92,92)
sleep(300)
Mouseclick("left")
Sleep(300)
MouseMove(181,777)
sleep(300)
Mouseclick("left")
Sleep(300)
MouseMove(66,40)
sleep(300)
Mouseclick("left")
Sleep(300)
MouseMove(108,131)
sleep(300)
Mouseclick("left")
sleep(300)
WinWait("Paste Special","")
If Not WinActive("Paste Special","") Then WinActivate("Paste Special","")
WinWaitActive("Paste Special","")
sleep(300)
MouseMove(22,96)
Sleep(300)
Mouseclick("left")
sleep(300)
MouseMove(178,261)
Sleep(300)
Mouseclick("left")
Sleep(300)
WinWait("Microsoft Excel - 251-500","")
If Not WinActive("Microsoft Excel - 251-500","") Then WinActivate("Microsoft Excel - 251-500","")
WinWaitActive("Microsoft Excel - 251-500","")
Sleep(300)
MouseMove(104,778)
Sleep(300)
Mouseclick("left")
Sleep(300)
MouseMove(68,63)
Sleep(300)
Mouseclick("left")
Sleep(300)
MouseMove(1145,40)
Sleep(300)
Mouseclick("left")
Sleep(300)
WinWait("Microsoft Excel - Quotelib","")
If Not WinActive("Microsoft Excel - Quotelib","") Then WinActivate("Microsoft Excel - Quotelib","")
WinWaitActive("Microsoft Excel - Quotelib","")
Send("{RWINDOWN}{m}")

#endregion --- ScriptWriter generated code End --- 




