#include <Constants.au3>
#include <GUIConstantsEx.au3>
#include <Misc.au3>
#include <WindowsConstants.au3>
#include <ButtonConstants.au3>
#include <EditConstants.au3>
#include <StaticConstants.au3>

GuiCreate("SQLBackup", 763, 333, -1, -1, $WS_OVERLAPPED + $WS_CAPTION + $WS_SYSMENU + $WS_VISIBLE + $WS_CLIPSIBLINGS + $WS_MINIMIZEBOX)
Global $date, $DBNAME, $INSTNAME, $DESTNAME, $SHARENAME, $CLUSTNAME, $THREADS, $THREADVAR, $PATHNAME, $Button_1, $Button_2, $Button_3, $Button_4, $Input_5, $Label_6, $Input_7, $Label_8, $Input_9, $Label_10, $Input_11, $Label_12, $Input_13, $Label_14, $Input_15, $Label_16, $Label_18

$Button_1 = GuiCtrlCreateButton("Backup Now", 110, 240, 140, 50)
$Button_2 = GuiCtrlCreateButton("Create Scheduled Task", 280, 240, 140, 50)
$Button_3 = GuiCtrlCreateButton("Restore", 450, 240, 140, 50)
$Button_4 = GuiCtrlCreateButton("Cancel", 610, 240, 140, 50)
$Input_5 = GuiCtrlCreateInput("", 20, 60, 190, 30)
$Label_6 = GuiCtrlCreateLabel("Database Name", 40, 20, 130, 20)
$Input_7 = GuiCtrlCreateInput("", 250, 60, 180, 30)
$Label_8 = GuiCtrlCreateLabel("Instance Name", 270, 30, 130, 20)
$Input_9 = GuiCtrlCreateInput("", 20, 150, 440, 40)
$Label_10 = GuiCtrlCreateLabel("Destination path \\nas\share\ or D:\ but must end with \ do not use quotes", 30, 110, 440, 30)
$Input_11 = GuiCtrlCreateInput("", 500, 150, 190, 40)
$Label_12 = GuiCtrlCreateLabel("Compression Level  1=lowest 10=highest", 500, 110, 230, 20)
$Input_13 = GuiCtrlCreateInput("", 470, 60, 210, 30)
$Label_14 = GuiCtrlCreateLabel("Cluster Network Name", 490, 30, 190, 20)
$Input_15 = GuiCtrlCreateInput("", 40, 240, 40, 40)
$Label_16 = GuiCtrlCreateLabel("Thread Count", 30, 200, 70, 20)
$Label_18 = GuiCtrlCreateLabel("2-15", 50, 220, 40, 20)




Func runsmbp()
EndFunc
GuiSetState()
While 1
	$msg = GuiGetMsg()
	Select
	Case $msg = $GUI_EVENT_CLOSE
		ExitLoop
		Case $msg = $Button_1

			$datevar = ("%date:~-4,4%%date:~-10,2%%date:~-7,2%")
			$data3 = GUICtrlRead($Input_9)
			$data4 = GUICtrlRead($Input_5)
			$data5 = GUICtrlRead($Input_7)
			$data6 = GUICtrlRead($Input_13)
			$data7 = GUICtrlRead($Input_15)
			$data8 = "path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '"
			;		$data9 = GUICtrlRead($Input9)
			$data10 = $data7 + 1

; Non-Clustered & No Named Instance

			If $data5 == "" And $data6 == "" And $data7 == 2 Then
				Run(@ComSpec & ' /k c:\msbp\c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 3 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 4 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 5 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 6 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 7 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 8 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 9 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 10 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 11 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 12 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 13 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 14 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_14.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data6 == "" And $data7 == 15 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_14.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_15.bak.zip)"')
				Exit

; Named Instance non cluster

			ElseIf $data6 == "" And $data7 == 2 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 3 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 4 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 5 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 6 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 7 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 8 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 9 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 10 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 11 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 12 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 13 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 14 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_14.bak.zip)"')
				Exit
			ElseIf $data6 == "" And $data7 == 15 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_14.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_15.bak.zip)"')
				Exit

; Unnamed instance cluster

			ElseIf $data5 == "" And $data7 == 2 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 3 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 4 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 5 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 6 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 7 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 8 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 9 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 10 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 11 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 12 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 13 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 14 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_14.bak.zip)"')
				Exit
			ElseIf $data5 == "" And $data7 == 15 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_14.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_15.bak.zip)"')
				Exit

;Named Instance Cluster

			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 2 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 3 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 4 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 5 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 6 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 7 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 8 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 9 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 10 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 11 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 12 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 13 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 14 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_14.bak.zip)"')
				Exit
			ElseIf $data6 <> "" And $data5 <> "" And $data7 == 15 Then
				Run(@ComSpec & ' /k c:\msbp\msbp.exe backup "db(database=' & $data4 & ';instancename=' & $data5 & ';clusternetworkname=' & $data6 & ';backuptype=full;)" "zip64(level=' & $data6 & ')" "local(path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_1.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_2.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_3.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_4.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_5.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_6.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_7.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_8.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_9.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_10.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_11.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_12.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_13.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_14.bak.zip;path=' & $data3 & '' & $data4 & '\' & $data4 & '.' & $datevar & '_15.bak.zip)"')
				Exit

			EndIf
Case $msg = $Button_4
			Exitloop


	Case Else
		;;;
EndSelect


WEnd
Exit