#region --- GuiBuilder code Start ---
; Script generated by AutoBuilder 0.5 Prototype

#include <GuiConstants.au3>
#include <math.au3>

;If Not IsDeclared('WS_CLIPSIBLINGS') Then Global $WS_CLIPSIBLINGS = 0x04000000

GuiCreate("ReSave", 452, 322,(@DesktopWidth-452)/2, (@DesktopHeight-322)/2 , $WS_OVERLAPPEDWINDOW + $WS_VISIBLE + $WS_CLIPSIBLINGS)

$Label_1 = GuiCtrlCreateLabel("Folder:", 20, 25, 40, 20)
$Label_4 = GuiCtrlCreateLabel("File:", 20, 55, 20, 20)
$Label_5 = GuiCtrlCreateLabel("Extension:", 248, 55, 50, 20)
$Label_7 = GuiCtrlCreateLabel("Start Number:", 20, 85, 70, 20)
$Label_9 = GuiCtrlCreateLabel("End Number:", 190, 85, 70, 20)
$Labelcurr = GuiCtrlCreateLabel("Current File: ", 20, 295, 420, 20)
$Labelper = GuiCtrlCreateLabel("", 385, 85, 70, 20)
$Group_13 = GuiCtrlCreateGroup("", 10, 0, 432, 314)

$InputFolder = GuiCtrlCreateInput("", 60, 20, 290, 20)
$InputFile = GuiCtrlCreateInput("", 60, 50, 180, 20)
$InputStart = GuiCtrlCreateInput("", 90, 80, 90, 20)
$InputStop = GuiCtrlCreateInput("", 260, 80, 90, 20)
$InputExt = GuiCtrlCreateInput("", 300,50,50,20)

$ButtonBrowse = GuiCtrlCreateButton("Browse", 360, 20, 70, 20)
$ButtonStart = GuiCtrlCreateButton("Start", 360, 50, 70, 20)

$Listbox = GuiCtrlCreateList("", 20, 140, 410, 162)
$ProgressBar = GuiCtrlCreateProgress(20, 110, 410, 20)

GuiSetState()
While 1
	$msg = GuiGetMsg()
	Select
	Case $msg = $ButtonBrowse
		$Path = FileOpenDialog("Select an Image", "%userprofile%\Desktop", "Images                                                                                     (*.jpeg;*.jpg;*.bmp;*.png;*.gif)")
			If @error Then
				MsgBox(4096,"","No File(s) chosen")
			Else
				$path = StringReplace($path, "|", @CRLF)
				$TempArr = StringSplit($Path, "\")
				$TempArr2 = StringSplit($path,".")
			If @error Then
				$File = $Path
			Else
				$File = $TempArr[UBound($TempArr) - 1]
				$Extension = $TempArr2[Ubound($TempArr2) - 1]
				$sCount = StringLen($file)
				$sCount2 = StringLen($Extension)
				$path = StringTrimRight($path,$sCount)
				$File = StringTrimRight($file,$scount2 + 1)
					GUICtrlsetData($InputFile,$File)
					GUICtrlsetData($InputFolder,$path)
					GUICtrlsetData($InputExt,"."&$Extension)
  EndIf
EndIf
		
	Case $msg = $ButtonStart
	 $istart = Int(GUICtrlRead($InputStart))
	 $istop = Int(GUICtrlRead($InputStop))
	 $iext = GUICtrlRead($inputext)
	 $ipath = GuiCtrlRead($InputFolder)
	 $ifile = GuiCtrlRead($InputFile)
	 $count = 1
	for $i = $istart to $istop
		If FileExists($ipath & $ifile & $i & $iext) Then
			ClipPut($ipath & $ifile & $i & $iext)
			GUICtrlSetData($Listbox,$ipath & $ifile & $i & $iext)
			
			Sleep(400)
			Run ('mspaint.exe')
			Sleep(400)
			WinWaitActive('untitled')
			Send("^o")
			WinWaitActive('Open')
			Send("^v")
			Send("!o")
			Sleep(500)
			send("^s")
			WinClose($iFile)
			
		Else			
	EndIf
GuiCtrlSetData($progressbar,(($i-$istart)/ ($istop-$istart)) * 100)
GuiCtrlSetData($Labelcurr,"Current File: " & $ipath & $ifile & $i & $iext)
GuiCtrlSetData($Labelper, round((($i-$istart)/ ($istop-$istart)) * 100) & "%")
	next	
		
	Case $msg = $GUI_EVENT_CLOSE
		ExitLoop
	Case Else
		;;;
	EndSelect
WEnd
Exit
#endregion --- GuiBuilder generated code End ---